// SPDX-License-Identifier: GPL-3.0-only
/**
 * Structured content for the PQCTestingValidation module.
 */
import type { ModuleContent } from '@/types/ModuleContentTypes'
import { getAlgorithm } from '@/data/algorithmProperties'
import { getStandard } from '@/data/standardsRegistry'

export const content: ModuleContent = {
  // Corrected 2026-08-22: this read 'p-q-c-testing-validation', an id used
  // NOWHERE else — manifest.ts, the /learn route, the simulation trees and every
  // pre-existing library module_ids value all say 'pqc-testing-validation'. It was
  // invisible until writeback_module_ids.py trusted this field and wrote the bad id
  // onto four library rows, which the hub's C4 check rejected immediately. Tooling
  // keyed on content.ts (learn_snapshot.py, and through it the spot-check rotation)
  // was addressing this module by a name the catalogue does not know.
  moduleId: 'pqc-testing-validation',
  version: '1.0.0',
  lastReviewed: '2026-08-10',
  lastEdited: '2026-08-23',

  standards: [
    getStandard('FIPS 186-5'),
    getStandard('FIPS 203'),
    getStandard('FIPS 204'),
    getStandard('RFC 9794'),
    // DECLARED 2026-08-22 by writeback_module_declarations.py: documents this
    // module already names to a reader. Mechanical since the four-document
    // sampler cap was lifted the same day — declaring no longer costs coverage.
    getStandard('FIPS 202'),
    // DECLARED 2026-08-23: this module tells a reader that keys live in a FIPS 140-3
    // validated module and cited nothing for it. Found by
    // audit_module_designation_aliases.py — the literal-id check could not match the
    // prose "FIPS 140-3" against a row filed as FIPS-140-3-STANDARD.
    getStandard('FIPS-140-3-STANDARD'),
    // DECLARED 2026-08-23: this module labels a hashing mechanism it describes as conforming to FIPS 180-4
    // (the Secure Hash Standard) and cited nothing for it. Found by
    // audit_module_designation_aliases.py — the literal-id check could not match the
    // prose "FIPS 180-4" against a row filed as FIPS-180-4.
    getStandard('FIPS-180-4'),
    // DECLARED 2026-08-23: this module labels an AES-GCM mechanism it describes as conforming to SP 800-38D
    // and cited nothing for it. Found by
    // audit_module_designation_aliases.py — the literal-id check could not match the
    // prose "SP 800-38D" against a row filed as NIST-SP-800-38D.
    getStandard('NIST-SP-800-38D'),
    // DECLARED 2026-08-23: this module names FIPS 198-1 (the keyed-hash MAC standard) for a mechanism it describes and cited nothing for it. Found by
    // audit_module_designation_aliases.py — the literal-id check could not match
    // the prose "FIPS 198-1" against a row filed as FIPS-198-1.
    getStandard('FIPS-198-1'),
    // DECLARED 2026-08-23: this module names "FIPS 197" to a reader and cited
    // nothing for it. Capture verified clean (no Obsoleted-by / Withdrawn header)
    // before declaring — the check that caught RFC 4210, RFC 6712, SP 800-161r1
    // and a misnamed RFC 9700 row earlier the same day.
    getStandard('FIPS-197'),
  ],

  algorithms: [
    getAlgorithm('ECDSA P-384'),
    getAlgorithm('Ed25519'),
    getAlgorithm('ML-DSA-65'),
    getAlgorithm('ML-KEM-768'),
    getAlgorithm('RSA-2048'),
    getAlgorithm('RSA-4096'),
    getAlgorithm('X25519'),
  ],

  deadlines: [
    // No regulatory deadlines detected — add manually if needed
  ],

  narratives: {
    overview:
      'Module ID: pqc-testing-validation. Track: Protocols. Duration: 120 minutes. Difficulty: Advanced. Prerequisites: hybrid-crypto, network-security-pqc, vpn-ssh-pqc (recommended). This module teaches how to design and execute testing strategies for post-quantum cryptography deployments. It covers the full PQC testing lifecycle from initial crypto discovery through production monitoring — distinct from protocol migration modules which cover _what_ to migrate. ---',
    keyConcepts:
      "TVLA — Test Vector Leakage Assessment; Welch's t-test on power traces; |t| > 4.5 = leakage. CBOM — Cryptography Bill of Materials; cryptoProperties entered the spec at CycloneDX 1.6 and 1.7 is current (our own CBOM is specVersion 1.7); generated by CBOMkit. RFC 9794 — Hybrid PQC design rules; both components must complete; no silent downgrade. Passive Discovery — SPAN/TAP probe; no packet injection; production-safe. Active Scanning — Connection-initiating probes; detects full capability; requires coordination.",
  },
}
