// SPDX-License-Identifier: GPL-3.0-only
/**
 * Structured content for the PQCTestingValidation module.
 */
import type { ModuleContent } from '@/types/ModuleContentTypes'
import { getAlgorithm } from '@/data/algorithmProperties'
import { getStandard } from '@/data/standardsRegistry'

export const content: ModuleContent = {
  // Corrected 2026-08-22: this read 'p-q-c-testing-validation', an id used
  // NOWHERE else — manifest.ts, the /learn route, the simulation trees and every
  // pre-existing library module_ids value all say 'pqc-testing-validation'. It was
  // invisible until writeback_module_ids.py trusted this field and wrote the bad id
  // onto four library rows, which the hub's C4 check rejected immediately. Tooling
  // keyed on content.ts (learn_snapshot.py, and through it the spot-check rotation)
  // was addressing this module by a name the catalogue does not know.
  moduleId: 'pqc-testing-validation',
  version: '1.0.0',
  lastReviewed: '2026-08-22',

  standards: [
    getStandard('FIPS 186-5'),
    getStandard('FIPS 203'),
    getStandard('FIPS 204'),
    getStandard('RFC 9794'),
  ],

  algorithms: [
    getAlgorithm('ECDSA P-384'),
    getAlgorithm('Ed25519'),
    getAlgorithm('ML-DSA-65'),
    getAlgorithm('ML-KEM-768'),
    getAlgorithm('RSA-2048'),
    getAlgorithm('RSA-4096'),
    getAlgorithm('X25519'),
  ],

  deadlines: [
    // No regulatory deadlines detected — add manually if needed
  ],

  narratives: {
    overview:
      'Module ID: pqc-testing-validation. Track: Protocols. Duration: 120 minutes. Difficulty: Advanced. Prerequisites: hybrid-crypto, network-security-pqc, vpn-ssh-pqc (recommended). This module teaches how to design and execute testing strategies for post-quantum cryptography deployments. It covers the full PQC testing lifecycle from initial crypto discovery through production monitoring — distinct from protocol migration modules which cover _what_ to migrate. ---',
    keyConcepts:
      "TVLA — Test Vector Leakage Assessment; Welch's t-test on power traces; |t| > 4.5 = leakage. CBOM — Cryptography Bill of Materials; cryptoProperties entered the spec at CycloneDX 1.6 and 1.7 is current (our own CBOM is specVersion 1.7); generated by CBOMkit. RFC 9794 — Hybrid PQC design rules; both components must complete; no silent downgrade. Passive Discovery — SPAN/TAP probe; no packet injection; production-safe. Active Scanning — Connection-initiating probes; detects full capability; requires coordination.",
  },
}
