// SPDX-License-Identifier: GPL-3.0-only
//
// suiteCodegen — generated Python for the Build tab's ACVP and Conformance
// suites (design handoff design_handoff_kmip_pkcs11_playground §3.6).
//
// Honesty contract: these scripts run IN THIS BROWSER TAB through two
// Pyodide JS modules (`acvp_native`, `pkcs11_conformance`) that call the
// same TypeScript runners the Builder view uses — real C_* calls against
// the WASM engine, identical rows. They are not portable to the separately
// distributed dev sandbox (that needs the Standard suite's `p11` scripts),
// and the header says so rather than pretending otherwise. Where a KAT is
// also expressible as a portable `p11` script, the header points at the
// Standard-suite template that carries it.
import { CATEGORIES, type CategoryId } from '@/components/Playground/hsm/acvp/useAcvpSuite'
import {
  TIER_A_CASES,
  type ConformanceSelection,
} from '@/components/Playground/hsm/conformance/usePkcs11Conformance'

const ENGINE_NAME: Record<string, string> = {
  cpp: 'C++',
  rust: 'Rust',
  dual: 'C++ + Rust (dual parity)',
  software: 'software',
}

/** Standard-suite templates that express the same KAT as portable p11. */
const PORTABLE_KATS: Partial<Record<CategoryId, string[]>> = {
  ml_kem: ['ACVP ML-KEM-768 KAT'],
  ml_dsa: ['ACVP ML-DSA-44 KAT'],
  hashing_mac: ['ACVP SHA-256 KAT', 'ACVP SHA3-256 KAT'],
}

const pyList = (items: string[]) => `[${items.map((s) => JSON.stringify(s)).join(', ')}]`

export function emitAcvpSuite(selected: Set<CategoryId>, engineMode: string): string {
  const cats = CATEGORIES.filter((c) => selected.has(c.id))
  const portable = cats.flatMap((c) =>
    (PORTABLE_KATS[c.id] ?? []).map((t) => `#   ${c.label}: "${t}"`)
  )
  return `"""ACVP known-answer tests — generated by the pqctoday Build tab.

Engine: softhsmv3 · ${ENGINE_NAME[engineMode] ?? engineMode}, compiled to WebAssembly, running in
this browser tab. Every selected category replays NIST ACVP-Server reference
vectors (or a self-consistency oracle where no published KAT exists — the
row's evidence tier says which) through the same runner the Builder uses,
via the in-browser \`acvp_native\` bridge. Skips are visible rows, never
dropped: a mechanism the engine doesn't advertise reports "skip".

This driver is browser-only (it needs the bridge). The KATs below are also
available as portable p11 v3.2 scripts in the Standard suite's "Start from"
list, runnable unchanged in the pqctoday dev sandbox:
${portable.length ? portable.join('\n') : '#   (none of the selected categories has a portable p11 template yet)'}
"""
import json
import acvp_native as acvp   # in-browser bridge → hsm/acvp/useAcvpSuite.ts

CATEGORIES = ${pyList(cats.map((c) => c.id))}
${cats.map((c) => `#   ${c.id.padEnd(12)} ${c.label} · ${c.groups} test groups`).join('\n')}

rows = json.loads(await acvp.run_categories(CATEGORIES))
for r in rows:
    tier = r.get("evidenceTier") or "—"
    print(f"[{r['status'].upper():>5}] {r['category']:<12} {r['algorithm']:<32} {r['testCase']}  ({tier})")

passed = sum(1 for r in rows if r["status"] == "pass")
failed = sum(1 for r in rows if r["status"] == "fail")
skipped = sum(1 for r in rows if r["status"] == "skip")
print(f"\\nResult: {passed} pass, {failed} fail, {skipped} skip (of {len(rows)} rows)")
print("FAILED" if failed else "OK")
`
}

export function emitConformanceSuite(sel: ConformanceSelection, engineMode: string): string {
  const cases = TIER_A_CASES.filter((c) => sel.tierA.has(c.id))
  return `"""PKCS#11 v3.2 Profiles conformance — generated by the pqctoday Build tab.

Engine: softhsmv3 · ${ENGINE_NAME[engineMode] ?? engineMode}, compiled to WebAssembly, running in
this browser tab. Tier A replays OASIS's own published XML test cases
verbatim; Tier B condition probes and Mechanism Coverage are generated probe
sequences. Profile claims come from the engine's own CKO_PROFILE objects —
never assumed — so an unclaimed profile reports "not-claimed", not "pass".

Executes through the in-browser \`pkcs11_conformance\` bridge to the same
TypeScript runner the Builder uses (src/wasm/pkcs11ConformanceRunner/*):
real C_* calls against the raw WASM ABI, identical rows. Browser-only.
"""
import json
import pkcs11_conformance as conf   # in-browser bridge → hsm/conformance/usePkcs11Conformance.ts

TIER_A = ${pyList(cases.map((c) => c.id))}
${cases.map((c) => `#   ${c.id.padEnd(12)} ${c.citation}`).join('\n') || '#   (no Tier A case selected)'}
RUN_TIER_B_PROBES = ${sel.tierB ? 'True' : 'False'}      # per claimed profile: up to 17/6/8/5/6 checks
RUN_MECHANISM_COVERAGE = ${sel.coverage ? 'True' : 'False'}   # CKA_SEED determinism, §6.67.4 / §6.68.4 / §6.69.2

claims = json.loads(conf.claims())          # engine → claimed profiles (after the last run)
rows = json.loads(await conf.run_cases(TIER_A, RUN_TIER_B_PROBES, RUN_MECHANISM_COVERAGE))
for r in rows:
    print(f"[{r['status'].upper():>11}] {r['engine']:<5} {('Tier ' + r['tier']) if r['tier'] != 'Coverage' else 'Coverage':<9} {r['name']} — {r['citation']}")

passed = sum(1 for r in rows if r["status"] == "pass")
failed = sum(1 for r in rows if r["status"] == "fail")
not_claimed = sum(1 for r in rows if r["status"] == "not-claimed")
print(f"\\nResult: {passed} pass, {failed} fail, {not_claimed} not-claimed (of {len(rows)} rows)")
print("FAILED" if failed else "OK")
`
}
