// SPDX-License-Identifier: GPL-3.0-only
/**
 * Board Pack ZIP builder (P15-P1-03).
 *
 * Bundles the assessment result + a curated profile snapshot into a
 * downloadable ZIP an executive can drop into a board pack without
 * touching the in-app report. Produces:
 *
 *   board-pack/
 *     README.md                 — what's inside, how to use
 *     executive-summary.md      — riskScore + level + narrative + top-3 actions
 *     key-findings.md           — full key findings list
 *     recommended-actions.md    — every recommendation by priority + category
 *     compliance-deadlines.csv  — per-framework deadlines + PQC requirement
 *     profile.json              — assessment inputs (machine-readable replay)
 *
 * Pure data builder — no React, no DOM. Returns a Blob ready for download.
 */
import JSZip from 'jszip'
import type { AssessmentResult } from '@/hooks/assessmentTypes'

export interface BoardPackProfile {
  industry: string
  country: string
  region?: string
  generatedAt: string
  persona?: string | null
}

export interface BuildBoardPackInput {
  result: AssessmentResult
  profile: BoardPackProfile
  /** Optional UTM-style tag echoed into the README footer. */
  appVersion?: string
}

const CATEGORY_LABEL: Record<string, string> = {
  immediate: 'Immediate · do now',
  'short-term': 'Short-term · this quarter',
  'long-term': 'Long-term · plan it',
}

function escapeCsv(value: string): string {
  if (/[",\n]/.test(value)) return `"${value.replace(/"/g, '""')}"`
  return value
}

function buildReadme(profile: BoardPackProfile, appVersion?: string): string {
  const parts = [
    '# PQC Board Pack',
    '',
    `Generated ${profile.generatedAt} from the PQC Today Risk Assessment.`,
    '',
    "## What's inside",
    '',
    '- `executive-summary.md` — risk score, level, and top-3 actions in one page.',
    '- `key-findings.md` — the 3-5 most material insights from the assessment.',
    '- `recommended-actions.md` — every recommendation grouped by category and priority.',
    '- `compliance-deadlines.csv` — applicable frameworks, deadlines, and PQC-required flag.',
    '- `profile.json` — the answers that produced this report, in machine-readable form.',
    '',
    '## How to use',
    '',
    'Drop these files straight into a board pack. The CSV opens in Excel; the markdown files render in any board-pack tool (Notion, Docs, Confluence). The JSON replays the report — paste it back into the app via `?share=` to reproduce.',
    '',
    '## Profile',
    '',
    `- **Industry:** ${profile.industry || 'unspecified'}`,
    `- **Country:** ${profile.country || 'unspecified'}`,
    profile.region ? `- **Region:** ${profile.region}` : '',
    profile.persona ? `- **Active persona:** ${profile.persona}` : '',
    '',
  ].filter(Boolean)
  if (appVersion) {
    parts.push('---', '', `Generated by pqctoday.org · ${appVersion}`)
  }
  return parts.join('\n')
}

function buildExecutiveSummary(result: AssessmentResult, profile: BoardPackProfile): string {
  const top3 = result.recommendedActions.slice(0, 3)
  const lines = [
    '# Executive Summary',
    '',
    `**Risk score:** ${result.riskScore} / 100 (${result.riskLevel})`,
    `**Generated:** ${profile.generatedAt}`,
    profile.industry ? `**Industry:** ${profile.industry}` : '',
    profile.country ? `**Country:** ${profile.country}` : '',
    '',
    '## Narrative',
    '',
    (result.personaNarrative || result.executiveSummary || result.narrative || '').trim(),
    '',
    '## Top 3 priorities',
    '',
  ].filter(Boolean)
  for (const a of top3) {
    lines.push(`### ${a.priority}. ${a.action}`)
    lines.push('')
    lines.push(
      `*${CATEGORY_LABEL[a.category] ?? a.category}${a.effort ? ` · effort: ${a.effort}` : ''}*`
    )
    lines.push('')
  }
  return lines.join('\n')
}

function buildKeyFindings(result: AssessmentResult): string {
  const findings = result.keyFindings ?? []
  if (findings.length === 0) {
    return '# Key Findings\n\n_No findings recorded for this assessment._\n'
  }
  const lines = ['# Key Findings', '']
  for (const f of findings) lines.push(`- ${f}`)
  lines.push('')
  return lines.join('\n')
}

function buildRecommendedActions(result: AssessmentResult): string {
  const byCategory: Record<string, typeof result.recommendedActions> = {
    immediate: [],
    'short-term': [],
    'long-term': [],
  }
  for (const a of result.recommendedActions) {
    ;(byCategory[a.category] ?? (byCategory[a.category] = [])).push(a)
  }
  const lines = ['# Recommended Actions', '']
  for (const cat of ['immediate', 'short-term', 'long-term'] as const) {
    // eslint-disable-next-line security/detect-object-injection
    const items = byCategory[cat]
    if (!items || items.length === 0) continue
    lines.push(`## ${CATEGORY_LABEL[cat]}`, '')
    for (const a of items.sort((x, y) => x.priority - y.priority)) {
      lines.push(`- **${a.action}**${a.effort ? ` _(effort: ${a.effort})_` : ''}`)
      if (a.relatedModule) {
        lines.push(`  - Related learn module: \`${a.relatedModule}\``)
      }
    }
    lines.push('')
  }
  return lines.join('\n')
}

function buildComplianceCsv(result: AssessmentResult): string {
  const header = ['framework', 'requires_pqc', 'deadline', 'notes'].join(',')
  const rows = result.complianceImpacts.map((c) =>
    [
      escapeCsv(c.framework),
      c.requiresPQC === null ? 'unknown' : c.requiresPQC ? 'yes' : 'no',
      escapeCsv(c.deadline),
      escapeCsv(c.notes),
    ].join(',')
  )
  return [header, ...rows].join('\n') + '\n'
}

function buildProfileJson(result: AssessmentResult, profile: BoardPackProfile): string {
  return JSON.stringify(
    {
      profile,
      score: {
        risk: result.riskScore,
        riskLevel: result.riskLevel,
        preBoost: result.preBoostScore,
        boosts: result.boosts ?? [],
      },
      assessmentProfile: result.assessmentProfile ?? null,
    },
    null,
    2
  )
}

/**
 * Build the Board Pack as a single Blob.
 */
export async function buildBoardPackBlob(input: BuildBoardPackInput): Promise<Blob> {
  const { result, profile, appVersion } = input
  const zip = new JSZip()
  const folder = zip.folder('board-pack')!
  folder.file('README.md', buildReadme(profile, appVersion))
  folder.file('executive-summary.md', buildExecutiveSummary(result, profile))
  folder.file('key-findings.md', buildKeyFindings(result))
  folder.file('recommended-actions.md', buildRecommendedActions(result))
  folder.file('compliance-deadlines.csv', buildComplianceCsv(result))
  folder.file('profile.json', buildProfileJson(result, profile))
  return zip.generateAsync({ type: 'blob' })
}

/**
 * Build the Board Pack and trigger a browser download. No-ops in non-browser
 * environments (server / test) — caller is expected to gate via `if (typeof
 * window !== 'undefined')`.
 */
export async function downloadBoardPack(input: BuildBoardPackInput): Promise<void> {
  const blob = await buildBoardPackBlob(input)
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `pqc-board-pack-${profileSlug(input.profile)}.zip`
  a.click()
  URL.revokeObjectURL(url)
}

function profileSlug(profile: BoardPackProfile): string {
  const date = profile.generatedAt.slice(0, 10) || new Date().toISOString().slice(0, 10)
  const industry = (profile.industry || 'unspec').toLowerCase().replace(/[^a-z0-9]+/g, '-')
  return `${date}-${industry}`
}
