// SPDX-License-Identifier: GPL-3.0-only
import React, { useState, useCallback } from 'react'
import { GateReason } from '@/components/shared/GateReason'
import {
  Workflow,
  KeyRound,
  Play,
  RotateCw,
  Cpu,
  ArrowRight,
  Database,
  Hash,
  AlertTriangle,
  FlaskConical,
  CheckCircle,
  XCircle,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { CopyableOutput } from '@/components/ui/CopyableOutput'
import { PlaygroundNextStep } from '@/components/Playground/components/PlaygroundNextStep'
import { getRandomBytes } from '@/utils/webCrypto'
import { formatHex } from '../utils/outputFormatters'
import {
  hmacDrbgGenerate,
  hmacDrbgInstantiate,
  hmacDrbgReseed,
  runHmacDrbgKatSuite,
  bytesToHex,
  hexToBytes,
  type HmacDrbgKatCase,
  type HmacDrbgKatOutcome,
} from '../utils/hmacDrbg'

// SP 800-90A Rev. 1 §10.1 Table 2: HMAC_DRBG reseed_interval = 2^48.
// For this educational demo we use a much smaller interval so the limit is
// reachable. The check is the one in §10.1.2.5 step 1: generate refuses once
// reseed_counter > reseed_interval.
const DEMO_RESEED_INTERVAL = 10

const INITIAL_K = new Uint8Array(32).fill(0x00)
const INITIAL_V = new Uint8Array(32).fill(0x01)

interface KatRun {
  outcomes: HmacDrbgKatOutcome[]
  sabotage: { flippedCaseId: string; matched: boolean }
}

/** Load the pinned NIST vectors on demand (kept out of the step's main chunk). */
async function loadKatCases(): Promise<HmacDrbgKatCase[]> {
  const mod = await import('../utils/hmacDrbgSha256.kat.json')
  return mod.default.cases as HmacDrbgKatCase[]
}

/**
 * Run every pinned vector, then re-run one with a single bit flipped in its
 * entropy input — the flipped run must NOT match, or the check proves nothing.
 */
async function runKatWithSabotage(): Promise<KatRun> {
  const cases = await loadKatCases()
  const outcomes = await runHmacDrbgKatSuite(cases)
  const target = cases.find((c) => c.id === 'acvp-tg14-tc196') ?? cases[0]
  const flipped: HmacDrbgKatCase = JSON.parse(JSON.stringify(target))
  const e = hexToBytes(flipped.entropyInput)
  e[0] ^= 0x01
  flipped.entropyInput = bytesToHex(e)
  const [sab] = await runHmacDrbgKatSuite([flipped])
  return { outcomes, sabotage: { flippedCaseId: target.id, matched: sab.passed } }
}

export const DrbgArchitectureDemo: React.FC = () => {
  // DRBG Internal State
  const [K, setK] = useState<Uint8Array>(INITIAL_K)
  const [V, setV] = useState<Uint8Array>(INITIAL_V)
  const [reseedCounter, setReseedCounter] = useState(0)
  const [instantiated, setInstantiated] = useState(false)
  const [isProcessing, setIsProcessing] = useState(false)

  // Inputs
  const [entropyInput, setEntropyInput] = useState<Uint8Array>(() => getRandomBytes(32))
  const [nonce, setNonce] = useState<Uint8Array>(() => getRandomBytes(16))
  // SP 800-90A §8.6.7: nonce should be obtained from an external source.
  // This field lets learners supply a custom hex nonce; blank = use auto-generated bytes.
  const [nonceHex, setNonceHex] = useState('')
  const [persoString, setPersoString] = useState('PQC-Timeline-App')

  // §10.1.2.5 step 1: a reseed is required once reseed_counter > reseed_interval.
  const isReseedRequired = instantiated && reseedCounter > DEMO_RESEED_INTERVAL

  const [genBytesCount, setGenBytesCount] = useState(32)
  const [addlInputStr, setAddlInputStr] = useState('')

  // Outputs
  const [lastGenerated, setLastGenerated] = useState<Uint8Array | null>(null)
  const [historyLog, setHistoryLog] = useState<string[]>([])

  // Known-answer check
  const [katRun, setKatRun] = useState<KatRun | null>(null)
  const [katRunning, setKatRunning] = useState(false)
  const [katError, setKatError] = useState<string | null>(null)

  const logAction = (action: string) => {
    setHistoryLog((prev) => [action, ...prev].slice(0, 5))
  }

  // Instantiate — SP 800-90A Rev. 1 §10.1.2.3
  const handleInstantiate = useCallback(async () => {
    setIsProcessing(true)
    try {
      // Resolve nonce: prefer user-supplied hex; fall back to auto-generated bytes.
      let resolvedNonce = nonce
      if (nonceHex.trim()) {
        const cleaned = nonceHex.replace(/\s/g, '')
        if (/^[0-9a-fA-F]+$/.test(cleaned) && cleaned.length % 2 === 0) {
          resolvedNonce = hexToBytes(cleaned)
        }
      }

      const persoBytes = new TextEncoder().encode(persoString)
      const state = await hmacDrbgInstantiate(entropyInput, resolvedNonce, persoBytes)

      setK(state.K)
      setV(state.V)
      setReseedCounter(state.reseedCounter)
      setInstantiated(true)
      logAction('Instantiated — reseed_counter set to 1 (§10.1.2.3 step 5)')
    } finally {
      setIsProcessing(false)
    }
  }, [entropyInput, nonce, nonceHex, persoString])

  // Generate — SP 800-90A Rev. 1 §10.1.2.5
  const handleGenerate = useCallback(async () => {
    if (!instantiated) return
    setIsProcessing(true)
    try {
      const addlBytes = addlInputStr ? new TextEncoder().encode(addlInputStr) : new Uint8Array(0)
      const res = await hmacDrbgGenerate(
        { K, V, reseedCounter },
        genBytesCount,
        addlBytes,
        DEMO_RESEED_INTERVAL
      )
      if (res.status === 'RESEED_REQUIRED') {
        logAction('Generate refused — reseed required (§10.1.2.5 step 1)')
        return
      }
      setLastGenerated(res.returnedBytes)
      setK(res.state.K)
      setV(res.state.V)
      setReseedCounter(res.state.reseedCounter)
      logAction(`Generated ${genBytesCount} bytes — reseed_counter now ${res.state.reseedCounter}.`)
    } finally {
      setIsProcessing(false)
    }
  }, [instantiated, K, V, reseedCounter, addlInputStr, genBytesCount])

  // Reseed — SP 800-90A Rev. 1 §10.1.2.4
  const handleReseed = useCallback(async () => {
    if (!instantiated) return
    setIsProcessing(true)
    try {
      const newEntropy = getRandomBytes(32) as Uint8Array
      setEntropyInput(newEntropy) // show that new entropy input was obtained

      const addlBytes = addlInputStr ? new TextEncoder().encode(addlInputStr) : new Uint8Array(0)
      const state = await hmacDrbgReseed({ K, V, reseedCounter }, newEntropy, addlBytes)

      setK(state.K)
      setV(state.V)
      setReseedCounter(state.reseedCounter)
      logAction('Reseeded — reseed_counter reset to 1 (§10.1.2.4 step 3)')
    } finally {
      setIsProcessing(false)
    }
  }, [instantiated, addlInputStr, K, V, reseedCounter])

  const handleRunKat = useCallback(async () => {
    setKatRunning(true)
    setKatError(null)
    try {
      setKatRun(await runKatWithSabotage())
    } catch (e) {
      setKatError(e instanceof Error ? e.message : String(e))
      setKatRun(null)
    } finally {
      setKatRunning(false)
    }
  }, [])

  const handleReset = () => {
    setK(INITIAL_K)
    setV(INITIAL_V)
    setReseedCounter(0)
    setInstantiated(false)
    setLastGenerated(null)
    setHistoryLog([])
    setEntropyInput(getRandomBytes(32) as Uint8Array)
    setNonce(getRandomBytes(16) as Uint8Array)
  }

  return (
    <div className="space-y-6">
      <div className="glass-panel p-4 space-y-2">
        <div className="flex items-center gap-2 mb-2">
          <Workflow className="text-primary" size={20} />
          <h2 className="text-lg font-bold text-foreground">SP 800-90A HMAC_DRBG</h2>
        </div>
        <p className="text-sm text-foreground leading-relaxed">
          Explore the internal lifecycle of a Deterministic Random Bit Generator. This is HMAC_DRBG
          with SHA-256 as specified in SP 800-90A Rev. 1 &sect;10.1.2: the working state is the Key
          and V values plus a reseed counter, and every step updates them with HMAC-SHA-256.
        </p>
        <p className="text-xs text-muted-foreground leading-relaxed">
          The steps shown here are the HMAC_DRBG algorithms for <strong>Instantiate</strong>{' '}
          (&sect;10.1.2.3), <strong>Generate</strong> (&sect;10.1.2.5) and <strong>Reseed</strong>{' '}
          (&sect;10.1.2.4).
        </p>
        <p className="text-xs text-muted-foreground leading-relaxed">
          A DRBG is not an entropy source: its output is only as unpredictable as the entropy input
          it was seeded with. Here the entropy input comes from the browser&rsquo;s{' '}
          <code>crypto.getRandomValues()</code> as a stand-in. SP 800-90C expects seed material for
          a DRBG to come from entropy sources validated against SP 800-90B.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Left Column: Controls */}
        <div className="space-y-4">
          {/* Phase 1: Instantiate */}
          <div
            className={`glass-panel p-4 space-y-4 border ${!instantiated ? 'border-primary' : 'border-border/50 opacity-60'}`}
          >
            <h3 className="text-sm font-semibold flex items-center gap-2">
              <span className="flex items-center justify-center bg-primary text-primary-foreground rounded-full w-5 h-5 text-xs">
                1
              </span>
              Instantiate Phase
            </h3>

            <div className="space-y-3">
              <div>
                <span className="text-[10px] uppercase font-bold text-muted-foreground flex justify-between">
                  <span>Entropy Input (32 bytes)</span>
                  <Button
                    variant="ghost"
                    onClick={() => setEntropyInput(getRandomBytes(32))}
                    disabled={instantiated}
                    className="text-primary hover:underline"
                  >
                    re-roll
                  </Button>
                </span>
                <div className="font-mono text-[10px] bg-muted/40 p-2 rounded break-all mt-1">
                  {formatHex(entropyInput, 0)}
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                <div>
                  <span className="text-[10px] uppercase font-bold text-muted-foreground flex justify-between">
                    <span>Nonce — auto (16 bytes)</span>
                  </span>
                  <div className="font-mono text-[10px] bg-muted/40 p-2 rounded break-all mt-1 min-h-[32px] flex items-center overflow-hidden">
                    {formatHex(nonce, 0)}
                  </div>
                  <label
                    htmlFor="drbg-nonce"
                    className="text-[10px] uppercase font-bold text-muted-foreground mt-2 block"
                    title="SP 800-90A §8.6.7: nonce should be obtained from an external source"
                  >
                    Custom nonce (hex, optional)
                  </label>
                  <Input
                    id="drbg-nonce"
                    placeholder="e.g. 0011aabb… (§8.6.7)"
                    value={nonceHex}
                    onChange={(e) => setNonceHex(e.target.value)}
                    disabled={instantiated}
                    className="h-[32px] text-xs mt-1 font-mono"
                  />
                </div>
                <div>
                  <label
                    htmlFor="drbg-perso"
                    className="text-[10px] uppercase font-bold text-muted-foreground"
                  >
                    Personalization (String)
                  </label>
                  <Input
                    id="drbg-perso"
                    value={persoString}
                    onChange={(e) => setPersoString(e.target.value)}
                    disabled={instantiated}
                    className="h-[32px] text-xs mt-1"
                  />
                </div>
              </div>

              <Button
                variant={instantiated ? 'outline' : 'gradient'}
                className="w-full"
                onClick={handleInstantiate}
                disabled={instantiated || isProcessing}
              >
                <Cpu size={16} className="mr-2" />
                Instantiate HMAC_DRBG
              </Button>
            </div>
          </div>

          {/* Phase 2: Generate & Reseed */}
          <div
            className={`glass-panel p-4 space-y-4 border ${instantiated ? 'border-success' : 'border-dashed border-border'}`}
          >
            <h3 className="text-sm font-semibold flex items-center gap-2">
              <span className="flex items-center justify-center bg-success text-success-foreground rounded-full w-5 h-5 text-xs">
                2
              </span>
              Generate & Reseed
            </h3>

            <div className="space-y-3">
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-2">
                <div className="col-span-1">
                  <label
                    htmlFor="drbg-bytes"
                    className="text-[10px] uppercase font-bold text-muted-foreground"
                  >
                    Bytes
                  </label>
                  <Input
                    id="drbg-bytes"
                    type="number"
                    value={genBytesCount}
                    onChange={(e) =>
                      setGenBytesCount(Math.max(1, Math.min(2048, Number(e.target.value))))
                    }
                    disabled={!instantiated || isProcessing}
                    className="h-[32px] text-xs mt-1"
                  />
                </div>
                <div className="col-span-2">
                  <label
                    htmlFor="drbg-addl"
                    className="text-[10px] uppercase font-bold text-muted-foreground"
                    title="Mixed into Update() alongside the entropy/key material on Generate or Reseed (SP 800-90A §8.6.7) — e.g. a timestamp, request counter, or caller-supplied nonce. It doesn't need to be secret or unpredictable; its purpose is domain separation between calls, not additional entropy."
                  >
                    Additional Input (Opt.)
                  </label>
                  <Input
                    id="drbg-addl"
                    placeholder="E.g., a timestamp or request counter"
                    value={addlInputStr}
                    onChange={(e) => setAddlInputStr(e.target.value)}
                    disabled={!instantiated || isProcessing}
                    className="h-[32px] text-xs mt-1"
                  />
                </div>
              </div>

              {isReseedRequired && (
                <div className="flex items-start gap-2 rounded-md bg-status-warning/10 border border-status-warning/30 p-2">
                  <AlertTriangle size={14} className="text-status-warning mt-0.5 shrink-0" />
                  <p className="text-[10px] text-status-warning leading-relaxed">
                    <strong>Reseed required.</strong> reseed_counter ({reseedCounter}) is greater
                    than this demo&rsquo;s reseed_interval of {DEMO_RESEED_INTERVAL}, so Generate
                    refuses (&sect;10.1.2.5 step 1). SP 800-90A Rev. 1 Table 2 sets the HMAC_DRBG
                    maximum at 2<sup>48</sup> requests between reseeds. Click Reseed to continue.
                  </p>
                </div>
              )}

              <GateReason when={!instantiated} className="mt-0 mb-2">
                Instantiate the DRBG first; Generate and Reseed unlock once it has a state.
              </GateReason>
              <GateReason when={instantiated && isReseedRequired} className="mt-0 mb-2">
                The reseed interval is reached: press Reseed before generating again.
              </GateReason>
              <div className="flex gap-2">
                <Button
                  variant="default"
                  className="w-full"
                  onClick={handleGenerate}
                  disabled={!instantiated || isProcessing || isReseedRequired}
                >
                  <Play size={16} className="mr-2" /> Generate
                </Button>
                <Button
                  variant="outline"
                  className="w-full"
                  onClick={handleReseed}
                  disabled={!instantiated || isProcessing}
                  title="Reseeds using the current Additional Input and fresh entropy"
                >
                  <RotateCw size={16} className="mr-2" /> Reseed
                </Button>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column: State Visualization */}
        <div className="space-y-4">
          <div className="glass-panel p-4 space-y-4 bg-muted/10 h-full flex flex-col relative">
            <div className="flex justify-between items-center">
              <h3 className="text-sm font-semibold flex items-center gap-2 text-foreground">
                <Database size={16} className="text-primary" />
                Internal State Tracker
              </h3>
              <div
                className="text-xs bg-muted/50 px-2 py-1 rounded font-medium text-muted-foreground cursor-help"
                title="reseed_counter: 1 after instantiate (§10.1.2.3) or reseed (§10.1.2.4); +1 per generate. Generate refuses once it exceeds reseed_interval (§10.1.2.5 step 1). SP 800-90A Rev. 1 Table 2 maximum: 2^48."
              >
                reseed_counter:{' '}
                <span
                  className={isReseedRequired ? 'text-status-warning font-bold' : 'text-foreground'}
                >
                  {reseedCounter}
                </span>
                {instantiated && (
                  <span className="text-muted-foreground">
                    {' '}
                    (limit &gt; {DEMO_RESEED_INTERVAL})
                  </span>
                )}
              </div>
            </div>

            {!instantiated && (
              <div className="absolute inset-0 flex items-center justify-center bg-background/50 backdrop-blur-[1px] z-10 rounded-xl">
                <span className="text-sm font-medium text-muted-foreground bg-background px-4 py-2 rounded-lg shadow-sm">
                  Instantiate DRBG to start tracking state
                </span>
              </div>
            )}

            <div className="space-y-4 flex-grow">
              {/* Key K */}
              <div className="space-y-1">
                <span className="text-[10px] uppercase font-bold text-primary flex items-center gap-1">
                  <KeyRound size={12} /> Working Key (K)
                </span>
                <div className="font-mono text-[11px] bg-primary/10 text-primary rounded p-3 break-all border border-primary/20">
                  {formatHex(K, 0)}
                </div>
              </div>

              {/* Value V */}
              <div className="space-y-1">
                <span className="text-[10px] uppercase font-bold text-success flex items-center gap-1">
                  <Hash size={12} /> State Value (V)
                </span>
                <div className="font-mono text-[11px] bg-success/10 text-success rounded p-3 break-all border border-success/20">
                  {formatHex(V, 0)}
                </div>
              </div>

              {lastGenerated && (
                <div className="space-y-1 mt-6 border-t border-border/50 pt-4">
                  <span className="text-[10px] uppercase font-bold text-foreground flex items-center gap-1">
                    <ArrowRight size={12} /> Last Generated Output ({lastGenerated.length} bytes)
                  </span>
                  <CopyableOutput
                    value={formatHex(lastGenerated)}
                    rows={3}
                    downloadFilename="drbg-output.txt"
                    className="text-[11px]"
                  />
                </div>
              )}
            </div>

            {historyLog.length > 0 && (
              <div className="mt-4 border-t border-border/50 pt-3">
                <span className="text-[10px] uppercase font-bold text-muted-foreground mb-2 block">
                  Action Log
                </span>
                <div className="space-y-1">
                  {historyLog.map((log, i) => (
                    <div
                      key={i}
                      className={`text-[10px] ${i === 0 ? 'text-foreground font-medium' : 'text-muted-foreground opacity-60'}`}
                    >
                      • {log}
                    </div>
                  ))}
                </div>
              </div>
            )}

            {instantiated && (
              <Button
                variant="ghost"
                size="sm"
                onClick={handleReset}
                className="w-full mt-4 border border-border"
              >
                Reset DRBG
              </Button>
            )}
          </div>
        </div>
      </div>
      <div className="glass-panel p-4 space-y-3">
        <div className="flex items-center gap-2">
          <FlaskConical size={16} className="text-primary" />
          <h3 className="text-sm font-semibold text-foreground">
            Known-answer check (NIST HMAC_DRBG vectors)
          </h3>
        </div>
        <p className="text-xs text-muted-foreground leading-relaxed">
          Runs the same HMAC_DRBG code used above on 16 pinned SHA-256 vectors — 4 from NIST&rsquo;s
          ACVP-Server <code>hmacDRBG-1.0</code> sample set and 12 from the NIST CAVP{' '}
          <code>HMAC_DRBG.rsp</code> files. They cover prediction resistance on and off, reseed, and
          empty or non-empty personalization strings and additional input. Each output must equal
          the published answer byte for byte. The check then flips one bit of one vector&rsquo;s
          entropy input; that run must <strong>not</strong> match.
        </p>
        <p className="text-xs text-muted-foreground leading-relaxed">
          <strong>What a pass shows:</strong> this browser code computes the SP 800-90A Rev. 1
          HMAC_DRBG mechanism correctly for these inputs. <strong>What it does not show:</strong> it
          is not a CAVP/ACVP algorithm validation, it is not an entropy-source test, and it says
          nothing about the quality of any entropy input.
        </p>
        <Button variant="outline" onClick={handleRunKat} disabled={katRunning}>
          <FlaskConical size={16} className="mr-2" />
          {katRunning ? 'Running…' : 'Run known-answer check'}
        </Button>
        {katError && (
          <p className="text-xs text-status-error">Could not run the check: {katError}</p>
        )}
        {katRun && (
          <div className="space-y-2" data-testid="drbg-kat-result">
            {(() => {
              const passed = katRun.outcomes.filter((o) => o.passed).length
              const total = katRun.outcomes.length
              const allPass = passed === total && !katRun.sabotage.matched
              return (
                <div
                  className={`flex items-start gap-2 rounded-md border p-2 ${
                    allPass
                      ? 'border-status-success/30 bg-status-success/10'
                      : 'border-status-error/30 bg-status-error/10'
                  }`}
                >
                  {allPass ? (
                    <CheckCircle size={14} className="text-status-success mt-0.5 shrink-0" />
                  ) : (
                    <XCircle size={14} className="text-status-error mt-0.5 shrink-0" />
                  )}
                  <p className="text-xs text-foreground leading-relaxed">
                    {passed}/{total} vectors matched byte for byte.{' '}
                    {katRun.sabotage.matched
                      ? `Sabotage check FAILED: flipping one entropy-input bit in ${katRun.sabotage.flippedCaseId} still matched.`
                      : `Sabotage check passed: one flipped entropy-input bit in ${katRun.sabotage.flippedCaseId} no longer matches.`}
                  </p>
                </div>
              )
            })()}
            <ul className="grid grid-cols-1 sm:grid-cols-2 gap-1">
              {katRun.outcomes.map((o) => (
                <li key={o.id} className="flex items-center gap-1.5 text-[11px] font-mono">
                  {o.passed ? (
                    <CheckCircle size={12} className="text-status-success shrink-0" />
                  ) : (
                    <XCircle size={12} className="text-status-error shrink-0" />
                  )}
                  <span className="text-foreground break-all">{o.id}</span>
                </li>
              ))}
            </ul>
          </div>
        )}
      </div>

      <PlaygroundNextStep
        toolId="source-combining"
        name="Source Combining"
        description="See where a DRBG's entropy input comes from: health-test raw source samples, condition them, and state the assumptions a combined construction depends on."
      />
    </div>
  )
}
