// SPDX-License-Identifier: GPL-3.0-only
//
// Icon registry for the Industry Landscape tab. `use_case_icon` values in
// industry_landscape_*.csv must be keys of USE_CASE_ICONS (driftguard-tested)
// so a typo'd icon name fails CI instead of silently rendering nothing.

import {
  Activity,
  Antenna,
  Archive,
  Award,
  Banknote,
  Barcode,
  Bitcoin,
  Bluetooth,
  BookOpen,
  Building2,
  Cable,
  Calculator,
  Car,
  ClipboardCheck,
  Clapperboard,
  Cloud,
  Code,
  Cpu,
  CreditCard,
  Database,
  Download,
  Droplets,
  Factory,
  FileSignature,
  FileText,
  Fingerprint,
  FlaskConical,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  HeartPulse,
  KeyRound,
  Landmark,
  Layers,
  Lock,
  Mail,
  MonitorPlay,
  Network,
  Package,
  PenTool,
  Pill,
  Plane,
  Play,
  Plug,
  QrCode,
  Radio,
  RadioTower,
  Satellite,
  Scale,
  Server,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  ShoppingCart,
  Signal,
  Smartphone,
  Stamp,
  Stethoscope,
  Terminal,
  Ticket,
  Timer,
  TrainFront,
  Truck,
  Tv,
  Umbrella,
  Wallet,
  Waves,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/** Allowlisted use-case icons — CSV `use_case_icon` values must be keys here. */
export const USE_CASE_ICONS: Record<string, LucideIcon> = {
  Activity,
  Antenna,
  Archive,
  Award,
  Banknote,
  Barcode,
  Bitcoin,
  Bluetooth,
  BookOpen,
  Building2,
  Cable,
  Calculator,
  ClipboardCheck,
  Code,
  Cpu,
  CreditCard,
  Database,
  Download,
  Droplets,
  Factory,
  FileSignature,
  FileText,
  Fingerprint,
  FlaskConical,
  Gauge,
  GitBranch,
  Globe,
  KeyRound,
  Landmark,
  Lock,
  Mail,
  MonitorPlay,
  Network,
  Package,
  PenTool,
  Pill,
  Play,
  Plug,
  QrCode,
  Radio,
  Satellite,
  Scale,
  Server,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Ship,
  ShoppingCart,
  Signal,
  Smartphone,
  Stamp,
  Stethoscope,
  Terminal,
  Ticket,
  Timer,
  TrainFront,
  Tv,
  Wallet,
  Waves,
}

/** One icon per canonical industry label (threats vocabulary). */
export const INDUSTRY_ICONS: Record<string, LucideIcon> = {
  'Aerospace / Aviation': Plane,
  'Automotive / Connected Vehicles': Car,
  'Cloud Computing / Data Centers': Cloud,
  'Critical Infrastructure / Energy': Zap,
  'Cross-Industry': Layers,
  'Cryptocurrency / Blockchain': Bitcoin,
  'Education / Research': GraduationCap,
  'Finance & Banking': Landmark,
  'Government & Defense': Shield,
  'Healthcare / Pharmaceutical': HeartPulse,
  'Hardware Security Modules': Cpu,
  Insurance: Umbrella,
  'Internet of Things (IoT)': RadioTower,
  'IT Industry / Software': Code,
  'Legal / Notary / eSignature': Scale,
  'Media / Entertainment / DRM': Clapperboard,
  'Payment Card Industry': CreditCard,
  'Rail / Transit': TrainFront,
  'Retail & E-Commerce': ShoppingCart,
  'Supply Chain / Logistics': Truck,
  Telecommunications: Antenna,
  'Water / Wastewater': Droplets,
}

export function useCaseIcon(name: string): LucideIcon {
  return USE_CASE_ICONS[name] ?? Lock
}

export function industryIcon(industry: string): LucideIcon {
  return INDUSTRY_ICONS[industry] ?? Globe
}
