// SPDX-License-Identifier: GPL-3.0-only
//
// Stateful hash-based signature panels (XMSS, LMS/HSS) for the HSM playground —
// the Sign & Verify tab's "Stateful" family (NIST SP 800-208, PKCS#11 v3.2
// §2.4 / §6.14). Backed by the real softhsmv3 PKCS#11 v3.2 stateful-signature
// engine.
//
// What makes these keys different is STATE: every C_Sign consumes one
// one-time leaf; signing twice from the same leaf index is a catastrophic
// key compromise. So, unlike every other panel, this one reads the engine's
// own remaining-signatures counter (`hsm_getKeysRemaining` —
// CKA_HSS_KEYS_REMAINING / the Rust engine's XMSS equivalent) after key
// generation and after every signature, and shows the leaf index advancing.
// An engine that publishes no counter (C++ XMSS today) is reported as
// exactly that — never a fabricated number.
import { useState } from 'react'
import { CheckCircle, XCircle, Loader2, AlertTriangle } from 'lucide-react'
import { Button } from '../../ui/button'
import { ErrorAlert } from '../../ui/error-alert'
import {
  CKM_XMSS,
  CKM_LMS,
  hsm_generateXMSSKeyPair,
  hsm_generateLMSKeyPair,
  hsm_statefulSignBytes,
  hsm_statefulVerifyBytes,
  hsm_getKeysRemaining,
} from '../../../wasm/softhsm'
import { useHsmContext } from './HsmContext'
import { HsmResultRow, toHex } from './shared'

export type StatefulFamily = 'xmss' | 'lms'

interface FamilyMeta {
  label: string
  /** Spec citation shown in the family header. */
  spec: string
  /** Parameter set actually generated by the button below. */
  paramSet: string
  mech: number
  defaultMessage: string
  keyFamily: 'xmss' | 'lms'
}

// A lazy function, not a top-level literal: the production build wraps this
// module's softhsm import in vite-plugin-top-level-await, so a top-level
// literal here would capture CKM_XMSS/CKM_LMS as `undefined` (they're only
// assigned once that chunk's own top-level await resolves, which happens
// AFTER this module's top-level runs). Dev/vitest don't use that plugin, so
// this bug is invisible outside a real production build. See
// pqctoday-priv/design/design_handoff_kmip_pkcs11_playground/GAPS-CLOSEOUT-PLAN-2026-09-02.md §2.1.
export const statefulFamilies = (): Record<StatefulFamily, FamilyMeta> => ({
  xmss: {
    label: 'XMSS',
    spec: 'PKCS#11 v3.2 — CKM_XMSS / CKK_XMSS · RFC 8391 · SP 800-208',
    paramSet: 'XMSS-SHA2_10_256 (2¹⁰ = 1,024 one-time leaves)',
    mech: CKM_XMSS,
    defaultMessage: 'Hello from XMSS!',
    keyFamily: 'xmss',
  },
  lms: {
    label: 'LMS / HSS',
    spec: 'PKCS#11 v3.2 §6.14 — CKM_HSS / CKK_HSS (single-level; the spec has no standalone CKM_LMS codepoint) · RFC 8554 · SP 800-208',
    paramSet: 'LMS_SHA256_M32_H5 + LMOTS_SHA256_N32_W1 (2⁵ = 32 one-time leaves)',
    mech: CKM_LMS,
    defaultMessage: 'Hello from LMS!',
    keyFamily: 'lms',
  },
})

/** Advisory threshold: below this many remaining leaves the warning turns red. */
const LOW_REMAINING = 2

/**
 * One panel, parameterised by family — XMSS and LMS differ only in the
 * mechanism, key-generation call and copy. Exported per-family wrappers keep
 * the previous import surface (`XmssPanel`, `LmsPanel`).
 */
export const StatefulSignPanel = ({ family }: { family: StatefulFamily }) => {
  const meta = statefulFamilies()[family]
  const { moduleRef, hSessionRef, registerKey, engineMode } = useHsmContext()
  const [handles, setHandles] = useState<{ pub: number; priv: number } | null>(null)
  const [message, setMessage] = useState(meta.defaultMessage)
  const [sig, setSig] = useState<Uint8Array | null>(null)
  const [verifyResult, setVerifyResult] = useState<boolean | null>(null)
  const [loadingOp, setLoadingOp] = useState<string | null>(null)
  const [error, setError] = useState<string | null>(null)
  // Leaf-index bookkeeping. `signCount` is how many signatures THIS panel has
  // issued with the current key (the leaf index the next signature will
  // consume, starting at 0). `remaining` is the engine's own counter, read
  // back after keygen and after every sign; `null` = engine publishes none.
  const [signCount, setSignCount] = useState(0)
  const [remaining, setRemaining] = useState<number | null>(null)
  const [lastAdvance, setLastAdvance] = useState<{ from: number; to: number } | null>(null)

  const run = async (label: string, fn: () => void) => {
    setError(null)
    setLoadingOp(label)
    try {
      await new Promise<void>((resolve) => {
        setTimeout(() => {
          try {
            fn()
            resolve()
          } catch (e) {
            setError(e instanceof Error ? e.message : String(e))
            resolve()
          }
        }, 0)
      })
    } finally {
      setLoadingOp(null)
    }
  }

  const readRemaining = (priv: number) => {
    const M = moduleRef.current!
    const hSession = hSessionRef.current
    setRemaining(hsm_getKeysRemaining(M, hSession, priv))
  }

  const handleGenKeys = () =>
    run('KeyGen', () => {
      const M = moduleRef.current!
      const hSession = hSessionRef.current
      const { pubHandle, privHandle } =
        family === 'xmss'
          ? // paramSet 1 = XMSS-SHA2_10_256
            hsm_generateXMSSKeyPair(M, hSession, 1)
          : // LMS_SHA256_M32_H5 (0x05) + LMOTS_SHA256_N32_W1 (0x01)
            hsm_generateLMSKeyPair(M, hSession)
      const engine = engineMode === 'rust' ? 'rust' : 'cpp'
      registerKey(M, hSession, {
        handle: pubHandle,
        family: meta.keyFamily,
        role: 'public',
        label: `${meta.label.split(' ')[0]} Public Key`,
        engine,
        generatedAt: new Date().toISOString(),
      })
      registerKey(M, hSession, {
        handle: privHandle,
        family: meta.keyFamily,
        role: 'private',
        label: `${meta.label.split(' ')[0]} Private Key`,
        engine,
        generatedAt: new Date().toISOString(),
      })
      setHandles({ pub: pubHandle, priv: privHandle })
      setSig(null)
      setVerifyResult(null)
      setSignCount(0)
      setLastAdvance(null)
      readRemaining(privHandle)
    })

  const handleSign = () =>
    run('Sign', () => {
      const M = moduleRef.current!
      const hSession = hSessionRef.current
      const msgBytes = new TextEncoder().encode(message)
      const s = hsm_statefulSignBytes(M, hSession, meta.mech, handles!.priv, msgBytes)
      setSig(s)
      setVerifyResult(null)
      setLastAdvance({ from: signCount, to: signCount + 1 })
      setSignCount((n) => n + 1)
      readRemaining(handles!.priv)
    })

  const handleVerify = () =>
    run('Verify', () => {
      const M = moduleRef.current!
      const hSession = hSessionRef.current
      const msgBytes = new TextEncoder().encode(message)
      const valid =
        hsm_statefulVerifyBytes(M, hSession, meta.mech, handles!.pub, msgBytes, sig!) === 0
      setVerifyResult(valid)
    })

  const low = remaining !== null && remaining <= LOW_REMAINING

  return (
    <div className="space-y-4" data-tour={`pkcs-op-stateful-${family}`}>
      <div className="text-[11px] text-muted-foreground font-mono">{meta.spec}</div>

      {/* Reuse warning — always visible: the whole point of this family. */}
      <div
        role="note"
        className={`flex items-start gap-2 rounded-lg border p-3 text-xs ${
          low
            ? 'border-status-error/50 bg-status-error/10 text-status-error'
            : 'border-status-warning/40 bg-status-warning/5 text-foreground'
        }`}
      >
        <AlertTriangle
          size={14}
          className={`mt-0.5 shrink-0 ${low ? 'text-status-error' : 'text-status-warning'}`}
          aria-hidden="true"
        />
        <div className="space-y-0.5">
          <div className="font-semibold">
            Stateful — each private-key use advances a leaf-index counter; reusing an index is
            catastrophic key compromise.
          </div>
          <div className="text-muted-foreground">
            Never restore this key from a backup, never clone it to a second HSM, and stop signing
            when the counter reaches zero. {meta.paramSet}.
          </div>
          {low && (
            <div className="font-semibold">
              Only {remaining} {remaining === 1 ? 'signature' : 'signatures'} left on this key.
            </div>
          )}
        </div>
      </div>

      <div className="space-y-2">
        <div className="flex items-center gap-2">
          <Button
            variant="gradient"
            size="sm"
            onClick={handleGenKeys}
            disabled={loadingOp !== null}
            data-tour={`pkcs-op-stateful-${family}-keygen`}
          >
            {loadingOp === 'KeyGen' && <Loader2 size={14} className="animate-spin mr-1" />}
            {handles ? `Regen ${meta.label.split(' ')[0]}` : 'Generate Key Pair'}
          </Button>
        </div>
        {handles && (
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-1">
            <HsmResultRow label="pub handle" value={`h=${handles.pub}`} />
            <HsmResultRow label="priv handle" value={`h=${handles.priv}`} />
            <HsmResultRow label="Leaf index (next)" value={String(signCount)} />
            <HsmResultRow
              label="Signatures remaining"
              value={
                remaining === null
                  ? `counter not published by the ${engineMode === 'rust' ? 'Rust' : 'C++'} engine`
                  : String(remaining)
              }
            />
          </div>
        )}
      </div>

      {handles && (
        <div className="space-y-2 rounded-lg border border-border p-3">
          <input
            type="text"
            value={message}
            onChange={(e) => {
              setMessage(e.target.value)
              setSig(null)
              setVerifyResult(null)
            }}
            placeholder="Message to sign"
            className="w-full text-xs rounded-lg px-3 py-1.5 bg-muted border border-border text-foreground"
          />
          <div className="flex gap-2">
            <Button
              variant="gradient"
              size="sm"
              onClick={handleSign}
              disabled={loadingOp !== null || remaining === 0}
              data-tour={`pkcs-op-stateful-${family}-sign`}
            >
              {loadingOp === 'Sign' && <Loader2 size={14} className="animate-spin mr-1" />} C_Sign
              <span className="ml-1 font-normal opacity-80">(advances leaf index)</span>
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={handleVerify}
              disabled={loadingOp !== null || !sig}
              data-tour={`pkcs-op-stateful-${family}-verify`}
            >
              {loadingOp === 'Verify' && <Loader2 size={14} className="animate-spin mr-1" />}{' '}
              C_Verify
            </Button>
          </div>
          {lastAdvance && (
            <HsmResultRow
              label="Leaf index"
              value={`${lastAdvance.from} → ${lastAdvance.to}${
                remaining !== null ? ` · ${remaining} remaining` : ''
              }`}
            />
          )}
          {sig && <HsmResultRow label={`Sig (${sig.length}B)`} value={toHex(sig)} />}
          {verifyResult !== null && (
            <div
              className={`flex items-center gap-2 text-xs font-medium rounded px-2 py-1 ${verifyResult ? 'text-status-success bg-status-success/10' : 'text-status-error bg-status-error/10'}`}
            >
              {verifyResult ? (
                <>
                  <CheckCircle size={12} /> Valid
                </>
              ) : (
                <>
                  <XCircle size={12} /> Invalid
                </>
              )}
            </div>
          )}
        </div>
      )}

      {error && <ErrorAlert message={error} />}
    </div>
  )
}

export const XmssPanel = () => <StatefulSignPanel family="xmss" />
export const LmsPanel = () => <StatefulSignPanel family="lms" />
