// SPDX-License-Identifier: GPL-3.0-only
/**
 * Generates tools/acvp-native/pkcs11_constants.py — the Python native runner's
 * PKCS#11 v3.2 constants — FROM the hub's own tables, so the two runners can
 * never disagree about a mechanism/attribute/return-value number:
 *   - every numeric `export const` in src/wasm/softhsm/constants.ts
 *   - RV_NAMES (CKR_* names) from src/wasm/softhsm.ts (what rvName() prints,
 *     i.e. the `detail` strings the Node CLI writes into evidence.json)
 *
 * Entry: scripts/gen-acvp-native-constants.ts [--check].
 */
import * as C from '../../wasm/softhsm/constants'
import { RV_NAMES } from '../../wasm/softhsm'

export const NATIVE_CONSTANTS_PATH = 'tools/acvp-native/pkcs11_constants.py'

const hex = (n: number): string => `0x${(n >>> 0).toString(16).padStart(8, '0')}`

export const renderNativeConstants = (): string => {
  const nums = Object.entries(C)
    .filter((e): e is [string, number] => typeof e[1] === 'number' && Number.isInteger(e[1]))
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
  const rv = Object.entries(RV_NAMES)
    .map(([k, v]) => [Number(k), v] as const)
    .sort((a, b) => a[0] - b[0])
  const lines = [
    '# SPDX-License-Identifier: GPL-3.0-only',
    '# GENERATED by scripts/gen-acvp-native-constants.ts — DO NOT EDIT.',
    '# Source of truth: src/wasm/softhsm/constants.ts (numeric exports) and',
    '# RV_NAMES in src/wasm/softhsm.ts. Regenerate: npm run gen:acvp-native-constants',
    '# Drift check (local gate): npm run gen:acvp-native-constants:check',
    '"""PKCS#11 v3.2 constants shared with the hub\'s TypeScript engine adapter."""',
    '',
    ...nums.map(([k, v]) => `${k} = ${hex(v)}`),
    '',
    '# CK_RV -> name, exactly as rvName() in src/wasm/softhsm.ts renders it.',
    'CKR_NAMES = {',
    ...rv.map(([k, v]) => `    ${hex(k)}: "${v}",`),
    '}',
    '',
    '',
    'def rv_name(rv):',
    '    """Mirror of rvName(): known name, else 0x%08x."""',
    '    return CKR_NAMES.get(rv & 0xFFFFFFFF, "0x%08x" % (rv & 0xFFFFFFFF))',
    '',
  ]
  return lines.join('\n')
}
