// SPDX-License-Identifier: GPL-3.0-only
/**
 * Generates tools/acvp-native/pkcs11_constants.py — the Python native runner's
 * PKCS#11 v3.2 constants — FROM the hub's own tables, so the two runners can
 * never disagree about a mechanism/attribute/return-value number:
 *   - every numeric `export const` in src/wasm/softhsm/constants.ts
 *   - RV_NAMES (CKR_* names) from src/wasm/softhsm.ts (what rvName() prints,
 *     i.e. the `detail` strings the Node CLI writes into evidence.json)
 *
 * Entry: scripts/gen-acvp-native-constants.ts [--check].
 */
import * as C from '../../wasm/softhsm/constants'
import { RV_NAMES } from '../../wasm/softhsm'
import { PINNED_SCHEMAS } from '../acvp/schemas/registry'
import {
  DISCLAIMER_GENERAL,
  DISCLAIMER_IMPORT,
  EVIDENCE_VERSION,
  PROTOTYPE_LABEL,
} from '../acvp/evidence'
import { IR_VERSION } from '../acvp/ir'
import { PLAN_VERSION, VENDOR_DEFINED_MECHANISMS } from '../acvp/dispatch'
import fixtureProvenance from '../acvp/__fixtures__/nist-acvp-server/PROVENANCE.json'

export const NATIVE_CONSTANTS_PATH = 'tools/acvp-native/pkcs11_constants.py'
export const HUB_CONTRACT_PATH = 'tools/acvp-native/hub_contract.json'

/**
 * The non-PKCS#11 facts the Python runner must reproduce to write an
 * evidence.json that validates against src/services/acvp/schemas/
 * evidence.v<N>.schema.json (current version): evidence/IR/plan versions, the verbatim plan §2.2
 * disclaimers, the pinned schema metadata, and the known public fixtures
 * (prompt SHA-256 → NIST ACVP-Server identity). Generated, never hand-edited.
 */
export const renderHubContract = (): string =>
  `${JSON.stringify(
    {
      _comment:
        'GENERATED by scripts/gen-acvp-native-constants.ts from src/services/acvp/{evidence,ir,dispatch}.ts, schemas/registry.ts and __fixtures__/nist-acvp-server/PROVENANCE.json — DO NOT EDIT.',
      evidenceVersion: EVIDENCE_VERSION,
      irVersion: IR_VERSION,
      planVersion: PLAN_VERSION,
      label: PROTOTYPE_LABEL,
      disclaimers: [DISCLAIMER_GENERAL, DISCLAIMER_IMPORT],
      pinnedSchemas: PINNED_SCHEMAS.map((s) => ({
        id: s.id,
        algorithm: s.algorithm,
        mode: s.mode,
        revision: s.revision,
        promptSchemaFile: s.promptSchemaFile,
        responseSchemaFile: s.responseSchemaFile,
        specRepository: s.specSource.repository,
        specCommit: s.specSource.commit,
        specDocument: s.specSource.document,
      })),
      vendorDefinedMechanisms: Object.entries(VENDOR_DEFINED_MECHANISMS).map(([name, m]) => ({
        name,
        value: m?.value,
        source: m?.source,
      })),
      knownFixtures: fixtureProvenance.files.map((f) => ({
        sha256: f.sha256,
        repository: fixtureProvenance.repository,
        commit: fixtureProvenance.commit,
        upstreamPath: f.upstreamPath,
      })),
    },
    null,
    2
  )}\n`

const hex = (n: number): string => `0x${(n >>> 0).toString(16).padStart(8, '0')}`

export const renderNativeConstants = (): string => {
  const nums = (Object.entries(C) as Array<[string, unknown]>)
    .filter((e): e is [string, number] => typeof e[1] === 'number' && Number.isInteger(e[1]))
    .sort(([a], [b]) => (a < b ? -1 : a > b ? 1 : 0))
  const rv = Object.entries(RV_NAMES)
    .map(([k, v]) => [Number(k), v] as const)
    .sort((a, b) => a[0] - b[0])
  const lines = [
    '# SPDX-License-Identifier: GPL-3.0-only',
    '# GENERATED by scripts/gen-acvp-native-constants.ts — DO NOT EDIT.',
    '# Source of truth: src/wasm/softhsm/constants.ts (numeric exports) and',
    '# RV_NAMES in src/wasm/softhsm.ts. Regenerate: npm run gen:acvp-native-constants',
    '# Drift check (local gate): npm run gen:acvp-native-constants:check',
    '"""PKCS#11 v3.2 constants shared with the hub\'s TypeScript engine adapter."""',
    '',
    ...nums.map(([k, v]) => `${k} = ${hex(v)}`),
    '',
    '# CK_RV -> name, exactly as rvName() in src/wasm/softhsm.ts renders it.',
    'CKR_NAMES = {',
    ...rv.map(([k, v]) => `    ${hex(k)}: "${v}",`),
    '}',
    '',
    '',
    'def rv_name(rv):',
    '    """Mirror of rvName(): known name, else 0x%08x."""',
    '    return CKR_NAMES.get(rv & 0xFFFFFFFF, "0x%08x" % (rv & 0xFFFFFFFF))',
    '',
  ]
  return lines.join('\n')
}
