// SPDX-License-Identifier: GPL-3.0-only
/**
 * Anchor KAT tests — verify pinned PQC vectors against our openssl.wasm.
 *
 * Each fixture under src/test/kat/fixtures/ is a JSON blob containing a
 * frozen (publicKey, message, signature) or (privateKey, ciphertext,
 * sharedSecret) tuple. The fixtures were generated by Node 24's bundled
 * OpenSSL 3.5.4 via scripts/generate-kat-fixtures.mjs and committed to
 * the repo. This test loads them and verifies / decapsulates with the
 * WASM bundle (OpenSSL 3.6.2).
 *
 * The cross-impl tests (mldsa-cross-impl.test.ts, mlkem-cross-impl.test.ts)
 * catch divergence between fresh Node sigs and WASM verify on each run.
 * These anchor tests additionally catch the case where BOTH implementations
 * regress the same way later — the bytes are frozen, so the verification
 * MUST keep succeeding.
 *
 * To regenerate fixtures after a deliberate OpenSSL upgrade:
 *   node scripts/generate-kat-fixtures.mjs
 * Or to confirm fixtures exist without overwriting:
 *   node scripts/generate-kat-fixtures.mjs --check
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { newModule, runOpenssl, writeFile, readFileBin } from './openssl-driver'

const FIXTURES_DIR = join(process.cwd(), 'src', 'test', 'kat', 'fixtures')

interface SigFixture {
  kind: 'signature'
  alg: string
  expectedSigLen: number
  messageBase64: string
  publicKeyPem: string
  signatureBase64: string
}

interface KemFixture {
  kind: 'kem'
  alg: string
  expectedCtLen: number
  expectedSsLen: number
  privateKeyPem: string
  ciphertextBase64: string
  expectedSharedSecretBase64: string
}

function loadFixture<T>(alg: string): T {
  return JSON.parse(readFileSync(join(FIXTURES_DIR, `${alg}.json`), 'utf-8')) as T
}

function b64decode(s: string): Buffer {
  return Buffer.from(s, 'base64')
}

describe('Anchor KAT — signature verification (pinned fixtures)', () => {
  const sigAlgs = ['ml-dsa-44', 'ml-dsa-65', 'ml-dsa-87', 'slh-dsa-sha2-128s']

  it.each(sigAlgs)(
    '%s: pinned signature verifies under WASM (regression anchor)',
    async (alg) => {
      const fx = loadFixture<SigFixture>(alg)
      expect(fx.kind).toBe('signature')
      const signature = b64decode(fx.signatureBase64)
      const message = b64decode(fx.messageBase64)
      expect(signature.length).toBe(fx.expectedSigLen)

      const M = await newModule({ quiet: true })
      const pubPath = `/ssl/anchor-${alg}.pub.pem`
      const msgPath = `/ssl/anchor-${alg}.msg.bin`
      const sigPath = `/ssl/anchor-${alg}.sig.bin`
      writeFile(M, pubPath, fx.publicKeyPem)
      writeFile(M, msgPath, new Uint8Array(message))
      writeFile(M, sigPath, new Uint8Array(signature))

      const { rc, stderr } = runOpenssl(M, [
        'pkeyutl',
        '-verify',
        '-inkey',
        pubPath,
        '-pubin',
        '-rawin',
        '-in',
        msgPath,
        '-sigfile',
        sigPath,
      ])
      expect(rc, `stderr tail: ${stderr.slice(-300)}`).toBe(0)
    },
    120_000
  )

  it.each(sigAlgs)(
    '%s: pinned signature with flipped bit fails verification',
    async (alg) => {
      const fx = loadFixture<SigFixture>(alg)
      const message = b64decode(fx.messageBase64)
      const signature = b64decode(fx.signatureBase64)
      const tampered = Buffer.from(signature)
      tampered[Math.floor(tampered.length / 2)] ^= 0x01

      const M = await newModule({ quiet: true })
      writeFile(M, `/ssl/t-${alg}.pub.pem`, fx.publicKeyPem)
      writeFile(M, `/ssl/t-${alg}.msg.bin`, new Uint8Array(message))
      writeFile(M, `/ssl/t-${alg}.sig.bin`, new Uint8Array(tampered))

      const { rc } = runOpenssl(M, [
        'pkeyutl',
        '-verify',
        '-inkey',
        `/ssl/t-${alg}.pub.pem`,
        '-pubin',
        '-rawin',
        '-in',
        `/ssl/t-${alg}.msg.bin`,
        '-sigfile',
        `/ssl/t-${alg}.sig.bin`,
      ])
      expect(rc).not.toBe(0)
    },
    120_000
  )
})

describe('Anchor KAT — KEM decapsulation (pinned fixtures)', () => {
  const kemAlgs = ['ml-kem-512', 'ml-kem-768', 'ml-kem-1024']

  it.each(kemAlgs)(
    '%s: pinned ciphertext decapsulates to the expected shared secret',
    async (alg) => {
      const fx = loadFixture<KemFixture>(alg)
      expect(fx.kind).toBe('kem')
      const ct = b64decode(fx.ciphertextBase64)
      const expectedSs = b64decode(fx.expectedSharedSecretBase64)
      expect(ct.length).toBe(fx.expectedCtLen)
      expect(expectedSs.length).toBe(fx.expectedSsLen)

      const M = await newModule({ quiet: true })
      const skPath = `/ssl/anchor-kem-${alg}.sk.pem`
      const ctPath = `/ssl/anchor-kem-${alg}.ct.bin`
      const ssPath = `/ssl/anchor-kem-${alg}.ss.bin`
      writeFile(M, skPath, fx.privateKeyPem)
      writeFile(M, ctPath, new Uint8Array(ct))

      const { rc, stderr } = runOpenssl(M, [
        'pkeyutl',
        '-decap',
        '-inkey',
        skPath,
        '-in',
        ctPath,
        '-out',
        ssPath,
      ])
      expect(rc, `stderr tail: ${stderr.slice(-300)}`).toBe(0)
      const recoveredSs = readFileBin(M, ssPath)
      expect(Buffer.from(recoveredSs).equals(expectedSs)).toBe(true)
    },
    120_000
  )
})
