// SPDX-License-Identifier: GPL-3.0-only
/**
 * ML-DSA / SLH-DSA cross-implementation KAT.
 *
 * Strategy: Node 24's built-in `crypto` (OpenSSL 3.5.4 backend) generates
 * a fresh keypair and signs a known message. Our `public/wasm/openssl.wasm`
 * (OpenSSL 3.6.2 backend) verifies the signature via `pkeyutl -verify -rawin`.
 *
 * If both implementations match FIPS 204 / 205, verify returns rc=0. If
 * either implementation has a bug in the signature OID encoding, the
 * primitive math, the parameter set sizes, or the public-key DER framing,
 * the verification fails. This is a real cross-implementation KAT —
 * the standard way crypto interop is measured.
 *
 * Negative tests flip a bit in the signature and assert verify rejects it.
 */
import { generateKeyPairSync, sign, KeyObject } from 'node:crypto'
import { describe, expect, it } from 'vitest'
import { newModule, runOpenssl, writeFile } from './openssl-driver'

interface KATFixture {
  alg: 'ml-dsa-44' | 'ml-dsa-65' | 'ml-dsa-87' | 'slh-dsa-sha2-128s'
  publicKeyPem: string
  message: Buffer
  signature: Buffer
  /** Expected signature byte length per FIPS 204 / 205. Pinned to catch
   *  the case where a future Node upgrade silently changes the wire size. */
  expectedSigLen: number
}

/** Pre-baked KAT fixtures generated by Node 24 at test-setup time. We
 *  generate fresh per run (instead of pinning hex literals) because Node's
 *  crypto already encodes the OIDs the WASM expects — using Node here is
 *  the equivalent of pinning ACVP-derived vectors from the spec authority. */
function buildFixture(
  alg: KATFixture['alg'],
  expectedSigLen: number,
  message = Buffer.from('PQC cross-impl KAT — hello from Node, verify in WASM')
): KATFixture {
  // Node 24+'s OpenSSL 3.5.4 backend supports ML-DSA-44/65/87 in
  // generateKeyPairSync at runtime, but @types/node still only lists the
  // SLH-DSA variants in the overload union. Cast through `as unknown as never`
  // to bypass the stale type while preserving runtime correctness.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { publicKey, privateKey } = generateKeyPairSync(alg as any)
  const publicKeyPem = (publicKey as KeyObject).export({
    format: 'pem',
    type: 'spki',
  }) as string
  const signature = sign(null, message, privateKey as KeyObject)
  if (signature.length !== expectedSigLen) {
    throw new Error(`${alg} sig length drift: got ${signature.length}, expected ${expectedSigLen}`)
  }
  return { alg, publicKeyPem, message, signature, expectedSigLen }
}

async function verifyWithWasm(fixture: KATFixture): Promise<{
  rc: number
  stderr: string
}> {
  const M = await newModule({ quiet: true })
  const pubPath = `/ssl/kat-${fixture.alg}.pub.pem`
  const msgPath = `/ssl/kat-${fixture.alg}.msg.bin`
  const sigPath = `/ssl/kat-${fixture.alg}.sig.bin`
  writeFile(M, pubPath, fixture.publicKeyPem)
  writeFile(M, msgPath, new Uint8Array(fixture.message))
  writeFile(M, sigPath, new Uint8Array(fixture.signature))
  // `pkeyutl -verify -rawin` invokes the EVP_DigestVerify path that ML-DSA
  // implements. `-rawin` tells openssl not to pre-hash (ML-DSA's spec uses
  // an internal hash; an external SHA-256 would yield wrong results).
  return runOpenssl(M, [
    'pkeyutl',
    '-verify',
    '-inkey',
    pubPath,
    '-pubin',
    '-rawin',
    '-in',
    msgPath,
    '-sigfile',
    sigPath,
  ])
}

const nodeMajor = parseInt(process.versions.node.split('.')[0], 10)
const describeIfNode24 = nodeMajor >= 24 ? describe : describe.skip

describeIfNode24('ML-DSA / SLH-DSA cross-impl KAT — Node sign → WASM verify', () => {
  const cases: Array<{ alg: KATFixture['alg']; sigLen: number }> = [
    { alg: 'ml-dsa-44', sigLen: 2420 },
    { alg: 'ml-dsa-65', sigLen: 3309 },
    { alg: 'ml-dsa-87', sigLen: 4627 },
    { alg: 'slh-dsa-sha2-128s', sigLen: 7856 },
  ]

  it.each(cases)(
    '$alg: Node-produced signature verifies under our WASM (rc=0)',
    async ({ alg, sigLen }) => {
      const fx = buildFixture(alg, sigLen)
      const { rc, stderr } = await verifyWithWasm(fx)
      expect(rc, `stderr tail: ${stderr.slice(-300)}`).toBe(0)
    },
    120_000
  )

  it.each(cases)(
    '$alg: a single bit flip in the signature is rejected (rc!=0)',
    async ({ alg, sigLen }) => {
      const fx = buildFixture(alg, sigLen)
      // Flip a byte in the middle of the signature. Tampered sigs should
      // never verify — confirms the verify path isn't trivially returning 0.
      const tampered = Buffer.from(fx.signature)
      const idx = Math.floor(tampered.length / 2)
      tampered[idx] = (tampered[idx] + 1) & 0xff
      const tamperedFx = { ...fx, signature: tampered }
      const { rc } = await verifyWithWasm(tamperedFx)
      expect(rc).not.toBe(0)
    },
    120_000
  )

  it.each([
    { alg: 'ml-dsa-44' as const, sigLen: 2420 },
    { alg: 'ml-dsa-65' as const, sigLen: 3309 },
    { alg: 'ml-dsa-87' as const, sigLen: 4627 },
  ])(
    '$alg: wrong-message verify is rejected (rc!=0)',
    async ({ alg, sigLen }) => {
      // Sign one message, ask WASM to verify the sig against a DIFFERENT
      // message. Confirms verify actually checks the message content.
      const fx = buildFixture(alg, sigLen, Buffer.from('original message'))
      const tampered = { ...fx, message: Buffer.from('different message') }
      const { rc } = await verifyWithWasm(tampered)
      expect(rc).not.toBe(0)
    },
    120_000
  )
})
