// SPDX-License-Identifier: GPL-3.0-only
import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import { buildPackageParts, type Slide, type TextRun } from './pptxOoxml'

/**
 * Convert an artifact's markdown export into a 16:9 PPTX deck.
 *
 * Parsing rules (intentionally loose — artifact builders emit consistent md):
 *   - `# Heading` → deck title slide (first occurrence)
 *   - `## Heading` → new slide, heading becomes the slide title
 *   - Body paragraphs → bullet/paragraph content on the current slide
 *   - `- item` → bullet
 *   - `**bold**` markers are stripped (PPTX inline bold not yet wired)
 *
 * Designed for executive artifacts (Board Pitch, CRQC Scenario, etc.) where
 * slides map 1:1 to H2 sections.
 *
 * REPLACED pptxgenjs 2026-08-21. That library was here only to lay out text
 * boxes, and it pulled in `image-size`, which carries two open high-severity
 * advisories with no patched version and whose only npm-suggested remedy is a
 * breaking downgrade to pptxgenjs 1.1.5. The deck is emitted directly as
 * PresentationML now (see pptxOoxml.ts), which removes the dependency chain
 * instead of trading it for another one. Slide geometry, colours and font
 * sizes below are unchanged from the pptxgenjs version.
 */
export async function markdownToPptx(markdown: string, filename: string): Promise<void> {
  const blob = await buildPptxBlob(markdown)
  saveAs(blob, `${filename}.pptx`)
}

/**
 * The deck as a Blob, without touching the DOM.
 *
 * Split out for the same reason docxExport.ts splits its builder: the parsing
 * and layout can then be asserted in tests without triggering a download.
 */
export async function buildPptxBlob(markdown: string): Promise<Blob> {
  const zip = new JSZip()
  for (const [path, xml] of Object.entries(buildPackageParts(markdownToSlides(markdown)))) {
    zip.file(path, xml)
  }
  return zip.generateAsync({
    type: 'blob',
    mimeType: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  })
}

/** Parsed deck structure, exported so tests can assert the markdown mapping. */
export function markdownToSlides(markdown: string): Slide[] {
  const lines = markdown.split(/\r?\n/)

  type Block = { title: string; body: string[] }
  let deckTitle = ''
  const blocks: Block[] = []
  let current: Block | null = null

  for (const rawLine of lines) {
    const line = rawLine.trimEnd()
    if (!deckTitle && line.startsWith('# ')) {
      deckTitle = stripInline(line.slice(2))
      continue
    }
    if (line.startsWith('## ')) {
      if (current) blocks.push(current)
      current = { title: stripInline(line.slice(3)), body: [] }
      continue
    }
    if (line.startsWith('---')) continue // md hr
    if (line.trim() === '') {
      if (current && current.body.length > 0) current.body.push('') // preserve paragraph breaks
      continue
    }
    if (!current) continue // content before any H2 is ignored
    current.body.push(stripInline(line))
  }
  if (current) blocks.push(current)

  const slides: Slide[] = []

  // ── Title slide ──
  if (deckTitle) {
    slides.push({
      background: 'F8FAFC',
      textBoxes: [
        {
          xIn: 0.5,
          yIn: 2.8,
          wIn: 12.3,
          hIn: 1.2,
          runs: [{ text: deckTitle }],
          fontSize: 40,
          bold: true,
          color: '0F172A',
          align: 'ctr',
        },
        {
          xIn: 0.5,
          yIn: 4.2,
          wIn: 12.3,
          hIn: 0.5,
          runs: [{ text: 'Generated by PQC Today · Command Center' }],
          fontSize: 14,
          color: '64748B',
          align: 'ctr',
        },
        {
          xIn: 0.5,
          yIn: 4.8,
          wIn: 12.3,
          hIn: 0.4,
          runs: [{ text: new Date().toLocaleDateString(undefined, { dateStyle: 'long' }) }],
          fontSize: 12,
          color: '94A3B8',
          align: 'ctr',
        },
      ],
    })
  }

  // ── Content slides ──
  for (const b of blocks) {
    const runs: TextRun[] = []
    for (const raw of b.body) {
      const trimmed = raw.trim()
      if (!trimmed) continue
      if (trimmed.startsWith('- ')) {
        runs.push({ text: trimmed.slice(2), bullet: true })
      } else {
        runs.push({ text: trimmed })
      }
    }

    const textBoxes: Slide['textBoxes'] = [
      {
        xIn: 0.5,
        yIn: 0.4,
        wIn: 12.3,
        hIn: 0.7,
        runs: [{ text: b.title }],
        fontSize: 26,
        bold: true,
        color: '0F172A',
      },
    ]
    if (runs.length > 0) {
      textBoxes.push({
        xIn: 0.5,
        yIn: 1.4,
        wIn: 12.3,
        hIn: 5.8,
        runs,
        fontSize: 16,
        color: '334155',
        anchor: 't',
        spaceAfter: 8,
      })
    }
    textBoxes.push({
      xIn: 0.5,
      yIn: 7.1,
      wIn: 12.3,
      hIn: 0.3,
      runs: [{ text: 'PQC Today · Command Center' }],
      fontSize: 9,
      color: '94A3B8',
      align: 'r',
    })

    slides.push({
      background: 'FFFFFF',
      textBoxes,
      lines: [{ xIn: 0.5, yIn: 1.15, wIn: 12.3, color: 'CBD5E1', widthPt: 1 }],
    })
  }

  return slides
}

/** Strip minimal inline markdown (bold / italic markers) for PPTX text. */
function stripInline(s: string): string {
  return s
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/__([^_]+)__/g, '$1')
    .replace(/\*(?!\s)([^*]+?)\*/g, '$1')
    .replace(/_([^_\s][^_]*?)_/g, '$1')
    .replace(/`([^`]+)`/g, '$1')
}
