// SPDX-License-Identifier: GPL-3.0-only
// @vitest-environment node
/**
 * D4: the synthetic datasets are not committed; the generator is. This pins
 * every generated byte to the SHA-256 recorded in the manifest, so a change to
 * the generator (or a platform difference) cannot silently change a dataset
 * that parity results and workshop text refer to.
 */
import { createHash } from 'node:crypto'
import { describe, expect, it } from 'vitest'
import manifest from '../../../public/data/entropy/d4-synthetic-manifest.json'
import { D4_DATASETS, KAT_FIXTURE, KAT_IID_FIXTURE, Xoshiro128ss } from './syntheticDatasets'

const sha256 = (b: Uint8Array) => createHash('sha256').update(b).digest('hex')

describe('D4 synthetic datasets', () => {
  it('manifest labels everything synthetic', () => {
    expect(manifest.label).toMatch(/^SYNTHETIC/)
    for (const d of manifest.datasets) expect(d.provenance).toBe('synthetic')
  })

  it('xoshiro128** stream is stable (first outputs for seed 1)', () => {
    const r = new Xoshiro128ss(1)
    const first = Array.from({ length: 4 }, () => r.nextU32())
    expect(first.every((x) => Number.isInteger(x) && x >= 0 && x < 2 ** 32)).toBe(true)
    const again = new Xoshiro128ss(1)
    expect(Array.from({ length: 4 }, () => again.nextU32())).toEqual(first)
  })

  for (const spec of D4_DATASETS) {
    it(`${spec.id}: regenerates to the manifest SHA-256`, () => {
      const entry = manifest.datasets.find((d) => d.id === spec.id)
      expect(entry).toBeDefined()
      const bytes = spec.build()
      expect(bytes.length).toBe(entry!.bytes)
      expect(sha256(bytes)).toBe(entry!.sha256)
      const mask = (1 << spec.bitsPerSymbol) - 1
      expect(bytes.every((b) => (b & ~mask) === 0)).toBe(true)
    })
  }

  it('KAT fixtures regenerate to the manifest SHA-256', () => {
    expect(sha256(KAT_FIXTURE.build())).toBe(manifest.katFixture.sha256)
    expect(sha256(KAT_IID_FIXTURE.build())).toBe(manifest.katIidFixture.sha256)
  })
})
