// SPDX-License-Identifier: GPL-3.0-only
/**
 * Node-only I/O for a WS-H evidence run directory (never import from browser
 * code). Layout — evidence/acvp-xplat/<runId>/:
 *
 *   targets.json                          every Q3 target, "run" | "not run" + reason
 *   bundles/<fixture>/manifest.json       the fixture bundle manifest every target consumed
 *   bundles/<fixture>/response.json       the bundle's reference response (hash-pinned by the manifest)
 *   bundles/<fixture>/plan-index.json     payload-free plan skeleton, frozen with the run
 *   targets/<target>/build-info.json      (native) engine/build facts the runner cannot observe
 *   targets/<target>/<fixture>/{response,evidence,execution-environment}.json
 *   matrix.json, matrix.md                generated by scripts/acvp-xplat-compare.ts
 *   divergences/<target>/<fixture>/tg<tg>-tc<tc>.json   minimal cases (H-5), if any
 *
 * Only JSON/Markdown lives here; prompt/IR/plan are NOT copied (the prompt is
 * the committed public fixture, pinned by the manifest; the plan's payload-free
 * skeleton is frozen as plan-index.json, verified against the live pipeline
 * whenever that still reproduces the manifest's plan hash).
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { canonicalJson, sha256Hex, type JsonObject } from '../../acvp/ir'
import { compareToExpected } from '../../acvp/compare'
import { preparePrompt } from '../../acvp/run'
import { FIXTURE_NAMES, readFixture } from '../../acvp/node/fixtures'
import { identifyKnownFixture } from '../../acvp/evidence'
import {
  compareTargets,
  planIndexOf,
  renderMatrixMarkdown,
  type CompareOutput,
  type FixtureRef,
  type PlanIndexItem,
  type TargetInput,
} from '../compare'
import { XPLAT_TARGETS, type DeclaredTarget } from '../targets'

const readJson = (p: string): unknown => JSON.parse(readFileSync(p, 'utf8'))

export interface FixtureLoadNote {
  fixture: string
  /** false once the live dispatch rules produce a different plan than the frozen run (expected after WS-F growth). */
  livePlanReproducible: boolean
}

/**
 * Load the FROZEN per-fixture facts of a run: bundle manifest, its plan index
 * and reference response. Integrity is checked against the committed
 * manifest (prompt bytes, response bytes) and against NIST expectedResults
 * (every reference answer must match); the live pipeline is only consulted to
 * report whether it still reproduces the frozen plan.
 */
export const loadFixtureRefs = async (
  repoRoot: string,
  runDir: string,
  notes: FixtureLoadNote[] = []
): Promise<FixtureRef[]> => {
  const out: FixtureRef[] = []
  for (const name of FIXTURE_NAMES) {
    const dir = path.join(runDir, 'bundles', name)
    const manifestText = readFileSync(path.join(dir, 'manifest.json'), 'utf8')
    const manifest = JSON.parse(manifestText) as {
      schemaId: string
      vsId: number
      files: Record<string, string>
      canonicalSha256: { ir: string; plan: string; response: string }
    }
    const promptText = readFixture(repoRoot, name, 'prompt.json')
    const referenceText = readFileSync(path.join(dir, 'response.json'), 'utf8')
    const checks: Array<[string, string, string]> = [
      ['prompt.json SHA-256', await sha256Hex(promptText), manifest.files['prompt.json']],
      ['response.json SHA-256', await sha256Hex(referenceText), manifest.files['response.json']],
    ]
    for (const [what, have, want] of checks) {
      if (have !== want) throw new Error(`${dir}: ${what} ${have} ≠ manifest ${want}`)
    }
    const reference = JSON.parse(referenceText) as unknown
    const golden = compareToExpected(
      reference,
      JSON.parse(readFixture(repoRoot, name, 'expectedResults.json'))
    )
    if (golden.mismatched.length > 0 || golden.unexpected.length > 0) {
      throw new Error(`${dir}: reference response disagrees with NIST expectedResults.json`)
    }
    const planIndex = readJson(path.join(dir, 'plan-index.json')) as PlanIndexItem[]
    const prepared = await preparePrompt(promptText)
    if (!prepared.ok) throw new Error(`fixture ${name} no longer parses`)
    const livePlanReproducible =
      (await sha256Hex(canonicalJson(prepared.plan))) === manifest.canonicalSha256.plan
    if (
      livePlanReproducible &&
      canonicalJson(planIndexOf(prepared.plan)) !== canonicalJson(planIndex)
    ) {
      throw new Error(`${dir}: plan-index.json does not match the plan the manifest pins`)
    }
    notes.push({ fixture: name, livePlanReproducible })
    const testFields = new Map<string, JsonObject>()
    for (const g of prepared.ir.testGroups) {
      for (const t of g.tests) testFields.set(`${g.tgId}/${t.tcId}`, t.fields)
    }
    out.push({
      name,
      schemaId: manifest.schemaId,
      vsId: manifest.vsId,
      bundleManifestSha256: await sha256Hex(manifestText),
      planIndex,
      testFields,
      reference,
      publicInputs: identifyKnownFixture(prepared.promptSha256) !== null,
    })
  }
  return out
}

export const loadTargetInputs = (runDir: string): TargetInput[] => {
  const declared = readJson(path.join(runDir, 'targets.json')) as { targets: DeclaredTarget[] }
  const byId = new Map(declared.targets.map((d) => [d.id, d]))
  return XPLAT_TARGETS.map((target) => {
    const d = byId.get(target.id) ?? { id: target.id, status: 'not run' as const }
    const fixtures: TargetInput['fixtures'] = {}
    for (const name of FIXTURE_NAMES) {
      const dir = path.join(runDir, 'targets', target.id, name)
      const files = ['response.json', 'evidence.json', 'execution-environment.json']
      if (!files.every((f) => existsSync(path.join(dir, f)))) {
        fixtures[name] = undefined
        continue
      }
      fixtures[name] = {
        responseText: readFileSync(path.join(dir, 'response.json'), 'utf8'),
        evidence: readJson(path.join(dir, 'evidence.json')),
        environment: readJson(path.join(dir, 'execution-environment.json')),
      }
    }
    return { target, declared: d, fixtures }
  })
}

export const replayHint =
  (runDir: string) =>
  (target: string, fixture: string): string[] => [
    `# regenerate + verify the bundle: npx tsx scripts/acvp-xplat-wasm.ts --run ${runDir} --verify-bundles-only`,
    `# re-run this target: see ${runDir}/README.md (target ${target}), fixture ${fixture}`,
    `# recompare: npx tsx scripts/acvp-xplat-compare.ts --run ${runDir}`,
  ]

export interface GeneratedRun {
  files: Map<string, string>
  output: CompareOutput
}

/** Compare a run dir and render every generated file (matrix + divergences) in memory. */
export const generateRun = async (
  repoRoot: string,
  runDir: string,
  runId: string,
  notes: FixtureLoadNote[] = []
): Promise<GeneratedRun> => {
  const fixtures = await loadFixtureRefs(repoRoot, runDir, notes)
  const output = await compareTargets(runId, fixtures, loadTargetInputs(runDir), replayHint(runDir))
  const files = new Map<string, string>()
  files.set('matrix.json', `${JSON.stringify(output.matrix, null, 2)}\n`)
  files.set('matrix.md', renderMatrixMarkdown(output.matrix))
  for (const d of output.divergences) files.set(d.file, `${JSON.stringify(d.doc, null, 2)}\n`)
  return { files, output }
}

const listFiles = (dir: string, base = dir): string[] =>
  existsSync(dir)
    ? readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
        e.isDirectory()
          ? listFiles(path.join(dir, e.name), base)
          : [path.relative(base, path.join(dir, e.name))]
      )
    : []

/** Write the rendered files; stale divergence files from a previous compare are removed. */
export const writeRun = (runDir: string, rendered: GeneratedRun): void => {
  const divDir = path.join(runDir, 'divergences')
  if (existsSync(divDir)) rmSync(divDir, { recursive: true })
  for (const [rel, text] of rendered.files) {
    const p = path.join(runDir, rel)
    mkdirSync(path.dirname(p), { recursive: true })
    writeFileSync(p, text)
  }
}

/** --check: every generated file must equal the committed one, and no extra divergence file may exist. */
export const checkRun = (runDir: string, rendered: GeneratedRun): string[] => {
  const problems: string[] = []
  for (const [rel, text] of rendered.files) {
    const p = path.join(runDir, rel)
    if (!existsSync(p)) problems.push(`${rel} missing`)
    else if (readFileSync(p, 'utf8') !== text) problems.push(`${rel} is stale`)
  }
  for (const rel of listFiles(path.join(runDir, 'divergences'))) {
    const full = path.join('divergences', rel)
    if (!rendered.files.has(full))
      problems.push(`${full} is not produced by the current comparison`)
  }
  return problems
}
