// SPDX-License-Identifier: GPL-3.0-only
/**
 * execTourConfig — the Executive Overview walkthrough definition.
 *
 * The tour is a phase-major SINGLE PASS through the real program (p0 → verify-close,
 * plus the spanning Foundations band between p4 and p5 — WP2.4, 07182026: previously
 * the one phase this file skipped, contradicting the claim below), board-decisions-
 * first. It is a WALKTHROUGH, not a maturity climb: it reaches the player's
 * queue-exhaustion `done`, never the maturity-based win. Consumed by
 * `autoRunWalkthroughQueue` (simAutoRun) and the player's `walkthrough` mode.
 *
 * DEEP stages dwell and reveal real board documents (each generated by an activity
 * step, so the doc exists to reveal). LIGHT stages show one hand-picked step, quickly.
 * Every phase is visited once — none skipped — so the maturity story can't lie.
 *
 * Locked decisions: see the `project_exec_walkthrough_build` memory.
 */
import type { PhaseId } from '@/data/frameworkPhases'
import type { ExecutiveDocumentType } from '@/services/storage/types'
import type { StepKind } from '@/simulation'

export type TourConceptId =
  | 'hndl'
  | 'mosca'
  | 'hybrid'
  | 'two-track'
  | 'tnfl'
  | 'crypto-agility'
  | 'urgency-drivers'
  | 'cbom-fields'
  | 'weakest-domain-maturity'
  | 'kpi-pack'
  | 'readiness'
  | 'incident-response'

/**
 * A hand-picked representative step for a LIGHT stage, matched in the phase tree by
 * kind + its identifier. Auto-picking "the first step" fails (e.g. p6 has no level-1
 * band), so light stages carry an explicit pick.
 */
export interface TourLightStep {
  kind: StepKind
  /** The step's identifier: moduleId (learn), refId (reference), catalogId (catalog). */
  ref: string
}

export interface TourStage {
  phase: PhaseId
  depth: 'deep' | 'light'
  /** DEEP only: board documents to reveal; each MUST be produced by an activity step. */
  revealArtifacts?: ExecutiveDocumentType[]
  /** LIGHT only: the single hand-picked step to show. */
  lightStep?: TourLightStep
  /** Concept peeks surfaced when this phase opens (anchored to the phase boundary).
   *  Array — a phase boundary can introduce more than one concept (e.g. p0 pairs
   *  TNFL with the framework's own urgency-drivers framing). Each fires once,
   *  in array order, then never again (seenConceptPeeks). */
  conceptCards?: TourConceptId[]
}

/**
 * The locked stage order + depth (board-decisions-first, ~20 min balanced).
 * Order is program order; pilots (p5) and infrastructure (p6) kept separate.
 */
export const EXEC_TOUR_STAGES: readonly TourStage[] = [
  {
    phase: 'p0',
    depth: 'deep',
    // Order follows the real Phase 0 activity sequence (see simTree.p0): the four
    // financial-justification docs are Activity 0.2 (Build the Budget Structure);
    // program-charter and board-deck are Activity 0.4 (Draft the Program Charter) —
    // the charter formalizes the case the budget docs just built, and the board
    // pitch follows the charter. Previously program-charter was listed first,
    // ahead of the case that justifies it — fixed 07042026.
    revealArtifacts: [
      'cost-model-comparison',
      'roi-model',
      'breach-scenario',
      'cost-of-inaction',
      'program-charter',
      'board-deck',
    ],
    // TNFL is paired with HNDL from Activity 0.1 onward (and shown in the KPI
    // ribbon from the first screen) but wasn't in the concept system at all
    // before 07082026 — added here so it's introduced the same way HNDL/Mosca
    // are, right where the tour first shows it. urgency-drivers (07182026,
    // completeness gap-closing) names the framework's own four current-state
    // drivers (0.1's `do` text already states them verbatim) as their own peek,
    // rather than leaving them as prose only.
    conceptCards: ['tnfl', 'urgency-drivers'],
  },
  { phase: 'p1', depth: 'light', lightStep: { kind: 'learn', ref: 'data-asset-sensitivity' } },
  // cbom-fields (07182026, completeness gap-closing): the 5-field CBOM record
  // (algorithm, key size, protocol, library, owner) was named in 2.2's `do`
  // text but never had its own peek.
  {
    phase: 'p2',
    depth: 'light',
    lightStep: { kind: 'learn', ref: 'cbom' },
    conceptCards: ['cbom-fields'],
  },
  { phase: 'p3', depth: 'deep', revealArtifacts: ['risk-register'] },
  {
    phase: 'p4',
    depth: 'deep',
    revealArtifacts: ['migration-roadmap', 'kpi-dashboard'],
    conceptCards: ['two-track'],
  },
  // Foundations (WP2.4) — the spanning band was previously the only phase the
  // tour skipped, contradicting this file's own "every phase is visited once —
  // none skipped" claim above. Placed here (governance beat, between the
  // roadmap and pilots) because Foundations gates the compliance/agility
  // maturity domains that P5 execution depends on. kpi-dashboard is ALSO
  // revealed at p4 (the roadmap's own KPI baseline) — revealing it again here,
  // in Foundations' own home context, is intentional: the same real artifact,
  // shown where it's actually owned (see REVEAL INVARIANT in
  // walkthroughQueue.test.ts — kpi-dashboard has a generating step in BOTH
  // phases' trees, so this isn't a dangling reference).
  {
    phase: 'foundations',
    depth: 'deep',
    revealArtifacts: ['kpi-dashboard'],
    // weakest-domain-maturity + kpi-pack (07182026, educational-value gap-closing):
    // both were named in Foundations' own tree prose (the seven-domain listing and
    // the KPI-pack learn step) but never had their own peek — added alongside the
    // existing crypto-agility concept rather than left as prose only.
    conceptCards: ['crypto-agility', 'weakest-domain-maturity', 'kpi-pack'],
  },
  {
    phase: 'p5',
    depth: 'light',
    lightStep: { kind: 'learn', ref: 'hybrid-crypto' },
    conceptCards: ['hybrid'],
  },
  { phase: 'p6', depth: 'light', lightStep: { kind: 'learn', ref: 'pki-workshop' } },
  { phase: 'p7', depth: 'light', lightStep: { kind: 'learn', ref: 'vendor-risk' } },
  {
    phase: 'verify-close',
    depth: 'deep',
    revealArtifacts: ['migration-verification'],
    // 07-29 review G-M1 — the one lifecycle topic the tour never named:
    // what happens when an algorithm breaks AFTER the program closes.
    conceptCards: ['incident-response'],
  },
]

/** Concept peeks shown at the very start (threat + deadline math), before p0. */
export const EXEC_TOUR_OPENING_CONCEPTS: readonly TourConceptId[] = ['hndl', 'mosca']

export interface TourConcept {
  id: TourConceptId
  title: string
  /** Where the plain-language body comes from; 'inline' bodies are authored here. */
  source: 'guidedDef' | 'inline'
  /** Title keyword to resolve the GUIDED_DEFS entry (source === 'guidedDef'), matched
   *  case-insensitively — reuses the tour's existing plain-English definitions (no drift). */
  key?: string
  /** Authored body (source === 'inline'). Fact-free: no dates/numbers (those come from live components). */
  inline?: string
}

/** Concept content, reusing the existing plain-English GUIDED_DEFS where they exist (no drift). */
export const EXEC_TOUR_CONCEPTS: Record<TourConceptId, TourConcept> = {
  hndl: { id: 'hndl', title: 'Harvest now, decrypt later', source: 'guidedDef', key: 'HNDL' },
  mosca: { id: 'mosca', title: 'Mosca’s inequality', source: 'guidedDef', key: 'Mosca' },
  hybrid: { id: 'hybrid', title: 'Hybrid vs pure', source: 'guidedDef', key: 'hybrid' },
  tnfl: { id: 'tnfl', title: 'Trust now, forge later', source: 'guidedDef', key: 'TNFL' },
  'two-track': {
    id: 'two-track',
    title: 'Two tracks: confidentiality and integrity',
    source: 'inline',
    inline:
      'The roadmap runs two parallel tracks — protecting confidential data (key exchange) and protecting trust in signatures — because they use different algorithms and move on different timelines.',
  },
  'crypto-agility': {
    id: 'crypto-agility',
    title: 'Crypto-agility',
    source: 'guidedDef',
    key: 'crypto-agility',
  },
  'urgency-drivers': {
    id: 'urgency-drivers',
    title: 'Four urgency drivers, not a Q-Day countdown',
    source: 'inline',
    inline:
      'The business case rests on four concrete, current drivers — not a speculative future date: regulatory & compliance deadlines, Harvest-Now-Decrypt-Later exposure, Trust-Now-Forge-Later exposure, and client/investor/insurer expectations. Any one of the four can justify starting now.',
  },
  'cbom-fields': {
    id: 'cbom-fields',
    title: 'The 5-field CBOM record',
    source: 'inline',
    inline:
      'A Cryptography Bill of Materials record is only useful if it answers five things per instance: which algorithm, what key size, which protocol carries it, which library implements it, and who owns it. A name and a checkbox aren’t enough to act on.',
  },
  'weakest-domain-maturity': {
    id: 'weakest-domain-maturity',
    title: 'Maturity = your weakest domain',
    source: 'inline',
    inline:
      'Overall program maturity isn’t an average across domains — it’s the lowest of them. A program that’s Advanced everywhere except vendor engagement is only as mature as its vendor engagement, the same way a chain is only as strong as its weakest link.',
  },
  'kpi-pack': {
    id: 'kpi-pack',
    title: 'The board KPI pack',
    source: 'inline',
    inline:
      'A small, standing set of numbers a board can track quarter over quarter — coverage, pace against plan, vendor commitments — backed by an evidence dossier so each number has a receipt behind it, not just a self-reported status.',
  },
  readiness: {
    id: 'readiness',
    title: 'Grounded readiness',
    source: 'inline',
    inline:
      'A connection only counts as migrated when BOTH gates pass: you’ve done enough execution work to unlock it, AND you’ve chosen a real strategy (hybrid or pure) for it. A choice with no work, or work with no choice, counts for nothing — and the denominator is every vulnerable connection, so links with no PQC path yet hold this below 100% on purpose.',
  },
  'incident-response': {
    id: 'incident-response',
    title: 'Compromise response: swap, don’t scramble',
    source: 'inline',
    inline:
      'Verification closes the program, but algorithms keep aging after it. If one is broken — or a CRQC lands earlier than modeled — the rehearsed response is substitution, not a new program: the CBOM shows where the algorithm lives, the abstraction layer lets you swap it, and the incident playbook drives revocation and disclosure order. Your SOC watches for the trigger; the crypto-agility drill makes the swap a routine update instead of an emergency.',
  },
}

/**
 * Optional reveal one-liner overrides. Reveal text defaults to the matching business
 * tool's description (via ARTIFACT_TYPE_TO_TOOL_ID). All seven reveal types currently
 * resolve to a tool with a description, so this is empty; add an entry only when a
 * description reads poorly at the reveal moment. Any entry must stay fact-free.
 */
export const EXEC_TOUR_REVEAL_BLURBS: Partial<Record<ExecutiveDocumentType, string>> = {}

/** Every artifact type the tour reveals (for the queue-builder invariant + tests). */
export const EXEC_TOUR_REVEAL_TYPES: readonly ExecutiveDocumentType[] = EXEC_TOUR_STAGES.flatMap(
  (s) => s.revealArtifacts ?? []
)
