// SPDX-License-Identifier: GPL-3.0-only
/**
 * execTourConfig — the Executive Overview walkthrough definition.
 *
 * The tour is a phase-major SINGLE PASS through the real program (p0 → verify-close),
 * board-decisions-first. It is a WALKTHROUGH, not a maturity climb: it reaches the
 * player's queue-exhaustion `done`, never the maturity-based win. Consumed by
 * `autoRunWalkthroughQueue` (simAutoRun) and the player's `walkthrough` mode.
 *
 * DEEP stages dwell and reveal real board documents (each generated by an activity
 * step, so the doc exists to reveal). LIGHT stages show one hand-picked step, quickly.
 * Every phase is visited once — none skipped — so the maturity story can't lie.
 *
 * Locked decisions: see the `project_exec_walkthrough_build` memory.
 */
import type { PhaseId } from '@/data/frameworkPhases'
import type { ExecutiveDocumentType } from '@/services/storage/types'
import type { StepKind } from '@/simulation'

export type TourConceptId = 'hndl' | 'mosca' | 'hybrid' | 'two-track' | 'tnfl'

/**
 * A hand-picked representative step for a LIGHT stage, matched in the phase tree by
 * kind + its identifier. Auto-picking "the first step" fails (e.g. p6 has no level-1
 * band), so light stages carry an explicit pick.
 */
export interface TourLightStep {
  kind: StepKind
  /** The step's identifier: moduleId (learn), refId (reference), catalogId (catalog). */
  ref: string
}

export interface TourStage {
  phase: PhaseId
  depth: 'deep' | 'light'
  /** DEEP only: board documents to reveal; each MUST be produced by an activity step. */
  revealArtifacts?: ExecutiveDocumentType[]
  /** LIGHT only: the single hand-picked step to show. */
  lightStep?: TourLightStep
  /** A concept peek surfaced when this phase opens (anchored to the phase boundary). */
  conceptCard?: TourConceptId
}

/**
 * The locked stage order + depth (board-decisions-first, ~20 min balanced).
 * Order is program order; pilots (p5) and infrastructure (p6) kept separate.
 */
export const EXEC_TOUR_STAGES: readonly TourStage[] = [
  {
    phase: 'p0',
    depth: 'deep',
    // Order follows the real Phase 0 activity sequence (see simTree.p0): the four
    // financial-justification docs are Activity 0.2 (Build the Budget Structure);
    // program-charter and board-deck are Activity 0.4 (Draft the Program Charter) —
    // the charter formalizes the case the budget docs just built, and the board
    // pitch follows the charter. Previously program-charter was listed first,
    // ahead of the case that justifies it — fixed 07042026.
    revealArtifacts: [
      'cost-model-comparison',
      'roi-model',
      'breach-scenario',
      'cost-of-inaction',
      'program-charter',
      'board-deck',
    ],
    // TNFL is paired with HNDL from Activity 0.1 onward (and shown in the KPI
    // ribbon from the first screen) but wasn't in the concept system at all
    // before 07082026 — added here so it's introduced the same way HNDL/Mosca
    // are, right where the tour first shows it.
    conceptCard: 'tnfl',
  },
  { phase: 'p1', depth: 'light', lightStep: { kind: 'learn', ref: 'data-asset-sensitivity' } },
  { phase: 'p2', depth: 'light', lightStep: { kind: 'learn', ref: 'cbom' } },
  { phase: 'p3', depth: 'deep', revealArtifacts: ['risk-register'] },
  {
    phase: 'p4',
    depth: 'deep',
    revealArtifacts: ['migration-roadmap', 'kpi-dashboard'],
    conceptCard: 'two-track',
  },
  {
    phase: 'p5',
    depth: 'light',
    lightStep: { kind: 'learn', ref: 'hybrid-crypto' },
    conceptCard: 'hybrid',
  },
  { phase: 'p6', depth: 'light', lightStep: { kind: 'learn', ref: 'pki-workshop' } },
  { phase: 'p7', depth: 'light', lightStep: { kind: 'learn', ref: 'vendor-risk' } },
  { phase: 'verify-close', depth: 'deep', revealArtifacts: ['migration-verification'] },
]

/** Concept peeks shown at the very start (threat + deadline math), before p0. */
export const EXEC_TOUR_OPENING_CONCEPTS: readonly TourConceptId[] = ['hndl', 'mosca']

export interface TourConcept {
  id: TourConceptId
  title: string
  /** Where the plain-language body comes from; 'inline' bodies are authored here. */
  source: 'guidedDef' | 'inline'
  /** Title keyword to resolve the GUIDED_DEFS entry (source === 'guidedDef'), matched
   *  case-insensitively — reuses the tour's existing plain-English definitions (no drift). */
  key?: string
  /** Authored body (source === 'inline'). Fact-free: no dates/numbers (those come from live components). */
  inline?: string
}

/** Concept content, reusing the existing plain-English GUIDED_DEFS where they exist (no drift). */
export const EXEC_TOUR_CONCEPTS: Record<TourConceptId, TourConcept> = {
  hndl: { id: 'hndl', title: 'Harvest now, decrypt later', source: 'guidedDef', key: 'HNDL' },
  mosca: { id: 'mosca', title: 'Mosca’s inequality', source: 'guidedDef', key: 'Mosca' },
  hybrid: { id: 'hybrid', title: 'Hybrid vs pure', source: 'guidedDef', key: 'hybrid' },
  tnfl: { id: 'tnfl', title: 'Trust now, forge later', source: 'guidedDef', key: 'TNFL' },
  'two-track': {
    id: 'two-track',
    title: 'Two tracks: confidentiality and integrity',
    source: 'inline',
    inline:
      'The roadmap runs two parallel tracks — protecting confidential data (key exchange) and protecting trust in signatures — because they use different algorithms and move on different timelines.',
  },
}

/**
 * Optional reveal one-liner overrides. Reveal text defaults to the matching business
 * tool's description (via ARTIFACT_TYPE_TO_TOOL_ID). All seven reveal types currently
 * resolve to a tool with a description, so this is empty; add an entry only when a
 * description reads poorly at the reveal moment. Any entry must stay fact-free.
 */
export const EXEC_TOUR_REVEAL_BLURBS: Partial<Record<ExecutiveDocumentType, string>> = {}

/** Every artifact type the tour reveals (for the queue-builder invariant + tests). */
export const EXEC_TOUR_REVEAL_TYPES: readonly ExecutiveDocumentType[] = EXEC_TOUR_STAGES.flatMap(
  (s) => s.revealArtifacts ?? []
)
