// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 07062026_3 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'foundations',
  generated: '07062026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator: 'Cross-cutting capabilities recognized; ad hoc maturity awareness; no KPIs',
      activities: [
        {
          id: 'F.1',
          title: 'Establish GRC & Assess Program Maturity',
          do: 'Stand up the risk-appetite statement and KRI cascade; run (or refine) your PQC assessment — program maturity is derived from your progress, overall = weakest domain.',
          output: 'GRC structure & maturity baseline',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: PQC GRC (risk appetite & KRIs)',
              to: '/learn/pqc-grc',
              moduleId: 'pqc-grc',
            },
            {
              kind: 'reference',
              label: 'Run / refine your PQC assessment',
              to: '/assess',
              refId: 'assess-engine',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        'Maturity self-assessment run; KPI baseline set; crypto-agility plan and skills plan drafted',
      activities: [
        {
          id: 'F.2',
          title: 'Baseline Metrics & the Evidence Dossier',
          do: 'Set the board KPI pack (Coverage/Trust/Inventory/Vendors/Agility) and the operational KPIs, and start the audit/litigation evidence dossier.',
          output: 'KPI baseline & evidence dossier',
          steps: [
            {
              kind: 'activity',
              label: 'Baseline the board KPI pack',
              to: '/business/tools/kpi-dashboard',
              artifactType: 'kpi-dashboard',
            },
            {
              kind: 'activity',
              label: 'Track operational KPIs & the evidence dossier',
              to: '/business/tools/kpi-tracker',
              artifactType: 'kpi-tracker',
            },
          ],
        },
        {
          id: 'F.3',
          title: 'Build Crypto-Agility & the Team',
          do: 'Adopt crypto-agility as the end-state architecture and staff the program with the framework core roles (≈1 FTE per 500 CBOM instances).',
          output: 'Crypto-agility roadmap & skills plan',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Crypto-Agility as end-state',
              to: '/learn/crypto-agility',
              moduleId: 'crypto-agility',
            },
            {
              kind: 'learn',
              label: 'Learn: skills & team structure (roles, FTE sizing)',
              to: '/learn/skills-team-structure',
              moduleId: 'skills-team-structure',
            },
            {
              kind: 'activity',
              label: 'Plan skills & team',
              to: '/business/tools/skills-team-plan',
              artifactType: 'skills-team-plan',
            },
          ],
          deepDive: [
            {
              kind: 'learn',
              label: 'Deep dive — Learn: Cryptographic APIs & Developer Languages',
              to: '/learn/crypto-dev-apis',
              moduleId: 'crypto-dev-apis',
            },
            {
              kind: 'learn',
              label: 'Deep dive — Learn: SLH-DSA',
              to: '/learn/slh-dsa',
              moduleId: 'slh-dsa',
            },
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: SLH-DSA sign & verify',
              to: '/playground/slh-dsa',
              workshopId: 'slh-dsa',
            },
            {
              kind: 'learn',
              label: 'Deep dive — Learn: Stateful Hash Signatures',
              to: '/learn/stateful-signatures',
              moduleId: 'stateful-signatures',
            },
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: LMS/HSS stateful signatures',
              to: '/playground/lms-hss',
              workshopId: 'lms-hss',
            },
            {
              kind: 'workshop',
              label: 'Deep dive — Practice: OpenSSL Studio',
              to: '/playground/openssl-studio',
              workshopId: 'openssl-studio',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator:
        'KPIs reported to the board; regulatory/standards alignment maintained; crypto-agility OKRs tracked; evidence dossier kept',
      activities: [
        {
          id: 'F.4',
          title: 'Maintain Regulatory & Standards Alignment',
          do: 'Keep the phase-to-regulation map current across the 2026–2035 deadline squeeze and the standards bodies that bind you.',
          output: 'Regulatory & standards alignment map',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Standards, Certification & Compliance Bodies',
              to: '/learn/standards-bodies',
              moduleId: 'standards-bodies',
            },
            {
              kind: 'reference',
              label: 'Maintain the regulatory & standards alignment map',
              to: '/compliance',
              refId: 'compliance',
            },
          ],
          deepDive: [
            {
              kind: 'learn',
              label: 'Deep dive — Learn: PQC Candidates & Lifecycle',
              to: '/learn/pqc-candidates',
              moduleId: 'pqc-candidates',
            },
          ],
        },
      ],
    },
    {
      level: 4,
      indicator:
        'Foundations run as BAU; migration verification & program-closure standard applied; algorithm changes are routine',
      activities: [
        {
          id: 'F.5',
          title: 'Migration Verification & Program Closure',
          do: 'Apply the 5-point verification evidence standard, decommission classical material, and hand the capability to funded BAU owners.',
          output: 'Verification record & BAU handover',
          steps: [
            {
              kind: 'reference',
              label: 'Apply the 5-point verification standard in the Verification & Closure phase',
              to: '/report',
              refId: 'report',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Declare the migration "done" on milestones',
      why: 'Closing on milestone completion instead of verified posture — without verification evidence (observed negotiation, negative testing, dossier) the migration is a belief, not a fact.',
    },
    {
      title: 'Orphan the capabilities at closure',
      why: 'Treating closure as end-of-funding rather than handover — CBOM, discovery and vendor governance decay within quarters without funded BAU owners.',
    },
    {
      title: 'Skip the maturity baseline (run no assessment)',
      why: 'Without the weakest-link view you over-report progress and miss the gating domain that actually constrains readiness.',
    },
  ],
}

export default TREE
