// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 06142026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p1',
  gate: {
    id: 'G1',
    criterion: '≥70% Tier-1 systems inventoried',
  },
  generated: '06142026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator:
        'Partial manual inventory of obvious systems (web servers, VPN); CMDB-only asset register; no continuous discovery',
      activities: [
        {
          id: '1.0',
          title: 'Risk-Driven Scoping — Decide What to Inventory First',
          do: 'Apply 80/20 prioritization to pick the Tier-1 systems and assign discovery priority tiers.',
          output: 'Risk-driven scoping document',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Data & Asset Sensitivity',
              to: '/learn/data-asset-sensitivity',
              moduleId: 'data-asset-sensitivity',
            },
            {
              kind: 'reference',
              label: 'Run the scoping assessment engine',
              to: '/assess',
              refId: 'assess-engine',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        'Risk-driven scoping complete; automated discovery deployed on Priority A systems; ≥70% Tier-1 coverage; inventory is queryable; classical vulnerabilities being remediated; multiple asset data sources cross-referenced',
      activities: [
        {
          id: '1.1',
          title: 'Establish Three Parallel Inventory Tracks',
          do: 'Stand up Track A (crypto usage), Track B (data classification), Track C (systems/assets).',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Cryptographic Management Modernization',
              to: '/learn/crypto-mgmt-modernization',
              moduleId: 'crypto-mgmt-modernization',
            },
          ],
        },
        {
          id: '1.2',
          title: 'Deploy Cryptographic Discovery — Layered Approach',
          do: 'Deploy discovery across network, code, config, runtime, and manual layers.',
          output: 'Layered discovery deployment',
          steps: [
            {
              kind: 'reference',
              label: 'Browse the Migrate discovery catalog',
              to: '/migrate',
              refId: 'migrate',
            },
            {
              kind: 'activity',
              label: 'Run the Management-Tools Audit',
              to: '/business/tools/management-tools-audit',
              artifactType: 'management-tools-audit',
            },
          ],
        },
        {
          id: '1.3',
          title: 'Map the Cryptographic Estate',
          do: 'Document algorithm, key size, protocol, library, cert, owner and vulnerability for each instance.',
          output: 'Cryptographic asset inventory',
          steps: [
            {
              kind: 'activity',
              label: 'Draw the crypto architecture diagram',
              to: '/business/tools/crypto-architecture-diagram',
              artifactType: 'crypto-architecture',
            },
          ],
        },
        {
          id: '1.4–1.5',
          title: 'Address Asset Discovery & Integrate Existing Data Sources',
          do: 'Cross-reference CMDB, ITAM, cloud APIs, CT logs, BIA and certificate data for coverage.',
          output: 'Cross-referenced asset coverage',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Platform Engineering for PQC',
              to: '/learn/platform-eng-pqc',
              moduleId: 'platform-eng-pqc',
            },
            {
              kind: 'reference',
              label: 'Mine the Library for asset data',
              to: '/library',
              refId: 'library',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator:
        '≥90% coverage; continuous discovery in CI/CD and passive monitoring; integrated with CMDB, SBOM, BIA, and certificate management; change management integration live; crypto champions designated; alerting framework operational',
      activities: [
        {
          id: '1.6',
          title: 'Establish Continuous Discovery',
          do: 'Wire discovery into CI/CD and passive monitoring with quarterly rescans and tiered alerting.',
          output: 'Continuous discovery operating model',
          steps: [
            {
              kind: 'activity',
              label: 'Set up the Crypto-Vulnerability Watch',
              to: '/business/tools/crypto-vulnerability-watch',
              artifactType: 'crypto-vulnerability-watch',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Run an interview-only inventory',
      why: 'Application owners cannot reliably self-report crypto usage without automated discovery.',
    },
    {
      title: 'Keep the inventory in a spreadsheet',
      why: 'Static spreadsheets go stale within weeks without an automated, queryable refresh.',
    },
    {
      title: 'Wait for 100% completeness',
      why: 'Completeness is asymptotic; 80/20 risk-driven scoping delivers actionable results sooner.',
    },
    {
      title: 'Skip OT and embedded systems',
      why: 'The hardest systems to discover guarantee later surprises when excluded.',
    },
    {
      title: 'Trust a single discovery tool',
      why: 'No one tool covers all five discovery layers; multiple categories are required.',
    },
    {
      title: 'Treat discovery as one-time',
      why: 'Discovery is a permanent capability; disbanding the team staling the CBOM within six months.',
    },
  ],
}

export default TREE
