// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 06142026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p0',
  gate: {
    id: 'G0',
    criterion: 'Mandate signed',
  },
  generated: '06142026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator: 'Quantum risk acknowledged; no formal program',
      activities: [
        {
          id: '0.1',
          title: 'Frame the Business Case',
          do: 'Structure the executive argument around regulatory deadlines, HNDL and TNFL exposure, and stakeholder expectations.',
          output: 'Executive business case',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: PQC Business Case',
              to: '/learn/pqc-business-case',
              moduleId: 'pqc-business-case',
            },
            {
              kind: 'reference',
              label: 'Check the CRQC threat horizon',
              to: '/threats',
              refId: 'threats',
            },
            {
              kind: 'activity',
              label: 'Model the migration ROI',
              to: '/business/tools/roi-calculator',
              artifactType: 'roi-model',
            },
          ],
        },
        {
          id: '0.2',
          title: 'Assess Data & Asset Sensitivity',
          do: 'Discover the critical assets, classify their sensitivity and confidentiality horizon — the exposure that justifies the budget the board will commit.',
          output: 'Initial scoping & asset-sensitivity assessment',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Data & Asset Sensitivity',
              to: '/learn/data-asset-sensitivity',
              moduleId: 'data-asset-sensitivity',
            },
            {
              kind: 'reference',
              label: 'Run the assessment engine',
              to: '/assess',
              refId: 'assess-engine',
            },
            {
              kind: 'activity',
              label: 'Produce the scoping & asset assessment',
              to: '/business/tools/initial-scoping',
              artifactType: 'initial-scoping',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator: 'Charter approved; QRPM appointed; Year 1 budget secured',
      activities: [
        {
          id: '0.3',
          title: 'Identify Applicable Standards, Certifications & Compliance',
          do: 'Map the regulations, standards and certifications that bind this org (and their deadlines) into a compliance & regulatory strategy.',
          output: 'Compliance & regulatory strategy',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Compliance & Regulatory Strategy',
              to: '/learn/compliance-strategy',
              moduleId: 'compliance-strategy',
            },
            {
              kind: 'reference',
              label: 'Map applicable regs & certifications',
              to: '/compliance',
              refId: 'compliance',
            },
          ],
        },
        {
          id: '0.4',
          title: 'Assess the Quantum Risk',
          do: 'Score the quantum risk to the discovered assets (HNDL + TNFL) to size and prioritise the program.',
          output: 'Quantum risk assessment',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: PQC Risk Management',
              to: '/learn/pqc-risk-management',
              moduleId: 'pqc-risk-management',
            },
            {
              kind: 'activity',
              label: 'Run a CRQC scenario',
              to: '/business/tools/crqc-scenario',
              artifactType: 'crqc-scenario',
            },
          ],
        },
        {
          id: '0.5',
          title: 'Establish Governance & Draft the Charter',
          do: 'Define roles (Sponsor, SteerCo, QRPM), the RACI, and the one-page program charter.',
          output: 'Governance structure & approved charter',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: PQC Governance & Policy',
              to: '/learn/pqc-governance',
              moduleId: 'pqc-governance',
            },
            {
              kind: 'activity',
              label: 'Build the RACI matrix',
              to: '/business/tools/raci-builder',
              artifactType: 'raci-matrix',
            },
            {
              kind: 'activity',
              label: 'Produce the Program Charter',
              to: '/business/tools/program-charter',
              artifactType: 'program-charter',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator: 'Multi-year budget committed; SteerCo operational; scoping assessment complete',
      activities: [
        {
          id: '0.6',
          title: 'Secure the Board Mandate & Multi-Year Budget',
          do: 'Pitch the board with the exposure-justified ask and secure multi-year funding and cryptography policy.',
          output: 'Signed mandate & multi-year budget',
          steps: [
            {
              kind: 'activity',
              label: 'Pitch the board for budget',
              to: '/business/tools/board-pitch',
              artifactType: 'board-deck',
            },
            {
              kind: 'activity',
              label: 'Draft the cryptography policy',
              to: '/business/tools/policy-generator',
              artifactType: 'policy-draft',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Frame PQC as an innovation project',
      why: 'Treating migration as R&D instead of a governed program gets it deprioritized against operational work.',
    },
    {
      title: 'Commit only a single-year budget',
      why: 'One-year funding prevents realistic planning and talent retention over a 4–15 year program.',
    },
    {
      title: 'Leave business units off the SteerCo',
      why: 'Without business governance representation, workstream leads hit constant political resistance.',
    },
    {
      title: 'Delegate the program to vendors',
      why: 'Vendors execute on their own timelines, leaving you with no control over your migration.',
    },
    {
      title: 'Lock systems down prematurely',
      why: 'Knee-jerk restrictions burn operational goodwill without reducing HNDL risk.',
    },
  ],
}

export default TREE
