// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 06222026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'verify-close',
  gate: {
    id: 'G8',
    criterion: 'Verification complete; classical material decommissioned; closed to BAU',
  },
  generated: '06222026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator:
        'Closure discussed on milestones; no evidence standard applied; "done" is declared, not proven',
      activities: [
        {
          id: 'VC.1',
          title: 'Set the Verification Standard & Closure Plan',
          do: 'Adopt the 5-point migration-verification evidence standard and the program-closure record up front, so "done" means proven, not declared.',
          output: 'Verification standard & closure plan',
          steps: [
            {
              kind: 'reference',
              label: 'Reference: the program closure record & 5-point evidence standard',
              to: '/report',
              refId: 'report',
            },
            {
              kind: 'reference',
              label: 'Reference: closeout attestations & applicable mandates',
              to: '/compliance',
              refId: 'compliance',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        'Migration verified against the 5-point evidence standard; classical key material decommissioning logged (under the organization-defined key-destruction standard); program closure record produced',
      activities: [
        {
          id: 'VC.2',
          title: 'Assemble the Migration Evidence Dossier',
          do: 'Prove each migrated system against the evidence standard (observed PQC negotiation, negative testing, configuration attestation) and log classical key-material decommissioning under the organization-defined key-destruction standard (with destruction certificates for HSM-held keys).',
          output: 'Migration-verification evidence dossier',
          steps: [
            {
              kind: 'activity',
              label: 'Assemble the evidence dossier & log decommissioning',
              to: '/business/tools/migration-verification',
              artifactType: 'migration-verification',
            },
            {
              kind: 'activity',
              label: 'Run the closure audit-readiness checklist',
              to: '/business/tools/audit-checklist',
              artifactType: 'audit-checklist',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator:
        'Independent verification of Tier-1 systems; crypto-agility/rollback drill evidenced; executive-sponsor sign-off; BAU handover funded',
      activities: [
        {
          id: 'VC.3',
          title: 'Independent Verification & Sign-off',
          do: 'Independently verify Tier-1 systems, evidence the crypto-agility / rollback drill, and obtain executive-sponsor closure sign-off with a funded BAU handover.',
          output: 'Independent verification & signed closure',
          steps: [
            {
              kind: 'activity',
              label: 'Export the final CBOM as durable closure evidence',
              to: '/business/tools/crypto-cbom-builder',
              artifactType: 'crypto-cbom',
            },
            {
              kind: 'reference',
              label: 'Reference: key decommissioning & evidence standards',
              to: '/library',
              refId: 'library',
            },
          ],
        },
      ],
    },
    {
      level: 4,
      indicator:
        'Verification & closure run as BAU; evidence dossier continuously maintained; decommissioning and attestations folded into posture monitoring',
      activities: [
        {
          id: 'VC.4',
          title: 'Run Verification & Closure as BAU',
          do: 'Fold verification, decommissioning and attestations into the continuous posture-monitoring loop so algorithm changes and re-verification are routine.',
          output: 'BAU verification & posture monitoring',
          steps: [
            {
              kind: 'activity',
              label: 'Track post-closure crypto-posture KPIs as BAU',
              to: '/business/tools/kpi-tracker',
              artifactType: 'kpi-tracker',
            },
            {
              kind: 'reference',
              label: 'Reference: monitor the algorithm-transition landscape',
              to: '/algorithms?tab=transition',
              refId: 'algorithms-transition',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Declare the migration "done" on milestones',
      why: 'Closing on milestone completion instead of verified posture — without evidence (observed negotiation, negative testing, the dossier) the migration is a belief, not a fact, and an auditor asks for proof, not milestones.',
    },
    {
      title: 'Orphan the capabilities at closure',
      why: 'Treating closure as end-of-funding rather than a funded BAU handover — CBOM, discovery and vendor governance decay within quarters without owners.',
    },
    {
      title: 'Skip classical-key decommissioning',
      why: 'Leaving old classical keys and material live keeps the harvest-now-decrypt-later exposure open even after PQC is deployed — closure requires documented key-decommissioning evidence.',
    },
  ],
}

export default TREE
