// SPDX-License-Identifier: GPL-3.0-only
// Generated by scripts/ci/gen-tool-route-meta.ts — do not edit by hand.

export type ToolRouteKind = 'business-tool' | 'browser-tool' | 'sandbox-tool' | 'lab'

export interface ToolRouteMeta {
  path: string
  title: string
  description: string
  kind: ToolRouteKind
  index: boolean
  sourceGlobs: string[]
  contentRegion: string
}

export const TOOL_ROUTE_META: readonly ToolRouteMeta[] = [
  {
    path: '/business/tools/accelerated-execution-profile',
    title: 'Accelerated Execution Profile — PQC Business Tool | PQC Today',
    description:
      'Phase 4 Activity 4.7 — a pre-drafted contingency package (trigger conditions, compressed sequence, pre-approved risk acceptances, emergency resource…',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/audit-checklist',
    title: 'Audit Readiness Checklist — PQC Business Tool | PQC Today',
    description:
      'Multi-section audit checklist covering inventory, policy, controls, and documentation',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/board-pitch',
    title: 'Board Pitch Builder — PQC Business Tool | PQC Today',
    description: 'Build board-ready investment proposals with executive summary and budget request',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/breach-simulator',
    title: 'Breach Scenario Simulator — PQC Business Tool | PQC Today',
    description:
      'Compare classical vs quantum-enabled breach cost (per-event and annual expected loss) with HNDL exposure',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/cloud-responsibility-matrix',
    title: 'Cloud Responsibility Matrix — PQC Business Tool | PQC Today',
    description:
      'Architect + compliance-lead matrix from CSWP.39 §6.4 - per-asset-class shared-responsibility model across IaaS / PaaS / SaaS / FaaS, with PQC availability…',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/compliance-checklist',
    title: 'Compliance Checklist — PQC Business Tool | PQC Today',
    description:
      'Per-framework PQC compliance checklist seeded from your starred frameworks and assessment',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/compliance-timeline',
    title: 'Compliance Timeline Builder — PQC Business Tool | PQC Today',
    description: 'Plot framework milestones, deadlines, and dependencies on a single timeline',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/contract-clause',
    title: 'Contract Clause Generator — PQC Business Tool | PQC Today',
    description: 'Generate PQC-ready contract clauses for vendor agreements',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/cost-model-explorer',
    title: 'Cost Model Explorer — PQC Business Tool | PQC Today',
    description:
      'Compare the six PQC costing-model families on one scenario, with a live Monte Carlo run',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/cost-of-inaction',
    title: 'Cost of Inaction Analyzer — PQC Business Tool | PQC Today',
    description:
      'Model the discounted cost of delaying PQC migration — breach exposure, HNDL residual, and regulatory penalties',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/crqc-scenario',
    title: 'CRQC Scenario Planner — PQC Business Tool | PQC Today',
    description: 'Plan for cryptographically relevant quantum computer threat scenarios',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/crypto-api-refactor-audit',
    title: 'Crypto API Refactor Audit — PQC Business Tool | PQC Today',
    description:
      'Architect + senior-developer audit from CSWP.39 §4.1 - grades current crypto-agility state and emits a phased refactor checklist with language-specific…',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/crypto-architecture-diagram',
    title: 'Crypto Architecture Diagram — PQC Business Tool | PQC Today',
    description:
      'Document apps, libraries, HSMs, protocols, key stores, and CAs with their dependencies; renders as a Mermaid diagram',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/crypto-cbom-builder',
    title: 'Crypto BOM (CBOM) Builder — PQC Business Tool | PQC Today',
    description:
      'Build a CBOM slice from an SBOM, library posture, or HSM inventory; feeds the Assets pipeline',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/crypto-vulnerability-watch',
    title: 'Crypto Vulnerability Watch — PQC Business Tool | PQC Today',
    description:
      'NIST NVD CVE digest for the products on your /migrate selection, joined via CPE — the top CVEs per product by severity from the current snapshot',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/data-at-rest-strategy',
    title: 'Data-at-Rest Strategy — PQC Business Tool | PQC Today',
    description:
      'Phase 5 Activity 5.6 — per-store data-at-rest decision (re-encrypt under PQC keys, PQC key-wrap, crypto-shred, delete, or accept & monitor), recorded back…',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/deployment-playbook',
    title: 'Deployment Playbook — PQC Business Tool | PQC Today',
    description: 'Generate deployment playbooks with rollback procedures and validation steps',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/hybrid-transition-planner',
    title: 'Hybrid Transition Planner — PQC Business Tool | PQC Today',
    description:
      'Architect-facing decision tree from CSWP.39 §3.2.4 - pick traditional+PQC, PQC+PQC, pure PQC, or crypto-gateway pathway with concrete algorithm pairings',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/infra-modernization-planner',
    title: 'Infrastructure Modernization Planner — PQC Business Tool | PQC Today',
    description:
      'Phase 6 deliverable — consolidates the PKI modernization plan, HSM/KMS upgrade schedule, network/middlebox compatibility report, and PQC capacity plan into…',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/initial-scoping',
    title: 'Initial Scoping Assessment — PQC Business Tool | PQC Today',
    description:
      'Phase 0 first-cut scope — top-20 in-scope systems, an estate-size estimate, and the top-10 vendor dependencies; seedable from your /migrate selection',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/kpi-dashboard',
    title: 'KPI Dashboard Builder — PQC Business Tool | PQC Today',
    description: 'Build KPI dashboards for tracking PQC migration metrics and progress',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/kpi-tracker',
    title: 'KPI Tracker Template — PQC Business Tool | PQC Today',
    description: 'Track migration KPIs with configurable metrics and reporting templates',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/management-tools-audit',
    title: 'Management Tools Audit — PQC Business Tool | PQC Today',
    description:
      'Audit your discovery, assessment, configuration, and enforcement tooling stack — feeds the Information Repository per CSWP.39 §5',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/migration-verification',
    title: 'Migration Verification & Closure — PQC Business Tool | PQC Today',
    description:
      "Prove migration with the framework's 5-point evidence standard, log classical-key decommissioning (SP 800-88), and record program closure & BAU handover",
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/mti-negotiator',
    title: 'MTI Negotiator — PQC Business Tool | PQC Today',
    description:
      'Protocol-designer + architect decision tool from CSWP.39 §3.1.1 - picks Mandatory-to-Implement signature / KEM / hash plus alternates from audience…',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/policy-generator',
    title: 'Policy Template Generator — PQC Business Tool | PQC Today',
    description: 'Generate cryptographic algorithm, key management, vendor, and migration policies',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/program-charter',
    title: 'Program Charter — PQC Business Tool | PQC Today',
    description:
      'Phase 0 mandate artifact — sponsor sign-off, Steering Committee, QRPM appointment, governance cadence, and the multi-year budget commitment',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/raci-builder',
    title: 'RACI Builder — PQC Business Tool | PQC Today',
    description: 'Build RACI matrices for 10 PQC activities across 6 organizational roles',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/refresh-cycle-alignment',
    title: 'Refresh-Cycle Alignment — PQC Business Tool | PQC Today',
    description:
      'Phase 4 Activity 4.3 — maps PQC migration tasks onto already-funded infrastructure refresh programs (data center, SD-WAN, cloud, PKI, HSM, vendor renewals)…',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/risk-register',
    title: 'Risk Register Builder — PQC Business Tool | PQC Today',
    description:
      'Build a PQC risk register with current algorithm, threat vector, likelihood, impact and mitigation',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/risk-treatment-plan',
    title: 'Risk Heatmap & Treatment Plan — PQC Business Tool | PQC Today',
    description: 'Visualise residual risk and draft treatment strategies per risk category',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/roadmap-builder',
    title: 'Roadmap Builder — PQC Business Tool | PQC Today',
    description:
      'Build a two-track migration roadmap (key-exchange/HNDL ∥ signatures-PKI/TNFL) on the 8-phase spine, with gates G0–G6 (+ G8 at closure) and milestone…',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/roi-calculator',
    title: 'ROI Calculator — PQC Business Tool | PQC Today',
    description:
      'Calculate migration ROI with breach avoidance, compliance savings, and payback period',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/skills-team-plan',
    title: 'Skills & Team Plan — PQC Business Tool | PQC Today',
    description:
      'Foundations staffing plan — core roles + FTE from the framework role model, the 1-FTE-per-500-instances sizing heuristic, and build / borrow / buy per role',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/stakeholder-comms',
    title: 'Stakeholder Comms Planner — PQC Business Tool | PQC Today',
    description: 'Plan stakeholder communication strategies for PQC migration programs',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/supply-chain-matrix',
    title: 'Supply Chain Risk Matrix — PQC Business Tool | PQC Today',
    description: 'Assess supply chain risks with dependency mapping and impact analysis',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/business/tools/vendor-scorecard',
    title: 'Vendor Scorecard Builder — PQC Business Tool | PQC Today',
    description: 'Create vendor assessment scorecards for PQC readiness evaluation',
    kind: 'business-tool',
    index: true,
    sourceGlobs: [
      'src/components/BusinessCenter/businessToolsRegistry.tsx',
      'src/components/BusinessCenter/BusinessToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/api-security-jwt',
    title: 'API Security & JWT Workshop — PQC Crypto Lab | PQC Today',
    description:
      'Sign JWTs with ML-DSA-44/65/87, SLH-DSA, and composite ML-DSA-65+Ed25519 using real @noble/post-quantum or softhsmv3 PKCS#11.',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/bitcoin-flow',
    title: 'Bitcoin Transaction — PQC Crypto Lab | PQC Today',
    description: 'secp256k1 ECDSA keypair, SHA256 + RIPEMD160, transaction signing',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/cacp',
    title: 'Crypto-Agility Control Plane — KMIP Policy Lab | PQC Today',
    description:
      'Test KMIP crypto-agility policies and observe cryptographic operations switch to post-quantum controls in an interactive browser lab.',
    kind: 'lab',
    index: true,
    sourceGlobs: ['src/components/Playground/kmip', 'src/wasm/kmip'],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/cacp-kmip',
    title: 'KMIP Control Plane — PQC Crypto Lab | PQC Today',
    description:
      'In-browser KMIP 3.0 control plane + softhsmrustv3 HSM, compiled to WebAssembly. Load a crypto-agility policy (pqc.yaml / classical.yaml), run key lifecycle…',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/cert-capacity',
    title: 'Cert Capacity Calculator — PQC Crypto Lab | PQC Today',
    description:
      'Model storage, bandwidth, and CPU impact of migrating your PKI to ML-DSA — adjust cert counts and renewal cadence.',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/digital-id',
    title: 'EUDI Wallet Architecture — PQC Crypto Lab | PQC Today',
    description:
      'Complete digital identity lifecycle: Wallet, PID Issuance, Attestation, RP Verification, and QES Provider.',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/docker',
    title: 'PQC Docker Sandbox — Full-Fidelity Integration Lab | PQC Today',
    description:
      'Understand the requirements and workflows for PQC Today container scenarios that exercise full cryptographic applications outside the browser.',
    kind: 'lab',
    index: true,
    sourceGlobs: ['src/components/Playground/DockerPlaygroundView.tsx'],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/drbg-demo',
    title: 'SP 800-90A DRBG — PQC Crypto Lab | PQC Today',
    description:
      'Interactive HMAC_DRBG (SHA-256) state machine — Instantiate, Generate, Reseed as specified in NIST SP 800-90A Rev.',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/email-signing',
    title: 'S/MIME & CMS Workshop — PQC Crypto Lab | PQC Today',
    description:
      'Real OpenSSL 3.6 WASM CMS SignedData sign+verify (ML-DSA-44/65/87, SLH-DSA, RSA-PSS) and ML-KEM-768 AuthEnvelopedData encrypt+decrypt.',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/entropy-test',
    title: 'Entropy Testing — PQC Crypto Lab | PQC Today',
    description:
      'Separate groups: monobit, runs and chi-squared visual checks; the SP 800-90B repetition-count and adaptive-proportion health tests (on samples treated as…',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/envelope-encrypt',
    title: 'Envelope Encryption — PQC Crypto Lab | PQC Today',
    description: 'ML-KEM + AES key wrap in a KMS envelope encryption pattern',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/firmware-signing',
    title: 'Firmware Signing — PQC Crypto Lab | PQC Today',
    description:
      'UEFI secure boot firmware signing and verification with ML-DSA-44/65/87 or SLH-DSA (defaults to ML-DSA-65)',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/hd-wallet',
    title: 'HD Wallet Derivation — PQC Crypto Lab | PQC Today',
    description: 'BIP39 mnemonic + BIP32/SLIP-0010 multi-coin HD key derivation',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/hsm',
    title: 'PKCS#11 HSM Playground — SoftHSM in WebAssembly | PQC Today',
    description:
      'Explore PKCS#11 v3.2 operations, post-quantum keys and dual-engine validation using SoftHSM compiled to WebAssembly.',
    kind: 'lab',
    index: true,
    sourceGlobs: ['src/components/Playground/HsmPlayground.tsx', 'src/components/Playground/hsm'],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/hsm-capacity',
    title: 'HSM Capacity Calculator — PQC Crypto Lab | PQC Today',
    description:
      'Size your HSM fleet for the top 10 enterprise use cases. Compare classical vs next-gen PQC HSM, tune per-algorithm TPS, and see whether your fleet is…',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/hybrid-certs',
    title: 'Hybrid Certificates — PQC Crypto Lab | PQC Today',
    description:
      'Generate and compare eight X.509 hybrid and post-quantum certificate formats via SoftHSM PKCS#11 + real DER encoding',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/hybrid-encrypt',
    title: 'Hybrid KEM + ECDH — PQC Crypto Lab | PQC Today',
    description: 'ML-KEM + X25519 ECDH + HKDF hybrid encryption pipeline',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/hybrid-sigs',
    title: 'Hybrid Signature Spectrums — PQC Crypto Lab | PQC Today',
    description:
      'Live concatenation, nesting, and Silithium (fused Fiat-Shamir) — from no non-separability to SNS',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/interactive',
    title: 'Interactive PQC Playground — Live Cryptography | PQC Today',
    description:
      'Generate keys, encapsulate secrets, sign messages and compare post-quantum algorithms in a browser-based WebAssembly cryptography playground.',
    kind: 'lab',
    index: true,
    sourceGlobs: ['src/components/Playground/PlaygroundView.tsx'],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/kdf-derivation',
    title: 'SP 800-108 KDF — PQC Crypto Lab | PQC Today',
    description:
      'NIST SP 800-108 counter-mode key derivation — applicable to KEM secrets, PSK, QKD, and password-derived keys',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/lms-hss',
    title: 'Stateful Hash Signatures — PQC Crypto Lab | PQC Today',
    description: 'LMS and XMSS stateful signature trees using SoftHSMv3',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/merkle-proof',
    title: 'Merkle Tree Workshop — PQC Crypto Lab | PQC Today',
    description:
      'Build trees, generate inclusion proofs, verify with tamper detection, compare PQC cert sizes, and simulate Certificate Transparency logs',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/mls-group-messaging',
    title: 'MLS Group Messaging — PQC Crypto Lab | PQC Today',
    description:
      'RFC 9420 TreeKEM visualizer + PKCS#11 provider architecture. Add/remove members, trace re-keyed nodes on each Commit, and see how openmls_pqctoday_crypto…',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/openssl-studio',
    title: 'OpenSSL Studio — PQC Crypto Lab | PQC Today',
    description:
      'Full OpenSSL v3.6.3 environment: keygen, certificates, CSR, KEM, signing, KDF, encryption — all via WASM',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/pki-enrollment',
    title: 'PKI Enrollment (EST + CMP) — PQC Crypto Lab | PQC Today',
    description:
      'RFC 7030 EST + RFC 4210/9810 CMP — generate an ML-DSA-65 key, run CMP IR against an in-WASM mock CA, verify the issued cert.',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/pki-workshop',
    title: 'PKI Workshop — PQC Crypto Lab | PQC Today',
    description:
      'Build a full certificate chain hands-on: CSR → Root CA → cert issuance → parsing → CRL',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/pqc-ssh-sim',
    title: 'PQC SSH Simulator — PQC Crypto Lab | PQC Today',
    description:
      'Full OpenSSH 10.x handshake in WASM: mlkem768x25519-sha256 KEX + ssh-mldsa-65 host auth + publickey userauth backed by softhsmv3 PKCS#11.',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/qrng-demo',
    title: 'QRNG Demo — PQC Crypto Lab | PQC Today',
    description:
      'Simulation — no QRNG hardware involved. Compares a simulated QRNG sample (crypto.getRandomValues() output, not a quantum source), live Web Crypto output and…',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/rng-demo',
    title: 'Random Generation — PQC Crypto Lab | PQC Today',
    description: 'Web Crypto + OpenSSL DRBG random generation with statistical analysis',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-ab-handshake-bench',
    title: 'A/B TLS Handshake Benchmark — PQC Crypto Lab | PQC Today',
    description:
      'Measure concurrent TLS 1.3 handshake throughput with Apache Bench against ephemeral nginx (session resumption OFF, so...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-api-security-jwt',
    title: 'Post-Quantum JWT Identity Constraints — PQC Crypto Lab | PQC Today',
    description:
      'Sign JSON Web Tokens with ML-DSA-65 using OpenSSL raw signatures and measure the impact on HTTP request-header limits...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-browser-tls',
    title: 'Browser ML-KEM Handshake — PQC Crypto Lab | PQC Today',
    description:
      'Drive headless Chromium to connect to the nginx TLS endpoint and compare a classical X25519 handshake vs a hybrid X25...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-cbom-compliance',
    title: 'CBOM Compliance Audit — PQC Readiness Scoring — PQC Crypto Lab | PQC Today',
    description:
      'Generate real classical, hybrid and post-quantum key material, identify each asset algorithm with OpenSSL, and emit i...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-cert-validation',
    title: 'Certificate Chain Validation — PQC Crypto Lab | PQC Today',
    description:
      'Verify ML-DSA-65 certificate chains end-to-end — from Root CA through Intermediate to Leaf — validating that PQC sign...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-cloud-kms',
    title: 'Cloud KMS Key Wrapping — PQC Crypto Lab | PQC Today',
    description:
      'Demonstrate ML-KEM-768 key encapsulation with OpenSSL 3.6 — the key-wrapping pattern cloud KMS services (AWS, Azure, ...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-database-postgres',
    title: 'PostgreSQL TLS Hardening — PQC Crypto Lab | PQC Today',
    description:
      'Migrate PostgreSQL client-server TLS from a classical RSA-2048 cert + prime256v1 ECDHE to an ML-DSA-65 server cert ov...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-firmware-hss',
    title: 'Firmware Verification (HSS) — PQC Crypto Lab | PQC Today',
    description:
      'Secure IoT endpoint firmware updates with NIST SP 800-208 Stateful Hash-Based Signatures (HSS/LMS), generated and ver...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-hsm-perf-bench',
    title: 'HSM Performance Benchmark — PQC Crypto Lab | PQC Today',
    description:
      'Measure real PKCS#11 v3.2 throughput and latency across 26 algorithms by default (16 signature, 10 key-establishment;...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-hybrid-certs',
    title: 'Hybrid Certificate Formats — PQC Crypto Lab | PQC Today',
    description:
      'Generate and compare all 7 PQC X.509 certificate formats — Pure ML-DSA, Pure SLH-DSA, Composite, Alt-Sig/Catalyst, Re...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-iot-mqtt',
    title: 'Lightweight MQTT Telemetry — PQC Crypto Lab | PQC Today',
    description:
      'Run a real Mosquitto 2.1.2 TLS broker (built against OpenSSL 3.6) and compare a classical ECDSA-P256 / secp256r1 arm ...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-migration-impact',
    title: 'Migration Impact Analysis — PQC Crypto Lab | PQC Today',
    description:
      'Measure the real-world performance impact of migrating from classical to PQC TLS — handshake latency, certificate siz...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-osslsigncode',
    title: 'Code Signing (osslsigncode) — PQC Crypto Lab | PQC Today',
    description:
      'Sign Windows PE binaries using osslsigncode with classical RSA vs post-quantum ML-DSA-65, demonstrating the supply-ch...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-pki',
    title: 'Enterprise PKI Chains — PQC Crypto Lab | PQC Today',
    description:
      'Build a hierarchical PQC Certificate Authority with OpenSSL 3.6 — a mixed-algorithm chain: Root CA (SLH-DSA-SHA2-128s...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-pqctoday-kmip',
    title: 'PQCToday KMIP 3.0 KMS — PQC Crypto Lab | PQC Today',
    description:
      'Drive a real crypto-agile KMIP key lifecycle with pqctoday-kmip (Rust, MIT) backed by softhsmrustv3 — CreateKeyPair →...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-sequoia',
    title: 'PGP Code Signing (Sequoia) — PQC Crypto Lab | PQC Today',
    description:
      'Produce a real RFC 9580 v6 OpenPGP signature with an ML-DSA-65 + Ed25519 composite key (public-key-algorithm 30, RFC ...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-smime',
    title: 'Secure Email (S/MIME) — PQC Crypto Lab | PQC Today',
    description:
      'Compare legacy RSA-2048 S/MIME encryption sequences against open-source ML-DSA & ML-KEM cryptographic integration pro...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-sops',
    title: 'GitOps Secrets (SOPS) — PQC Crypto Lab | PQC Today',
    description:
      'Encrypt GitOps secrets with SOPS + age using the X-Wing hybrid KEM (X25519 + ML-KEM-768) via the age-plugin-pqctoday ...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-ssh',
    title: 'SSH PQC Authentication + KEX — PQC Crypto Lab | PQC Today',
    description:
      'Full post-quantum SSH session: host and client auth keys (ML-DSA-65) held in softhsmv3 via PKCS#11 v3.2, combined wit...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-stepca',
    title: 'Automated CA (Step-CA) — PQC Crypto Lab | PQC Today',
    description:
      'Deploy Smallstep step-ca with PQC-enabled certificate issuance, contrasting classical ECDSA-P256 automated certificat...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-supply-chain-signing',
    title: 'Supply Chain Signing — Quantum-Safe Container Provenance — PQC Crypto Lab | PQC Today',
    description:
      'Demonstrate post-quantum software signing with the forked Sigstore cosign (v3.0.6 + ML-DSA-65) — sign a manifest with...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-tls',
    title: 'OpenSSL TLS 1.3 + Composite Cert — PQC Crypto Lab | PQC Today',
    description:
      'Execute OpenSSL TLS 1.3 handshakes with configurable certificate formats. In pure-ML-DSA mode the server cert is an M...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-tpm-pqc-migration',
    title: 'TPM 2.0 → PQC Migration — PQC Crypto Lab | PQC Today',
    description:
      'Walk the TCG TPM 2.0 V1.85 key hierarchy and see the concrete cost of migrating each key role (EK / SRK / AIK / IDevI...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/sbx-vpn',
    title: 'Quantum-Resistant VPN — PQC Crypto Lab | PQC Today',
    description:
      'Secure site-to-site IPsec routing hidden behind SoftHSMv3 IKEv2 Key Exchanges, contrasting classical Diffie-Hellman v...',
    kind: 'sandbox-tool',
    index: true,
    sourceGlobs: [
      'src/data/sandboxScenarios.ts',
      'src/components/Playground/SandboxScenarioEmbed.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/slh-dsa',
    title: 'SLH-DSA Sign & Verify — PQC Crypto Lab | PQC Today',
    description: 'All 12 FIPS 205 parameter sets with pre-hash support',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/solana-flow',
    title: 'Solana Transaction — PQC Crypto Lab | PQC Today',
    description: 'Ed25519 keypair generation and transaction signing',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/source-combining',
    title: 'Source Combining — PQC Crypto Lab | PQC Today',
    description:
      'Two simulated raw sources: SP 800-90B health tests before conditioning, SP 800-90C concatenation (XOR, hash and HMAC as educational variants)…',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/suci-flow',
    title: '5G SUCI Construction — PQC Crypto Lab | PQC Today',
    description:
      'Subscriber identity concealment for 5G: ECDH + ANSI X9.63-KDF + AES (Profiles A/B), plus a post-quantum Profile C using ML-KEM in hybrid and pure modes',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/tee-channel',
    title: 'TEE-HSM Secure Channel — PQC Crypto Lab | PQC Today',
    description: 'Build a TEE-to-HSM trusted channel with ML-DSA + ML-KEM + AES wrap',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/tls-simulator',
    title: 'TLS 1.3 Simulator — PQC Crypto Lab | PQC Today',
    description:
      'Client–server TLS 1.3 handshake simulator: configure cipher suites, key exchange groups, mTLS, PQC and hybrid certificates',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/token-migration',
    title: 'Multi-Algorithm Signing — PQC Crypto Lab | PQC Today',
    description: 'Compare ML-DSA, ECDSA, and RSA signing in a token migration workflow',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/tpm-playground',
    title: 'TPM 2.0 PQC Playground — PQC Crypto Lab | PQC Today',
    description:
      'Execute raw TPM 2.0 Post-Quantum operations entirely in the browser using the WebAssembly-compiled pqctpm emulator.',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
  {
    path: '/playground/vpn-sim',
    title: 'PQC VPN Simulator — PQC Crypto Lab | PQC Today',
    description:
      'Full IKEv2 handshake in WASM with PKCS#11 crypto routed through softhsmv3. Inspect live C_* calls, ECDH key exchange, and PSK authentication between…',
    kind: 'browser-tool',
    index: true,
    sourceGlobs: [
      'src/components/Playground/workshopRegistry.tsx',
      'src/components/Playground/PlaygroundToolRoute.tsx',
    ],
    contentRegion: '#main-content',
  },
]
