// SPDX-License-Identifier: GPL-3.0-only
/**
 * generate-validation-counts — derive every public validation count from the
 * vector manifest (plan WS-B, B-4) so a hand-maintained number (the deck's
 * "13 NIST files" against a real 15) cannot drift again.
 *
 *   npx tsx scripts/generate-validation-counts.ts          # (re)write the JSON
 *   npx tsx scripts/generate-validation-counts.ts --check  # exit 1 if stale (gate)
 *
 * Output: src/data/validation/validation-counts.generated.json — deterministic
 * (no timestamps), keyed to a formatting-independent hash of the manifest.
 * The deck, data sheet and UI should read their numbers from this file.
 */
import { createHash } from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { EVIDENCE_CLASS_IDS, UNVERIFIED } from '../src/data/validation/evidenceClasses'
import {
  effectiveCase,
  type ValidationCaseManifest,
} from '../src/data/validation/validationCaseManifest'

export const COUNTS_REL = 'src/data/validation/validation-counts.generated.json'
const MANIFEST_REL = 'src/data/validation/vector-manifest.json'

const CLASS_KEYS = [...EVIDENCE_CLASS_IDS, UNVERIFIED] as const

function zeroByClass(): Record<string, number> {
  return Object.fromEntries(CLASS_KEYS.map((k) => [k, 0]))
}

function sortKeys<T>(o: Record<string, T>): Record<string, T> {
  return Object.fromEntries(Object.entries(o).sort(([a], [b]) => a.localeCompare(b)))
}

export function computeCounts(manifest: ValidationCaseManifest) {
  const filesByClass = zeroByClass()
  const activeCasesByClass = zeroByClass()
  const byAlgorithm: Record<string, { cases: number; byClass: Record<string, number> }> = {}
  const transformations: Record<string, number> = {}
  const gaps: Record<string, number> = {}
  const copiesByKind: Record<string, number> = {}
  let activeFiles = 0
  let quarantinedFiles = 0
  let activeCases = 0
  let quarantinedCases = 0
  let nistCases = 0
  const byExpectation = { positive: 0, negative: 0 }

  for (const f of manifest.files) {
    filesByClass[f.evidenceClass] += 1
    if (f.status === 'active') activeFiles += 1
    else quarantinedFiles += 1
    for (const g of f.publishabilityGaps) gaps[g] = (gaps[g] ?? 0) + 1
    for (const c of f.copies) copiesByKind[c.kind] = (copiesByKind[c.kind] ?? 0) + 1
    const lineageById = new Map(f.lineage.map((l) => [l.id, l]))
    for (const c of f.cases) {
      const eff = effectiveCase(f, c)
      if (eff.status !== 'active') {
        quarantinedCases += 1
        continue
      }
      activeCases += 1
      activeCasesByClass[eff.evidenceClass] += 1
      byExpectation[c.expectation] += 1
      if (eff.evidenceClass === 'nist-acvp-reference-sample') nistCases += 1
      const alg = (byAlgorithm[c.algorithm.name] ??= { cases: 0, byClass: {} })
      alg.cases += 1
      alg.byClass[eff.evidenceClass] = (alg.byClass[eff.evidenceClass] ?? 0) + 1
      const types = new Set(
        (c.lineage ?? [])
          .flatMap((id) => lineageById.get(id)?.transformations ?? [])
          .map((t) => t.type)
      )
      for (const t of types) transformations[t] = (transformations[t] ?? 0) + 1
    }
  }

  for (const a of Object.values(byAlgorithm)) a.byClass = sortKeys(a.byClass)

  return {
    vectorFiles: {
      total: manifest.files.length,
      active: activeFiles,
      quarantined: quarantinedFiles,
    },
    nistReferenceSampleFileCount: filesByClass['nist-acvp-reference-sample'],
    nistReferenceSampleCaseCount: nistCases,
    filesByClass,
    cases: {
      total: activeCases + quarantinedCases,
      active: activeCases,
      quarantined: quarantinedCases,
    },
    activeCasesByClass,
    activeCasesByExpectation: byExpectation,
    byAlgorithm: sortKeys(byAlgorithm),
    activeCasesByTransformation: sortKeys(transformations),
    filesWithPublishabilityGap: sortKeys(gaps),
    declaredCopiesByKind: sortKeys(copiesByKind),
  }
}

export function renderCounts(manifest: ValidationCaseManifest): string {
  const canonical = createHash('sha256').update(JSON.stringify(manifest)).digest('hex')
  const out = {
    $comment:
      'GENERATED by scripts/generate-validation-counts.ts from src/data/validation/vector-manifest.json — do not edit; run npm run gen:validation-counts.',
    schemaVersion: manifest.schemaVersion,
    manifestCanonicalSha256: canonical,
    ...computeCounts(manifest),
  }
  return JSON.stringify(out, null, 2) + '\n'
}

function main(): void {
  const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
  const manifest = JSON.parse(
    fs.readFileSync(path.join(root, MANIFEST_REL), 'utf8')
  ) as ValidationCaseManifest
  const next = renderCounts(manifest)
  const outAbs = path.join(root, COUNTS_REL)
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(outAbs) ? fs.readFileSync(outAbs, 'utf8') : ''
    if (cur !== next) {
      console.error(
        `[gen:validation-counts] ${COUNTS_REL} is stale — run npm run gen:validation-counts and commit it`
      )
      process.exit(1)
    }
    console.warn('[gen:validation-counts] OK — counts match the manifest')
    return
  }
  fs.writeFileSync(outAbs, next)
  console.warn(`[gen:validation-counts] wrote ${COUNTS_REL}`)
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main()
}
