// SPDX-License-Identifier: GPL-3.0-only
/**
 * sync-sandbox-scenarios.ts
 *
 * Regenerates src/data/sandboxScenarios.ts from the sandbox source of truth
 * (pqctoday-sandbox/ui/src/data/scenarios.ts). The hub only carries a thin
 * projection of each scenario; this script is the single place that defines
 * the projection so the two repos cannot drift silently again.
 *
 * Projection rules (see SandboxScenario in the emitted file):
 *   id         <- scenario.id
 *   title      <- scenario.title
 *   emoji      <- scenario.icon
 *   useCase    <- scenario.useCase            (verbatim — the honest backend prose)
 *   algorithms <- scenario.badges[].label     (the algorithms actually exercised)
 *   difficulty <- scenario.difficulty
 *   trackId    <- the LEARNING_TRACK that lists the scenario
 *   tool.name  <- scenario.tool.name          (clean name; version lives in the
 *                                               backend and drifts, so it is omitted)
 *   tool.url   <- scenario.tool.url
 *
 * A scenario is emitted only when it is (a) not deprecated and (b) referenced by
 * exactly one learning track — mirroring the backend's "only real-PQC scenarios
 * appear in the hub" rule. Deprecated scenarios (e.g. dnssec) and orphaned
 * scenarios are dropped.
 *
 * Usage:  npm run sync:sandbox            (writes the file)
 *         npm run sync:sandbox -- --check (fails if the file is out of date)
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import prettier from 'prettier'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUT_PATH = resolve(__dirname, '../src/data/sandboxScenarios.ts')

// Dynamic import so a missing sibling checkout (common in the hub's own CI) is a
// clean skip rather than a hard module-resolution crash — that lets the --check
// gate run wherever the sandbox repo is present and no-op where it isn't.
let LEARNING_TRACKS: typeof import('../../pqctoday-sandbox/ui/src/data/scenarios').LEARNING_TRACKS
let SCENARIOS: typeof import('../../pqctoday-sandbox/ui/src/data/scenarios').SCENARIOS
try {
  const src = await import('../../pqctoday-sandbox/ui/src/data/scenarios')
  ;({ LEARNING_TRACKS, SCENARIOS } = src)
} catch {
  console.log(
    '⏭  sandbox source (../../pqctoday-sandbox/ui/src/data/scenarios) not found — skipping sandbox sync.'
  )
  process.exit(0)
}

type Difficulty = 'beginner' | 'intermediate' | 'advanced'

// scenarioId -> trackId (a scenario must belong to exactly one track to be shown)
const trackOfScenario = new Map<string, string>()
for (const track of LEARNING_TRACKS) {
  for (const id of track.scenarioIds) {
    if (!trackOfScenario.has(id)) trackOfScenario.set(id, track.id)
  }
}

const scenarioById = new Map(SCENARIOS.map((s) => [s.id, s]))

// Build the visible list in track order, then track.scenarioIds order — gives a
// stable, human-meaningful grouping in the generated file.
const visible: Array<{
  id: string
  title: string
  emoji: string
  useCase: string
  algorithms: string[]
  difficulty: Difficulty
  trackId: string
  tool: { name: string; url: string }
}> = []
const usedTrackIds = new Set<string>()

for (const track of LEARNING_TRACKS) {
  for (const id of track.scenarioIds) {
    const s = scenarioById.get(id)
    if (!s) {
      console.warn(`⚠️  track '${track.id}' references unknown scenario '${id}' — skipped`)
      continue
    }
    if (s.deprecated) continue
    if (!s.difficulty) {
      console.warn(`⚠️  scenario '${id}' has no difficulty — skipped`)
      continue
    }
    usedTrackIds.add(track.id)
    visible.push({
      id: s.id,
      title: s.title,
      emoji: s.icon,
      useCase: s.useCase,
      algorithms: s.badges.map((b) => b.label),
      difficulty: s.difficulty as Difficulty,
      trackId: track.id,
      tool: { name: s.tool.name, url: s.tool.url },
    })
  }
}

const tracks = LEARNING_TRACKS.filter((t) => usedTrackIds.has(t.id)).map((t) => ({
  id: t.id,
  label: t.label,
  subtitle: t.subtitle,
  difficulty: t.difficulty,
}))

const q = (s: string) => JSON.stringify(s)
const trackUnion = tracks.map((t) => q(t.id)).join(' | ')

const lines: string[] = []
lines.push('// SPDX-License-Identifier: GPL-3.0-only')
lines.push('// Generated by scripts/sync-sandbox-scenarios.ts — do not edit by hand.')
lines.push('// Source: pqctoday-sandbox/ui/src/data/scenarios.ts')
lines.push('// Regenerate with: npm run sync:sandbox')
lines.push('')
lines.push(`export type SandboxTrackId = ${trackUnion}`)
lines.push(`export type SandboxDifficulty = 'beginner' | 'intermediate' | 'advanced'`)
lines.push('')
lines.push('export interface SandboxScenario {')
lines.push('  id: string')
lines.push('  title: string')
lines.push('  emoji: string')
lines.push('  useCase: string')
lines.push('  algorithms: string[]')
lines.push('  difficulty: SandboxDifficulty')
lines.push('  trackId: SandboxTrackId')
lines.push('  tool: { name: string; url: string }')
lines.push('}')
lines.push('')
lines.push('export interface SandboxTrack {')
lines.push('  id: SandboxTrackId')
lines.push('  label: string')
lines.push('  subtitle: string')
lines.push('  difficulty: string')
lines.push('}')
lines.push('')
lines.push('export const SANDBOX_SCENARIOS: SandboxScenario[] = [')
for (const s of visible) {
  lines.push('  {')
  lines.push(`    id: ${q(s.id)},`)
  lines.push(`    title: ${q(s.title)},`)
  lines.push(`    emoji: ${q(s.emoji)},`)
  lines.push(`    useCase: ${q(s.useCase)},`)
  lines.push(`    algorithms: [${s.algorithms.map(q).join(', ')}],`)
  lines.push(`    difficulty: ${q(s.difficulty)},`)
  lines.push(`    trackId: ${q(s.trackId)},`)
  lines.push(`    tool: { name: ${q(s.tool.name)}, url: ${q(s.tool.url)} },`)
  lines.push('  },')
}
lines.push(']')
lines.push('')
lines.push('export const SANDBOX_TRACKS: SandboxTrack[] = [')
for (const t of tracks) {
  lines.push('  {')
  lines.push(`    id: ${q(t.id)},`)
  lines.push(`    label: ${q(t.label)},`)
  lines.push(`    subtitle: ${q(t.subtitle)},`)
  lines.push(`    difficulty: ${q(t.difficulty)},`)
  lines.push('  },')
}
lines.push(']')
lines.push('')

// Format with the repo's Prettier config so the generated file is byte-identical
// to what `prettier --write` would produce — otherwise --check would false-alarm
// on formatting differences rather than real data drift.
const prettierConfig = await prettier.resolveConfig(OUT_PATH)
const output = await prettier.format(lines.join('\n'), {
  ...prettierConfig,
  filepath: OUT_PATH,
  parser: 'typescript',
})

const check = process.argv.includes('--check')
if (check) {
  let current = ''
  try {
    current = readFileSync(OUT_PATH, 'utf8')
  } catch {
    /* missing file => out of date */
  }
  if (current.trim() !== output.trim()) {
    console.error(
      '✗ src/data/sandboxScenarios.ts is out of date with the sandbox source.\n' +
        '  Run `npm run sync:sandbox` and commit the result.'
    )
    process.exit(1)
  }
  console.log(
    `✓ sandboxScenarios.ts is in sync (${visible.length} scenarios, ${tracks.length} tracks)`
  )
} else {
  writeFileSync(OUT_PATH, output)
  console.log(
    `✓ wrote ${OUT_PATH}\n  ${visible.length} scenarios across ${tracks.length} tracks ` +
      `(dropped deprecated/orphaned).`
  )
}
