// SPDX-License-Identifier: GPL-3.0-only
//
// discoverHsmObjects — enumerate every PKCS#11 object on the current session
// and register any handle HsmContext doesn't already know about. Shared by
// HsmKeyTable's "Discover" button and the Learn tab's automatic per-step
// registration, so a PKCS#11 key never needs its own classification logic
// written twice.
import type { SoftHSMModule } from '@pqctoday/softhsm-wasm'
import { hsm_findAllObjects, hsm_getKeyAttributes } from '../../../wasm/softhsm'
import type { HsmContextValue, HsmFamily, HsmKey, HsmKeyRole } from '../hsm/HsmContext'

export const CKK_NAMES: Record<number, string> = {
  0x00: 'CKK_RSA',
  0x03: 'CKK_EC',
  0x10: 'CKK_GENERIC_SECRET',
  0x1f: 'CKK_AES',
  0x40: 'CKK_EC_EDWARDS',
  0x41: 'CKK_EC_MONTGOMERY',
  0x46: 'CKK_HSS',
  0x47: 'CKK_XMSS',
  0x48: 'CKK_XMSSMT',
  0x49: 'CKK_ML_KEM',
  0x4a: 'CKK_ML_DSA',
  0x4b: 'CKK_SLH_DSA',
}

const CKK_TO_FAMILY: Record<number, HsmFamily> = {
  0x00: 'rsa',
  0x03: 'ecdsa',
  0x10: 'hmac',
  0x1f: 'aes',
  0x40: 'eddsa',
  // 0x41 CKK_EC_MONTGOMERY (X25519/X448) is key agreement, not signing — it must
  // map to 'ecdh' to match what HsmKeyAgreementPanel registers directly. Without
  // this entry it fell through the `?? 'aes'` default below and every discovered
  // Montgomery key was silently filed as a symmetric AES key.
  0x41: 'ecdh',
  0x49: 'ml-kem',
  0x4a: 'ml-dsa',
  0x4b: 'slh-dsa',
  0x46: 'hss',
  0x47: 'xmss',
  0x48: 'xmss',
}

const CKO_TO_ROLE: Record<number, HsmKeyRole> = {
  0x02: 'public',
  0x03: 'private',
  0x04: 'secret',
}

/**
 * Finds every object on the given session's token and registers any handle
 * not already in `knownHandles` via `addKey`. Returns the number of newly
 * registered keys. The classification tables above (CKK_TO_FAMILY,
 * CKO_TO_ROLE) are the single source of truth for turning a raw PKCS#11
 * object into an `HsmKey` — every caller (the shared HsmContext session,
 * the Developer tab's own separately-slotted session) goes through this one
 * function so that classification is never written twice.
 */
function discoverObjectsOnSession(
  M: SoftHSMModule,
  hSession: number,
  knownHandles: ReadonlySet<number>,
  addKey: (key: HsmKey) => void
): number {
  const handles = hsm_findAllObjects(M, hSession, [])
  let added = 0
  for (const h of handles) {
    if (knownHandles.has(h)) continue
    try {
      const a = hsm_getKeyAttributes(M, hSession, h)
      const family: HsmFamily = a.ckKeyType !== null ? (CKK_TO_FAMILY[a.ckKeyType] ?? 'aes') : 'aes'
      const role: HsmKeyRole = a.ckClass !== null ? (CKO_TO_ROLE[a.ckClass] ?? 'secret') : 'secret'
      const typeName = a.ckKeyType !== null ? (CKK_NAMES[a.ckKeyType] ?? 'Unknown') : 'Unknown'
      // Prefer the object's real CKA_LABEL — set by most generators, and now
      // by hsm_generateECKeyPair too (previously silently dropped). Fall back
      // to a synthetic label only when the object genuinely has none (empty
      // string, e.g. imported without one) or the read failed.
      const label = a.ckLabel && a.ckLabel.length > 0 ? a.ckLabel : `${typeName} (discovered)`
      addKey({
        handle: h,
        family,
        role,
        label,
        generatedAt: new Date().toLocaleTimeString(),
      })
      added++
    } catch {
      // skip objects that can't be queried
    }
  }
  return added
}

/**
 * Finds every object on the current session's token and registers any
 * handle not already tracked in the key registry (e.g. keys generated by a
 * Learn-tab lesson step, which calls `hsm_generate*` directly rather than
 * going through `addHsmKey`). Returns the number of newly registered keys.
 *
 * Reads `hsm.hsmKeysRef` (not `hsm.hsmKeys`) so that calling this more than
 * once per tick — e.g. once per lesson step inside a "Run all" loop, with
 * no render in between — sees keys registered by the previous call instead
 * of a stale pre-loop snapshot, which would otherwise re-discover and
 * duplicate-register the same handle on every iteration.
 *
 * Uses `rawModuleRef` (no logging proxy), not `moduleRef` — this is registry
 * bookkeeping, not a lesson step, and its C_FindObjectsInit/Final bracket
 * (which would otherwise show up after literally every step, around nothing
 * visible in between) must never appear in a learner's call log.
 */
export const discoverHsmObjects = (hsm: HsmContextValue): number => {
  const M = hsm.rawModuleRef.current
  const hSession = hsm.hSessionRef.current
  if (!M || !hSession) return 0
  const knownHandles = new Set(hsm.hsmKeysRef.current.map((k) => k.handle))
  return discoverObjectsOnSession(M, hSession, knownHandles, hsm.addHsmKey)
}

/**
 * Same discovery/classification logic as `discoverHsmObjects`, but scoped to
 * an arbitrary already-open session rather than `HsmContext`'s own —
 * specifically for the Developer tab's separately-labeled/PIN'd slot
 * (`devSlot.ts`), which is deliberately isolated from `HsmContext.hSessionRef`
 * so a Developer-tab script can never log the rest of the HSM playground out
 * from under it. Caller owns the session's lifecycle (open before, close
 * after) — this function only scans and registers.
 */
export const discoverHsmObjectsOnSession = (
  M: SoftHSMModule,
  hSession: number,
  hsm: Pick<HsmContextValue, 'hsmKeysRef' | 'addHsmKey'>
): number => {
  const knownHandles = new Set(hsm.hsmKeysRef.current.map((k) => k.handle))
  return discoverObjectsOnSession(M, hSession, knownHandles, hsm.addHsmKey)
}
