// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 06152026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p5',
  gate: {
    id: 'G5',
    criterion: 'Pilots validated; wave migration underway',
  },
  generated: '06152026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator: 'Lab testing only; no production exposure',
      activities: [
        {
          id: '5.1',
          title: 'Select Pilot Targets',
          do: 'Pick 2–4 Tier-1 pilots with full control, measurable baselines and rollback capability.',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Hybrid Cryptography',
              to: '/learn/hybrid-crypto',
              moduleId: 'hybrid-crypto',
            },
            {
              kind: 'reference',
              label: 'Pick pilots from the Migrate catalog',
              to: '/migrate',
              refId: 'migrate',
            },
          ],
        },
        {
          id: '5.2',
          title: 'Design Hybrid Deployments',
          do: 'Design hybrid patterns (e.g. X25519+ML-KEM-768) and verify library readiness.',
          steps: [
            {
              kind: 'reference',
              label: 'Reference: which protocols have a PQC path',
              to: '/algorithms?tab=support',
              refId: 'algorithms-protocol-matrix',
            },
            {
              kind: 'learn',
              label: 'Learn: VPN/IPsec & SSH PQC patterns',
              to: '/learn/vpn-ssh-pqc',
              moduleId: 'vpn-ssh-pqc',
            },
            {
              kind: 'learn',
              label: 'Learn: code & firmware signing (Track B — integrity)',
              to: '/learn/code-signing',
              moduleId: 'code-signing',
            },
            {
              kind: 'activity',
              label: 'Plan the hybrid transition',
              to: '/business/tools/hybrid-transition-planner',
              artifactType: 'hybrid-transition',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        '2+ production pilots running with measured results; rollback procedures tested; validated patterns documented',
      activities: [
        {
          id: '5.3',
          title: 'Execute Pilots with Measurement',
          do: 'Run pilots against SLOs (latency, CPU, throughput), test rollback and validate compatibility.',
          output: 'Pilot results reports',
          steps: [
            {
              kind: 'workshop',
              label: 'Practice: measure the TLS 1.3 hybrid handshake',
              to: '/playground/tls-simulator',
              workshopId: 'tls-simulator',
            },
            {
              kind: 'activity',
              label: 'Draft a Deployment Playbook',
              to: '/business/tools/deployment-playbook',
              artifactType: 'deployment-playbook',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator:
        'Tier-1 internet-facing systems on hybrid/PQC; wave rollout underway for Tier-2; defense-in-depth measures (tokenization, AES-256, segmentation) deployed',
      activities: [
        {
          id: '5.4',
          title: 'Scale from Pilot to Production Through Waves',
          do: 'Execute a 6-wave rollout from lab to long tail with success criteria at each stage.',
          output: 'Wave deployment plan',
          steps: [
            {
              kind: 'activity',
              label: 'Negotiate the minimum-interop baseline',
              to: '/business/tools/mti-negotiator',
              artifactType: 'mti-negotiator',
            },
          ],
        },
        {
          id: '5.5–5.6',
          title: 'Defense-in-Depth & Data-at-Rest Strategy',
          do: 'Deploy tokenization, segmentation and AES-256 defaults; decide a per-store data-at-rest strategy.',
          output: 'Defense-in-depth & data-at-rest plan',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Confidential Computing & defense-in-depth',
              to: '/learn/confidential-computing',
              moduleId: 'confidential-computing',
            },
            {
              kind: 'learn',
              label: 'Learn: data-at-rest strategy & DB encryption',
              to: '/learn/database-encryption-pqc',
              moduleId: 'database-encryption-pqc',
            },
            {
              kind: 'workshop',
              label: 'Practice: PQC key-wrapping (envelope encryption)',
              to: '/playground/envelope-encrypt',
              workshopId: 'envelope-encrypt',
            },
            {
              kind: 'activity',
              label: 'Decide the per-store data-at-rest strategy',
              to: '/business/tools/data-at-rest-strategy',
              artifactType: 'data-at-rest-strategy',
            },
          ],
        },
      ],
    },
    {
      level: 4,
      indicator:
        'Estate-wide hybrid/PQC deployment substantially complete; transitioning selected systems from hybrid to PQC-only; crypto-agility demonstrated via algorithm-swap drill',
      activities: [
        {
          id: '5.7',
          title: 'AI-Assisted Migration (the gate that stays closed)',
          do: 'Use AI to triage and enrich, but keep full review rigor on AI-modified cryptographic code.',
          steps: [
            {
              kind: 'activity',
              label: 'Audit AI-assisted crypto refactors',
              to: '/business/tools/crypto-api-refactor-audit',
              artifactType: 'crypto-api-refactor',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Pilot the easy systems, not the important ones',
      why: 'Convenience-based pilots prove little about real-world PQC viability on high-risk systems.',
    },
    {
      title: 'Skip rollback planning',
      why: 'Deploying without a tested rollback path leaves you unable to revert when a pilot fails.',
    },
    {
      title: 'Big-bang instead of waves',
      why: 'Migrating all Tier-1 at once prevents each wave validating assumptions for the next.',
    },
    {
      title: 'Measure only latency, not compatibility',
      why: 'Handshake metrics alone miss the downstream compatibility failures that break production.',
    },
    {
      title: 'Treat hybrid as the end state',
      why: 'Deploying hybrid without planning the PQC-only transition forces a second migration later.',
    },
    {
      title: 'Ignore library version as a hard constraint',
      why: 'PQC needs current libraries (OpenSSL 3.5+, BoringSSL, AWS-LC, Bouncy Castle); a lagging library/runtime silently blocks the deployment you designed.',
    },
  ],
}

export default TREE
