// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 06142026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p7',
  gate: {
    id: 'G7',
    criterion: 'Continuous vendor governance operating',
  },
  generated: '06142026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator: 'Ad-hoc inquiries to a few vendors; no structured tracking',
      activities: [
        {
          id: '7.1',
          title: 'Classify Vendor Portfolio by PQC Impact',
          do: 'Categorize vendors as Strategic Blocking, Strategic Enabling or Non-Critical.',
          output: 'Vendor classification matrix',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Vendor & Supply-Chain Risk',
              to: '/learn/vendor-risk',
              moduleId: 'vendor-risk',
            },
            {
              kind: 'activity',
              label: 'Build the supply-chain matrix',
              to: '/business/tools/supply-chain-matrix',
              artifactType: 'supply-chain-matrix',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        'Top 10 vendors formally engaged; questionnaires sent; responses tracked; vendor criticality classification complete',
      activities: [
        {
          id: '7.2',
          title: 'Execute Vendor Engagement',
          do: 'Send PQC readiness questionnaires to strategic vendors and track responses.',
          output: 'Vendor questionnaire responses',
          steps: [
            {
              kind: 'reference',
              label: 'Reference: vendor FIPS/CC cert status',
              to: '/compliance?cert=',
              refId: 'compliance-cert-check',
            },
            {
              kind: 'activity',
              label: 'Score vendors (Vendor Scorecard)',
              to: '/business/tools/vendor-scorecard',
              artifactType: 'vendor-scorecard',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator:
        'PQC in standard procurement language; contracts include dated commitments and remedies; bridging patterns deployed for blocked systems; vendor scorecard reported to SteerCo',
      activities: [
        {
          id: '7.3',
          title: 'Insert PQC Requirements into Procurement',
          do: 'Add PQC clauses to RFP and contract templates with dated commitments and remedies.',
          output: 'Updated procurement templates',
          steps: [
            {
              kind: 'activity',
              label: 'Draft a PQC contract clause',
              to: '/business/tools/contract-clause',
              artifactType: 'contract-clause',
            },
          ],
        },
        {
          id: '7.4–7.6',
          title: 'Manage Blockers, Ongoing Governance & Uncompellable Counterparties',
          do: 'Deploy bridging patterns, run a recurring scorecard cadence and coordinate ecosystem partners.',
          output: 'Vendor governance cadence',
          steps: [
            {
              kind: 'reference',
              label: 'Govern vendors against the compliance map',
              to: '/compliance',
              refId: 'compliance',
            },
          ],
        },
      ],
    },
    {
      level: 4,
      indicator:
        'All strategic vendors PQC-committed with verified delivery; open-source dependency tracking operational; vendor governance is permanent BAU function',
      activities: [
        {
          id: '7.7',
          title: 'Cloud Shared Responsibility and the SaaS Class',
          do: 'Define the provider/customer migration boundary and govern SaaS by sensitivity.',
          output: 'Cloud responsibility & SaaS governance',
          steps: [
            {
              kind: 'activity',
              label: 'Map the cloud responsibility split',
              to: '/business/tools/cloud-responsibility-matrix',
              artifactType: 'cloud-responsibility-matrix',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Start vendor engagement too late',
      why: 'Vendor dependency is the longest critical path; waiting for a complete CBOM loses 12–24 months.',
    },
    {
      title: 'Accept verbal commitments',
      why: 'Verbal assurances evaporate when priorities shift; written GA dates and remedies are essential.',
    },
    {
      title: 'Treat all vendors equally',
      why: 'Equal intensity wastes resources; focus on the 5–10 Strategic Blocking vendors.',
    },
    {
      title: 'Keep no bridging strategy',
      why: 'When critical vendors miss milestones, undeployable bridging patterns leave you stuck.',
    },
    {
      title: 'Ignore open-source crypto dependencies',
      why: 'OpenSSL/Bouncy Castle and language libraries need the same tracking as commercial vendors.',
    },
  ],
}

export default TREE
