// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 06142026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p0',
  gate: {
    id: 'G0',
    criterion: 'Mandate signed',
  },
  generated: '06142026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator: 'Quantum risk acknowledged; no formal program',
      activities: [
        {
          id: '0.1',
          title: 'Frame the Business Case',
          do: 'Structure the executive argument around regulatory deadlines, HNDL and TNFL exposure, and stakeholder expectations.',
          output: 'Executive business case',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: PQC Business Case',
              to: '/learn/pqc-business-case',
              moduleId: 'pqc-business-case',
            },
            {
              kind: 'reference',
              label: 'Check the CRQC threat horizon',
              to: '/threats',
              refId: 'threats',
            },
            {
              kind: 'activity',
              label: 'Model the migration ROI',
              to: '/business/tools/roi-calculator',
              artifactType: 'roi-model',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator: 'Charter approved; QRPM appointed; Year 1 budget secured',
      activities: [
        {
          id: '0.2',
          title: 'Build the Budget Structure & Cost Estimates',
          do: 'Structure multi-year phased funding aligned to refresh cycles and estimate migration costs across all categories.',
          output: 'Multi-year budget & cost estimate',
          steps: [
            {
              kind: 'activity',
              label: 'Build the board pitch (budget ask)',
              to: '/business/tools/board-pitch',
              artifactType: 'board-deck',
            },
            {
              kind: 'activity',
              label: 'Ground the ask in a CRQC scenario',
              to: '/business/tools/crqc-scenario',
              artifactType: 'crqc-scenario',
            },
          ],
        },
        {
          id: '0.3',
          title: 'Establish Governance Structure',
          do: 'Define roles (Sponsor, SteerCo, QRPM, workstream leads), decision cadence, and policy.',
          output: 'Governance structure & policy',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: PQC Governance & Policy',
              to: '/learn/pqc-governance',
              moduleId: 'pqc-governance',
            },
            {
              kind: 'activity',
              label: 'Build the RACI matrix',
              to: '/business/tools/raci-builder',
              artifactType: 'raci-matrix',
            },
            {
              kind: 'activity',
              label: 'Draft the cryptography policy',
              to: '/business/tools/policy-generator',
              artifactType: 'policy-draft',
            },
          ],
        },
        {
          id: '0.4',
          title: 'Draft the Program Charter',
          do: 'Create the one-page charter: purpose, scope, success criteria, cadence, escalation.',
          output: 'Approved program charter',
          steps: [
            {
              kind: 'activity',
              label: 'Produce the Program Charter',
              to: '/business/tools/program-charter',
              artifactType: 'program-charter',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator: 'Multi-year budget committed; SteerCo operational; scoping assessment complete',
      activities: [
        {
          id: '0.5',
          title: 'Conduct Initial Scoping Assessment',
          do: 'Run a 2–4 week assessment of the top 20 systems, estate size, and critical vendor dependencies.',
          output: 'Initial scoping assessment',
          steps: [
            {
              kind: 'activity',
              label: 'Run the Initial Scoping Assessment',
              to: '/business/tools/initial-scoping',
              artifactType: 'initial-scoping',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Frame PQC as an innovation project',
      why: 'Treating migration as R&D instead of a governed program gets it deprioritized against operational work.',
    },
    {
      title: 'Commit only a single-year budget',
      why: 'One-year funding prevents realistic planning and talent retention over a 4–15 year program.',
    },
    {
      title: 'Leave business units off the SteerCo',
      why: 'Without business governance representation, workstream leads hit constant political resistance.',
    },
    {
      title: 'Delegate the program to vendors',
      why: 'Vendors execute on their own timelines, leaving you with no control over your migration.',
    },
    {
      title: 'Lock systems down prematurely',
      why: 'Knee-jerk restrictions burn operational goodwill without reducing HNDL risk.',
    },
  ],
}

export default TREE
