// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 06152026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p2',
  gate: {
    id: 'G2',
    criterion: 'Machine-verifiable CBOM published',
  },
  generated: '06152026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator: 'Partial CBOM in spreadsheet form covering known systems; no standard format',
      activities: [
        {
          id: '2.1',
          title: 'Select CBOM Format and Tooling',
          do: 'Adopt CycloneDX and establish the record structure and tooling.',
          output: 'CycloneDX CBOM format spec',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: CBOM in Cryptographic Management',
              to: '/learn/crypto-mgmt-modernization',
              moduleId: 'crypto-mgmt-modernization',
            },
            {
              kind: 'reference',
              label: 'Reference: CycloneDX in the Library',
              to: '/library',
              refId: 'library',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        'CycloneDX CBOM operational for Layers 1–2; queryable; SBOM linkage established for key applications',
      activities: [
        {
          id: '2.2',
          title: 'Populate CBOM from Inventory Data',
          do: 'Transform Phase 1 inventory into enriched CycloneDX records linked to the SBOM.',
          output: 'Populated CycloneDX CBOM',
          steps: [
            {
              kind: 'activity',
              label: 'Build a CycloneDX CBOM',
              to: '/business/tools/crypto-cbom-builder',
              artifactType: 'crypto-cbom',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator:
        'CBOM covers Layers 1–3; integrated into CI/CD; freshness governance enforced; change management integration live',
      activities: [
        {
          id: '2.3',
          title: 'Integrate CBOM into Operational Processes',
          do: 'Embed CBOM governance into CI/CD, change management, vendor onboarding and audit.',
          steps: [
            {
              kind: 'catalog',
              label: 'Wire CBOM into the Migrate pipeline',
              to: '/migrate',
            },
            {
              kind: 'activity',
              label: 'Wire CBOM freshness into CI/CD drift checks',
              to: '/business/tools/crypto-vulnerability-watch',
              artifactType: 'crypto-vulnerability-watch',
            },
          ],
        },
        {
          id: '2.4–2.5',
          title: 'CBOM Freshness Governance & Securing Program Artifacts',
          do: 'Enforce refresh triggers and protect the CBOM with classification and access control.',
          output: 'CBOM governance & protection policy',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: protect the CBOM (it is an HNDL shopping list) — SOC monitoring',
              to: '/learn/soc-implementation-pqc',
              moduleId: 'soc-implementation-pqc',
            },
            {
              kind: 'catalog',
              label: 'Set CBOM freshness triggers in the Migrate pipeline',
              to: '/migrate',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Insist on 100% CBOM coverage',
      why: 'Layer 4 is never fully visible; perfection blocks progress instead of managing gaps via vendor governance.',
    },
    {
      title: 'Keep the CBOM as a static document',
      why: 'A PDF/spreadsheet CBOM never updated is operationally useless; it must be live and queryable.',
    },
    {
      title: 'Ignore the SBOM↔CBOM linkage',
      why: 'CBOM entries without SBOM context miss dependency chains across shared libraries.',
    },
  ],
}

export default TREE
