// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 06142026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p6',
  gate: {
    id: 'G6',
    criterion: 'Infrastructure PQC-ready; performance validated',
  },
  generated: '06142026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 2,
      indicator:
        'HSMs inventoried with PQC status; PKI modernization plan drafted; initial middlebox testing underway',
      activities: [
        {
          id: '6.1',
          title: 'PKI Modernization',
          do: 'Shorten certificate lifetimes, deploy dual-stack CA, and test chains across middleboxes.',
          output: 'PKI modernization plan',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: PKI Workshop',
              to: '/learn/pki-workshop',
              moduleId: 'pki-workshop',
            },
          ],
        },
        {
          id: '6.2',
          title: 'HSM and KMS Modernization',
          do: 'Inventory HSMs by PQC capability, upgrade firmware and configure cloud KMS for PQC.',
          output: 'HSM/KMS upgrade schedule',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: HSM & PQC Operations',
              to: '/learn/hsm-pqc',
              moduleId: 'hsm-pqc',
            },
            {
              kind: 'learn',
              label: 'Learn: KMS & PQC',
              to: '/learn/kms-pqc',
              moduleId: 'kms-pqc',
            },
          ],
        },
        {
          id: '6.3',
          title: 'Network Infrastructure Assessment',
          do: 'Test PQC handshake sizes and protocol impacts across all production middleboxes.',
          output: 'Network compatibility report',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: Network Security & PQC',
              to: '/learn/network-security-pqc',
              moduleId: 'network-security-pqc',
            },
            {
              kind: 'reference',
              label: 'Reference: protocol PQC support',
              to: '/algorithms?tab=support',
              refId: 'algorithms-protocol-matrix',
            },
          ],
        },
      ],
    },
    {
      level: 3,
      indicator:
        'HSM upgrades in progress; PKI dual-stack operational; all production middleboxes tested; performance baselines established for Tier-1 systems',
      activities: [
        {
          id: '6.4',
          title: 'Performance Testing Methodology',
          do: 'Baseline metrics, run canary at 1–5% traffic and evaluate against SLOs.',
          output: 'Performance baseline and projections',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: PQC Testing & Validation',
              to: '/learn/pqc-testing-validation',
              moduleId: 'pqc-testing-validation',
            },
            {
              kind: 'reference',
              label: 'Reference: algorithm sizes & FIPS/CC certs',
              to: '/compliance?cert=',
              refId: 'compliance-cert-check',
            },
          ],
        },
        {
          id: '6.5',
          title: 'Capacity Planning for PQC at Scale',
          do: 'Estimate CPU, memory, bandwidth and storage impact; benchmark on production hardware.',
          output: 'Capacity plan',
          steps: [
            {
              kind: 'reference',
              label: 'Reference: the algorithm size catalog',
              to: '/algorithms',
              refId: 'algorithms-catalog',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Treat PQC as a drop-in library swap',
      why: 'PQC changes key/handshake sizes, breaking untested network paths and TLS termination.',
    },
    {
      title: 'Ignore middleboxes on the path',
      why: 'Firewalls, IDS/IPS and WAFs have hardcoded buffers that fail with PQC-sized handshakes.',
    },
    {
      title: 'Defer HSM capability upgrades',
      why: 'Discovering HSM incompatibility late causes 12–18 month procurement delays.',
    },
    {
      title: 'Do all PKI modernization in one event',
      why: 'Changing root, intermediate and end-entity at once risks widespread outages.',
    },
  ],
}

export default TREE
