// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-sim-trees.mjs on 06152026 — do not edit by hand.
// Source: Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)
// Self-contained dated snapshot. Re-run the generator to refresh; archive older dates.
import type { PhaseTree } from '../types'

const TREE: PhaseTree = {
  phase: 'p3',
  gate: {
    id: 'G3',
    criterion: 'QRA approved',
  },
  generated: '06152026',
  source: 'Applied Quantum PQC Migration Framework v2.1 (Marin Ivezić)',
  levels: [
    {
      level: 1,
      indicator:
        'Informal awareness of which systems are "probably vulnerable"; no structured scoring',
      activities: [
        {
          id: '3.1',
          title: 'Define Risk Scoring Model',
          do: 'Establish the four-dimension model: HNDL, TNFL, Regulatory, Feasibility.',
          output: 'Risk scoring model',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: PQC Risk Management',
              to: '/learn/pqc-risk-management',
              moduleId: 'pqc-risk-management',
            },
            {
              kind: 'learn',
              label: 'Learn: data sensitivity & legal/data-retention horizon',
              to: '/learn/data-asset-sensitivity',
              moduleId: 'data-asset-sensitivity',
            },
            {
              kind: 'reference',
              label: 'Reference: why 256-bit ECC ≈ RSA-2048 under quantum',
              to: '/threats',
              refId: 'threats',
            },
            {
              kind: 'reference',
              label: 'Reference: PQC Protocol Matrix',
              to: '/algorithms?tab=support',
              refId: 'algorithms-protocol-matrix',
            },
          ],
        },
      ],
    },
    {
      level: 2,
      indicator:
        'Formal risk scoring model applied to Tier-1 CBOM entries; prioritized migration backlog exists; QRA document produced',
      activities: [
        {
          id: '3.2',
          title: 'Calculate Priority Scores',
          do: 'Compute composite scores and classify systems into migration tiers.',
          output: 'Scored and tiered CBOM',
          steps: [
            {
              kind: 'activity',
              label: 'Produce a Risk Register',
              to: '/business/tools/risk-register',
              artifactType: 'risk-register',
            },
          ],
        },
        {
          id: '3.3',
          title: 'Apply Migration Sequencing Logic',
          do: 'Sequence with the two-track model (key exchange / signatures) by exposure and lead time.',
          output: 'Migration sequencing recommendation',
          steps: [
            {
              kind: 'learn',
              label: 'Learn: the two-track migration sequencing model',
              to: '/learn/migration-program',
              moduleId: 'migration-program',
            },
            {
              kind: 'reference',
              label: 'Confirm your classical → PQC replacement mapping',
              to: '/algorithms?tab=transition',
              refId: 'algorithms-transition',
            },
            {
              kind: 'reference',
              label: 'Compare PQC candidates in detail and confirm your architecture',
              to: '/algorithms?tab=detailed',
              refId: 'algorithms-detailed',
            },
            {
              kind: 'activity',
              label: 'Draft a Risk Treatment Plan',
              to: '/business/tools/risk-treatment-plan',
              artifactType: 'risk-treatment-plan',
            },
          ],
        },
        {
          id: '3.4',
          title: 'Produce the Quantum Readiness Assessment (QRA)',
          do: 'Consolidate scoring into a defensible QRA: heatmap, backlog, gap analysis, compliance mapping.',
          output: 'Quantum Readiness Assessment (QRA)',
          steps: [
            {
              kind: 'reference',
              label: 'Map the QRA to NIST / CNSA 2.0 / ETSI / sector rules',
              to: '/compliance',
              refId: 'compliance',
            },
            {
              kind: 'reference',
              label: 'Assemble the QRA on the Report page',
              to: '/report',
              refId: 'report',
            },
          ],
        },
      ],
    },
  ],
  pitfalls: [
    {
      title: 'Give everything equal priority',
      why: 'Treating all vulnerable crypto as equally urgent dilutes resources and stalls the highest-risk systems.',
    },
    {
      title: 'Ignore migration feasibility',
      why: 'Prioritising systems that cannot migrate yet wastes effort on unmigrable targets.',
    },
    {
      title: 'Produce the QRA once and freeze it',
      why: 'Risk scores change as standards mature and deadlines approach; a static QRA goes stale.',
    },
    {
      title: 'Migrate RSA before ECC for "strength"',
      why: '256-bit ECC is at least as exposed to quantum attack as RSA-2048; ordering by classical strength misreads the threat.',
    },
    {
      title: 'Skip the legal / data-retention review',
      why: 'Long-retention data (GDPR, contractual, >10–15y) changes the HNDL exposure window; without legal counsel the QRA under-scores the very data that needs protecting first.',
    },
  ],
}

export default TREE
