// SPDX-License-Identifier: GPL-3.0-only
/**
 * Pinned-value checks for the PQC random-input matrix.
 *
 * These are known-answer checks, not round-trips: every expected value below
 * was read from the final FIPS 203 / 204 / 205 PDFs on 2026-09-24 and is
 * written out literally here. If a value in pqcRandomInputs.ts changes, this
 * test must fail until someone re-reads the standard.
 */
import { describe, it, expect } from 'vitest'
import { createElement } from 'react'
import { render, screen, within } from '@testing-library/react'
import { MemoryRouter } from 'react-router'
import { PQC_RANDOM_INPUTS, PQC_ERRATA_STATE, type PqcRandomInput } from './pqcRandomInputs'
import { EntropyIntroduction } from '../components/EntropyIntroduction'
import { QRNGDemo } from '../workshop/QRNGDemo'

function row(id: string): PqcRandomInput {
  const r = PQC_RANDOM_INPUTS.find((x) => x.id === id)
  if (!r) throw new Error(`missing row ${id}`)
  return r
}

/** [parameter set, level, minBits] triples, sorted for stable comparison. */
function rules(id: string): string[] {
  return row(id)
    .strengthRules.flatMap((r) => r.parameterSets.map((p) => `${p}:${r.level}:${r.minBits}`))
    .sort()
}

describe('PQC random-input matrix (FIPS 203/204/205, checked 2026-09-24)', () => {
  it('has exactly the seven operations of the plan', () => {
    expect(PQC_RANDOM_INPUTS.map((r) => r.id)).toEqual([
      'ml-kem-keygen',
      'ml-kem-encaps',
      'ml-dsa-keygen',
      'ml-dsa-sign-hedged',
      'ml-dsa-sign-deterministic',
      'slh-dsa-keygen',
      'slh-dsa-sign',
    ])
  })

  it('ML-KEM KeyGen: d and z, 32 bytes each, shall 128/192/256 (FIPS 203 §3.3, Table 2)', () => {
    const r = row('ml-kem-keygen')
    expect(r.standard).toBe('FIPS 203')
    expect(r.inputs).toEqual(['d', 'z'])
    expect(r.length).toBe('32 bytes each')
    expect(rules('ml-kem-keygen')).toEqual([
      'ML-KEM-1024:shall:256',
      'ML-KEM-512:shall:128',
      'ML-KEM-768:shall:192',
    ])
  })

  it('ML-KEM Encaps: m, 32 bytes, same rule as KeyGen (FIPS 203 §3.3)', () => {
    const r = row('ml-kem-encaps')
    expect(r.inputs).toEqual(['m'])
    expect(r.length).toBe('32 bytes')
    expect(rules('ml-kem-encaps')).toEqual(rules('ml-kem-keygen'))
  })

  it('ML-DSA KeyGen: ξ, 32 bytes; ML-DSA-44 shall 128 AND should 192 (FIPS 204 §3.6.1)', () => {
    const r = row('ml-dsa-keygen')
    expect(r.standard).toBe('FIPS 204')
    expect(r.inputs).toEqual(['ξ'])
    expect(r.length).toBe('32 bytes')
    expect(rules('ml-dsa-keygen')).toEqual([
      'ML-DSA-44:shall:128',
      'ML-DSA-44:should:192',
      'ML-DSA-65:shall:192',
      'ML-DSA-87:shall:256',
    ])
    expect(r.ruleSummary).toContain('category 2 to category 1')
  })

  it('ML-DSA hedged signing: rnd has NO mandatory RBG strength (FIPS 204 §3.6.1)', () => {
    const r = row('ml-dsa-sign-hedged')
    expect(r.inputs).toEqual(['rnd'])
    expect(r.length).toBe('32 bytes')
    expect(r.strengthRules).toEqual([])
    expect(r.sources.map((s) => s.quote).join(' ')).toContain('should ideally be generated')
    expect(r.sources.map((s) => s.quote).join(' ')).toContain('even a weak RBG may be preferable')
    expect(r.notes).toContain('shall be generated by the cryptographic module')
  })

  it('ML-DSA deterministic signing: rnd = {0}^32, no fresh randomness (FIPS 204 §5.2)', () => {
    const r = row('ml-dsa-sign-deterministic')
    expect(r.length).toBe('32 bytes, fixed to {0}^32')
    expect(r.strengthRules).toEqual([])
  })

  it('SLH-DSA KeyGen: three n-byte values, shall be >= 8n bits (FIPS 205 §3.1)', () => {
    const r = row('slh-dsa-keygen')
    expect(r.standard).toBe('FIPS 205')
    expect(r.inputs).toEqual(['SK.seed', 'SK.prf', 'PK.seed'])
    expect(r.length).toBe('n bytes each (n = 16, 24 or 32)')
    const bits = r.strengthRules.map((x) => [x.level, x.minBits])
    expect(bits).toEqual([
      ['shall', 128],
      ['shall', 192],
      ['shall', 256],
    ])
  })

  it('SLH-DSA signing: addrnd has no mandatory RBG strength (FIPS 205 §9.2, §10.2)', () => {
    const r = row('slh-dsa-sign')
    expect(r.length).toBe('n bytes')
    expect(r.strengthRules).toEqual([])
    expect(r.notes).toContain('slh_sign_internal')
  })

  it('every row cites a section of its own standard', () => {
    for (const r of PQC_RANDOM_INPUTS) {
      expect(r.sources.length).toBeGreaterThan(0)
      for (const s of r.sources) {
        expect(s.section.startsWith(r.standard)).toBe(true)
        expect(s.quote.length).toBeGreaterThan(20)
      }
    }
  })

  it('never states an input as "full entropy" (F1 regression)', () => {
    const text = JSON.stringify(PQC_RANDOM_INPUTS).toLowerCase()
    expect(text).not.toContain('full entropy')
    expect(text).not.toContain('bits of entropy')
  })

  it('records the errata state and its check date', () => {
    expect(PQC_ERRATA_STATE.checkedOn).toBe('2026-09-24')
    expect(PQC_ERRATA_STATE.entries.map((e) => e.standard)).toEqual([
      'FIPS 203',
      'FIPS 204',
      'FIPS 205',
    ])
    expect(PQC_ERRATA_STATE.entries[0].state).toContain('2025-11-17')
    expect(PQC_ERRATA_STATE.entries[1].state).toContain('2026-07-31')
  })
})

/**
 * Claim-consistency checks on the rendered Learn text and the QRNG tool
 * (plan §10.2): the panel renders from the canonical data, and the removed
 * claims (F1, F7–F12) do not come back.
 */
describe('Entropy Learn and QRNG surfaces: removed claims stay removed', () => {
  function renderIntro() {
    return render(
      createElement(
        MemoryRouter,
        null,
        createElement(EntropyIntroduction, { onNavigateToWorkshop: () => {} })
      )
    )
  }

  it('renders one matrix row per canonical PQC_RANDOM_INPUTS entry', () => {
    renderIntro()
    const panel = screen.getByTestId('pqc-random-inputs')
    const bodyRows = within(panel).getAllByRole('row').slice(1)
    expect(bodyRows).toHaveLength(PQC_RANDOM_INPUTS.length)
    for (const r of PQC_RANDOM_INPUTS) {
      expect(within(panel).getByText(r.operation)).toBeTruthy()
    }
  })

  it('Learn text drops F1, F7, F8 and F9 wording', () => {
    const { container } = renderIntro()
    const text = container.textContent ?? ''
    expect(text).not.toMatch(/full entropy/i)
    expect(text).not.toMatch(/XOF_DRBG/)
    expect(text).not.toMatch(/synergiz/i)
    expect(text).not.toMatch(/~\s*6 weeks/)
    expect(text).not.toMatch(/guaranteed by quantum physics/i)
    expect(text).not.toMatch(/Category 5/)
    expect(text).toContain('Pre-draft call for comments')
  })

  it('QRNG tool states it is a simulation and makes no uncited certification claim', () => {
    const { container } = render(createElement(QRNGDemo))
    const text = container.textContent ?? ''
    expect(text).toContain('Simulation — no QRNG hardware involved.')
    expect(screen.getByTestId('qrng-proves-panel')).toBeTruthy()
    expect(text).not.toMatch(/FIPS 140-2/)
    expect(text).not.toMatch(/AIS 31 certified/i)
    expect(text).not.toMatch(/SP 800-90B certifies/i)
    expect(text).not.toMatch(/guaranteed by quantum physics/i)
  })
})
