// SPDX-License-Identifier: GPL-3.0-only
/**
 * communitySignalsData — bundled-at-build-time GitHub Discussions signals.
 *
 * Source of truth: `public/data/community-signals.json` (regenerated by
 * `npm run fetch-community-signals` or `tsx scripts/fetch-community-signals.ts`).
 *
 * The aggregator writes the same payload to both `public/data/` (served +
 * signed) and `src/data/community-signals.json` (bundled — this file).
 * Trust-score module reads from this bundled copy so per-record signals
 * are baked into the precomputed trust scores at app-load time.
 *
 * Schema mirrors `CommunitySignalsFile` in scripts/fetch-community-signals.ts.
 */
import raw from './community-signals.json'

export interface PerRecordCommunitySignal {
  endorsements: number
  flags: number
  discussion_numbers: number[]
}

export interface CommunitySignalsData {
  generated_at: string
  source: string
  discussion_count: number
  endorsement_count: number
  flag_count: number
  signals: Record<string, PerRecordCommunitySignal>
}

export const communitySignals: CommunitySignalsData = raw as CommunitySignalsData

/**
 * Build a Map keyed by `${resourceType}:${resourceId}` for O(1) lookup
 * during trust-score computation. Returns an empty Map if no signals exist.
 */
export function buildCommunitySignalsMap(): Map<string, PerRecordCommunitySignal> {
  const m = new Map<string, PerRecordCommunitySignal>()
  for (const [key, sig] of Object.entries(communitySignals.signals)) {
    m.set(key, sig)
  }
  return m
}
