// SPDX-License-Identifier: GPL-3.0-only
/**
 * contentFreshness — the machine-auditable manifest of every time-sensitive
 * claim the simulation surfaces (CMVP/FIPS status, the protocol matrix snapshot,
 * the Q-Day planning anchor). Each claim carries a structured `{ asOf, recheck }`
 * instead of a free-text date buried in prose, so a CI auditor can flag a claim
 * that has silently aged past its review window and point an owner at the live
 * source to re-verify it.
 *
 * Pure + deterministic: the staleness helpers take `now` as a parameter (no
 * `Date.now()` on the evaluated path) so the unit test and the CI script agree.
 *
 * The three sources expose their freshness in structured form; this module only
 * AGGREGATES them (one-way value imports), and each source imports nothing but
 * the `Freshness` *type* back, so there is no runtime import cycle.
 */
import { Q_DAY_FRESHNESS } from './quantumTimeline'
import { PROTOCOL_MATRIX_FRESHNESS } from './pqcProtocolMatrix'
import { SIM_MOVES } from './simMoves'

/** A structured, re-verifiable timestamp attached to a time-sensitive claim. */
export interface Freshness {
  /** ISO date (YYYY-MM-DD) the claim was last verified against its source. */
  asOf: string
  /** URL of the live source to re-verify the claim against. */
  recheck: string
}

/** A single dated claim in the manifest, with where it lives + what it asserts. */
export interface FreshnessClaim extends Freshness {
  /** Stable slug — used by the report and to keep ordering deterministic. */
  id: string
  /** Human description of what must stay true. */
  claim: string
  /** Source file the claim is maintained in. */
  source: string
}

/** Review window: a claim older than this many days is flagged stale. */
export const FRESHNESS_MAX_AGE_DAYS = 90

const ISO_DATE = /^\d{4}-\d{2}-\d{2}$/

/** Whole days between `asOf` (UTC midnight) and `now`. Negative if asOf is future. */
export function ageInDays(asOf: string, now: Date): number {
  const then = Date.parse(`${asOf}T00:00:00Z`)
  return Math.floor((now.getTime() - then) / 86_400_000)
}

/** The claims older than `maxDays` relative to `now` — the auditor's flag set. */
export function staleClaims(
  claims: FreshnessClaim[],
  now: Date,
  maxDays: number = FRESHNESS_MAX_AGE_DAYS
): FreshnessClaim[] {
  return claims.filter((c) => ageInDays(c.asOf, now) > maxDays)
}

/** Walk SIM_MOVES for moves that carry a structured freshness stamp. */
function simMoveClaims(): FreshnessClaim[] {
  const out: FreshnessClaim[] = []
  for (const [phase, moves] of Object.entries(SIM_MOVES)) {
    for (const move of moves ?? []) {
      if (!move.freshness) continue
      out.push({
        id: `simmove-${phase}-${move.label
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/^-|-$/g, '')}`,
        claim: `Sim move (${phase}): "${move.label}"`,
        source: 'src/data/simMoves.ts',
        ...move.freshness,
      })
    }
  }
  return out
}

/**
 * The full manifest, sorted by id for a deterministic report. Extend by adding a
 * structured `Freshness` at the source and surfacing it here.
 */
export const FRESHNESS_CLAIMS: FreshnessClaim[] = [
  {
    id: 'q-day-anchor',
    claim: 'Sim Q-Day anchor (2029) vs the public 2030–2040 CRQC range',
    source: 'src/data/quantumTimeline.ts',
    ...Q_DAY_FRESHNESS,
  },
  {
    id: 'protocol-support-matrix',
    claim: 'PQC protocol-support matrix snapshot (RFC/draft stages, GA dates)',
    source: 'src/data/pqcProtocolMatrix.ts',
    ...PROTOCOL_MATRIX_FRESHNESS,
  },
  ...simMoveClaims(),
].sort((a, b) => a.id.localeCompare(b.id))

/** Every claim's asOf is a well-formed ISO date — guards typos at test time. */
export function malformedClaims(claims: FreshnessClaim[] = FRESHNESS_CLAIMS): FreshnessClaim[] {
  return claims.filter((c) => !ISO_DATE.test(c.asOf) || !/^https?:\/\//.test(c.recheck))
}

/**
 * Deterministic markdown catalog (no `now`-derived content) for
 * `reports/content-freshness.md` — the next reviewer's checklist.
 */
export function freshnessReportMarkdown(claims: FreshnessClaim[] = FRESHNESS_CLAIMS): string {
  const rows = claims
    .map((c) => `| \`${c.id}\` | ${c.claim} | ${c.asOf} | ${c.source} | [re-check](${c.recheck}) |`)
    .join('\n')
  return [
    '# Content-freshness manifest',
    '',
    '> Generated by `npm run audit:content-freshness -- --write`. Do not hand-edit —',
    `> update the \`Freshness\` stamp at each \`source\` instead. Review window: ${FRESHNESS_MAX_AGE_DAYS} days.`,
    '',
    '| id | claim | asOf | source | re-check |',
    '| --- | --- | --- | --- | --- |',
    rows,
    '',
  ].join('\n')
}
