// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-framework-phase-intros.mjs from pqc-references/framework-2.1.json
// (the machine-readable twin of framework-2.1.yaml — the Applied Quantum PQC Migration
// Framework v2.1 SoT). Do not edit by hand; re-run the generator if the framework changes.
import type { PhaseId } from '@/data/frameworkPhases'

export interface FrameworkActivityIntro {
  title: string
  do: string
  output: string
}

export interface FrameworkPhaseIntro {
  /** Framework phase name, verbatim. */
  name: string
  /** Framework phase summary — "what to expect", verbatim. */
  summary: string
  /** Framework exit-gate note (or closure criteria for verify-close). */
  gate: string | null
  /** Framework activities for this phase (the steps / resources / work). */
  activities: FrameworkActivityIntro[]
}

export const FRAMEWORK_PHASE_INTROS: Partial<Record<PhaseId, FrameworkPhaseIntro>> = {
  p0: {
    name: 'Phase 0 — Executive Mandate & Business Case',
    summary:
      'Establish the governance foundation and secure multi-year funding, authority, and organizational commitment. Frames PQC migration as a multi-year enterprise transformation program (not an IT project) and is the single most common failure point.',
    gate: 'Phase 0 exit corresponds to the executive-mandate gate: charter approved, multi-year budget committed, governance structure (SteerCo confirmed, QRPM appointed, cadence established), initial scoping assessment, and board briefing delivered.',
    activities: [
      {
        title: 'Frame the Business Case',
        do: "Structure the executive argument around four concrete, current 'urgency drivers' rather than speculative Q-Day predictions.",
        output: 'Board briefing deck',
      },
      {
        title: 'Build the Budget Structure',
        do: 'Structure funding as a multi-year program with phased investment rather than a single project budget line, and align spend to existing infrastructure refresh cycles.',
        output: 'Multi-year budget commitment',
      },
      {
        title: 'Build the Business Case — Additional Benefit Arguments',
        do: 'Beyond the four urgency drivers, marshal additional arguments that strengthen the business case.',
        output: 'Board briefing deck',
      },
      {
        title: 'Develop Migration Cost Estimates',
        do: 'Build a budget structure despite inherent imprecision; estimate each cost-driver category separately rather than waiting for precise data.',
        output: 'Multi-year budget commitment',
      },
      {
        title: 'Establish Governance Structure',
        do: "Stand up the program's roles, workstreams, decision cadence, board oversight model, risk appetite statement, and three-lines-of-defense structure.",
        output: 'Governance structure',
      },
      {
        title: 'Draft the Program Charter',
        do: 'Produce a one-page charter document.',
        output: 'Approved program charter',
      },
      {
        title: 'Conduct Initial Scoping Assessment',
        do: 'Before launching full discovery, perform a rapid (2–4 week) scoping assessment to establish program boundaries.',
        output: 'Initial scoping assessment',
      },
    ],
  },
  p1: {
    name: 'Phase 1 — Discovery & Inventory',
    summary:
      'Build a comprehensive, continuously updated inventory of all cryptographic usage across IT, OT, cloud, IoT, and third-party systems. Foundational activity on which every subsequent phase depends — you cannot migrate what you cannot see. Major organizations should plan 12–24 months of dedicated team effort; no single tool provides 100% discovery.',
    gate: 'Phase 1 exit: risk-driven scoping document; cryptographic asset inventory (Priority A ≥90% within 60 days, ≥90% of all Tier-1 within 12 months); classical vulnerability findings reported; integrated sensitive-data map and systems/assets register; discovery gap register; continuous-discovery operating model.',
    activities: [
      {
        title: 'Risk-Driven Scoping — Decide What to Inventory First',
        do: 'Apply an 80/20 prioritization to determine where to focus initial discovery effort before launching broad discovery; an architecture-first approach concentrating discovery where risk concentrates.',
        output: 'Risk-driven scoping document',
      },
      {
        title: 'Establish Three Parallel Inventory Tracks',
        do: 'Run integrated discovery across three interdependent domains coordinated through a single governance structure, even if executed by different teams with different tools.',
        output:
          'Cryptographic asset inventory; Sensitive data map (integrated); Systems and assets register (integrated)',
      },
      {
        title: 'Deploy Cryptographic Discovery — Layered Approach',
        do: 'Deploy a combination of discovery techniques because no single technique covers all cryptographic usage; supplement with tool selection across capability categories.',
        output: 'Cryptographic asset inventory',
      },
      {
        title: 'Map the Cryptographic Estate',
        do: 'For every cryptographic instance discovered, record a standard set of fields.',
        output: 'Cryptographic asset inventory',
      },
      {
        title: 'Address the Asset Discovery Problem',
        do: 'Confront the asset discovery gap directly — you cannot scan a system you do not know exists — by going far beyond the CMDB across many data sources.',
        output: 'Systems and assets register (integrated); Discovery gap register',
      },
      {
        title: 'Integrate with Existing Data Sources',
        do: 'Do not build the cryptographic inventory from scratch in isolation; integrate existing organizational data to save effort, improve accuracy, and inherit business context.',
        output: 'Cryptographic asset inventory; Systems and assets register (integrated)',
      },
      {
        title: 'Establish Continuous Discovery',
        do: 'Treat the cryptographic inventory as a living data set maintained continuously, spanning CI/CD integration, passive monitoring, change management, scheduled rescans, external intelligence, alerting, culture, and effectiveness metrics.',
        output: 'Continuous discovery operating model',
      },
    ],
  },
  p2: {
    name: 'CBOM & Documentation',
    summary:
      'Transform raw Phase 1 inventory data into a durable, queryable, standardized Cryptographic Bill of Materials (CBOM) that serves as the single source of truth for all subsequent phases, making PQC migration auditable, plannable, and measurable.',
    gate: 'Phase 2 exit (CycloneDX CBOM operational for Layers 1–2 with freshness governance and protection controls) corresponds to the G2->G3 transition; authoritative gate criteria live in the global stage_gates table.',
    activities: [
      {
        title: 'Select CBOM Format and Tooling',
        do: 'Choose the CBOM format and hosting platform and define the per-entry record structure. Recommended format is CycloneDX, the de facto CBOM standard with native support for cryptographic asset types (algorithms, certificates, keys, protocols, related dependencies).',
        output: 'CycloneDX CBOM (format/tooling decision and record schema)',
      },
      {
        title: 'Populate CBOM from Inventory Data',
        do: 'Map Phase 1 inventory data into CBOM records as a data transformation and enrichment exercise.',
        output: 'Populated CycloneDX CBOM records',
      },
      {
        title: 'Integrate CBOM into Operational Processes',
        do: 'Embed the CBOM into operational processes so it is a live system rather than a static document.',
        output: 'CI/CD integration',
      },
      {
        title: 'Establish CBOM Freshness Governance',
        do: 'Define trigger-to-action rules that keep the CBOM current.',
        output: 'CBOM governance policy',
      },
      {
        title: 'Secure the CBOM and Program Artifacts',
        do: 'Protect the CBOM, QRA, and prioritized migration backlog, which together form a map of every weak cryptographic point in the enterprise and a target-selection shopping list for HNDL adversaries.',
        output: 'CBOM protection controls',
      },
    ],
  },
  p3: {
    name: 'Risk Scoring & Prioritization',
    summary:
      'Translate CBOM data into a defensible, sequenced migration priority list, producing the prioritized backlog and Quantum Readiness Assessment (QRA) that drive Phase 4 roadmap planning and Phase 5 execution sequencing. A structured, transparent scoring model depoliticizes sequencing by replacing opinion with repeatable criteria.',
    gate: 'Phase 3 exit (scored/tiered CBOM and a produced QRA with prioritized backlog ready for Phase 4) corresponds to the G3->G4 transition; authoritative gate criteria live in the global stage_gates table.',
    activities: [
      {
        title: 'Define Risk Scoring Model',
        do: 'Define a quantum-specific risk scoring model that extends established information security risk methodologies (ISO/IEC 27005, NIST SP 800-30, NIST RMF). Default weights are a starting configuration to be calibrated by sector, risk profile, and regulatory context. Score each CBOM entry across four dimensions.',
        output: 'Risk scoring model (four-dimension, calibrated weights)',
      },
      {
        title: 'Calculate Priority Scores',
        do: 'Compute a composite priority score for each CBOM entry and classify it into a migration urgency tier.',
        output: 'Scored and tiered CBOM',
      },
      {
        title: 'Apply Migration Sequencing Logic',
        do: 'Sequence the prioritized backlog within the Two-Track Migration Model from Phase 5: Track A (key exchange and confidentiality) and Track B (signatures, PKI, authentication) run as parallel workstreams, not a serial list. v2.1 retires the earlier key-exchange-then-signatures-then-data-at-rest serialization because treating signatures as second systematically delays the migrations with the longest lead times.',
        output: 'Migration sequencing recommendation',
      },
      {
        title: 'Produce the Quantum Readiness Assessment (QRA)',
        do: 'Consolidate risk scoring into a formal Quantum Readiness Assessment document as the defensible basis for migration planning and regulatory evidence.',
        output: 'Quantum Readiness Assessment (QRA)',
      },
    ],
  },
  p4: {
    name: 'Phase 4 — Roadmap & Governance',
    summary:
      'Translate the prioritized Phase 3 migration backlog into a multi-year execution plan with realistic milestones, resource allocations, vendor coordination timelines, and governance checkpoints. Establishes PMO discipline and models external constraints (vendor GA dates, hardware refresh, regulatory deadlines, scarce crypto skills) explicitly, not just internal work sequencing.',
    gate: "Phase 4 exit corresponds to gate G3 -> G4: 'Multi-year roadmap approved; Year 1 plan resourced' (Executive Sponsor), per Activity 4.6's milestone gate table at lines ~3932-3933",
    activities: [
      {
        title: 'Define Year-1 Starter Plan (90-Day Governance Sprint)',
        do: 'Deliver five things in the first 90 days across Organization, People, Plan, Policy/Procurement, and KPI pack; then execute a quarter-by-quarter Year-1 detailed plan (Q1-Q4) spanning Governance & People, Discovery & CBOM, Pilots & Technical, and Vendor & Policy workstreams.',
        output: 'Year 1 detailed plan',
      },
      {
        title: 'Structure the Multi-Year Roadmap',
        do: 'Lay out a 5-year roadmap with a focus theme and key milestones per year.',
        output: 'Multi-year roadmap',
      },
      {
        title: 'Align to Infrastructure Refresh Cycles',
        do: 'Map migration tasks to existing planned expenditures so PQC piggybacks on already-funded infrastructure changes.',
        output: 'Multi-year roadmap (refresh-cycle alignment)',
      },
      {
        title: 'Establish PMO Structure for Scale',
        do: 'For programs exceeding 10,000 tasks, stand up PMO machinery and map/track the critical dependency chains.',
        output: 'PMO operating model',
      },
      {
        title: 'Manage the Roadmap as a Living Instrument',
        do: 'Treat the roadmap as a living instrument, not a static Gantt chart; run a quarterly roadmap review as a standing SteerCo agenda item presenting KPIs alongside leading indicators, and apply a decision playbook when adjustment is needed.',
        output: 'Multi-year roadmap (quarterly review governance)',
      },
      {
        title: 'Define Milestone Gates',
        do: 'Define a milestone gate review for each phase transition, with explicit criteria and a decision authority per gate.',
        output: 'Milestone gate definitions (PMO operating model)',
      },
      {
        title: 'Pre-Draft the Accelerated Execution Profile',
        do: 'Pre-draft the accelerated track as a concrete, pre-approved artifact before it is needed, and exercise it annually as a tabletop scenario.',
        output: 'Accelerated Execution Profile (pre-approved package)',
      },
    ],
  },
  p5: {
    name: 'Phase 5 — Pilots & Migration Execution',
    summary:
      "Execute the migration through controlled pilots, validate patterns, and scale to production through waves, operationalizing the Phase 4 roadmap starting with the highest-priority, most-controllable systems. Produces the program's first tangible security outcomes and deliberately surfaces infrastructure incompatibilities, performance regressions, middlebox failures, and interoperability problems in a controlled setting with tested rollback.",
    gate: "Phase 5 exit corresponds to gate G5 -> G6: 'Pilots validated; performance baselines established; Tier-1 rollout approved' (SteerCo)",
    activities: [
      {
        title: 'Select Pilot Targets',
        do: 'Choose 2-4 initial pilots based on Tier-1 priority from Phase 3 risk scoring, full organizational control of both endpoints, a measurable baseline, representative architecture, and rollback capability.',
        output: 'Pilot results reports (pilot candidates for both Track A and Track B)',
      },
      {
        title: 'Design Hybrid Deployments',
        do: 'Default to Hybrid ML-KEM-768 + X25519 for TLS key exchange (the X25519MLKEM768 named group in TLS 1.3); choose hybrid over pure PQC for the stated reasons; default to composite/dual signatures where toolchains support them; and verify cryptographic library readiness before committing to a deployment pattern.',
        output: 'Validated migration patterns',
      },
      {
        title: 'Execute Pilots with Measurement',
        do: 'For each pilot, define and measure performance SLOs, anticipate expected performance impacts, and define explicit rollback criteria/triggers.',
        output:
          'Pilot results reports (performance data, compatibility findings, issues log, recommendations)',
      },
      {
        title: 'Scale from Pilot to Production Through Waves',
        do: 'Sequence deployment through controlled waves, each with a defined scope and an explicit prerequisite gate from the prior wave.',
        output: 'Wave deployment plan',
      },
      {
        title: 'Implement Defense-in-Depth Beyond Pure PQC',
        do: 'Complement hybrid/PQC deployment with layered controls that reduce cryptographic protection surface and protect data across in-transit, at-rest, and in-use states.',
        output: 'Defense-in-depth implementation (tokenization, segmentation, AES-256 defaults)',
      },
      {
        title: 'Decide the Data-at-Rest Strategy',
        do: "Make a per-data-store choice among five data-at-rest strategies, driven by the data's confidentiality horizon (Phase 1 classification), volume, and exfiltration exposure; record the chosen strategy per data store in the CBOM.",
        output: 'Per-data-store strategy recorded in the CBOM',
      },
      {
        title: 'AI-Assisted Migration: Where It Helps, and the Gate That Stays Closed',
        do: 'Use AI tooling where it genuinely accelerates migration (triage and drafting) while holding a non-negotiable gate that AI-modified cryptographic code passes the same (or more) review/testing/validation rigor as human-written code; keep algorithm selection, parameter choices, and risk acceptances as human decisions, and record AI-assisted provenance.',
        output: 'AI-assisted provenance recorded on migrated components',
      },
    ],
  },
  p6: {
    name: 'Infrastructure Modernization & Performance',
    summary:
      'Modernize the cryptographic infrastructure stack (PKI, HSMs, KMS, network devices, middleboxes) to support PQC operations at production scale, and address the performance, capacity, and compatibility challenges PQC introduces to real infrastructure.',
    gate: "Phase 6 exit corresponds to infrastructure readiness gating scaled Phase 5 production deployment; each Phase 6 deliverable (PKI dual-stack, HSM upgrade, middlebox clearance) unblocks a corresponding set of Phase 5 migration targets. Note: Phase 6 is iterative/parallel with Phase 5, so this maps to the framework's infrastructure-readiness transition rather than a single hard cutover.",
    activities: [
      {
        title: 'PKI Modernization',
        do: "Address PQC's fundamental challenges to PKI (certificate size explosion, increased chain verification time, middlebox compatibility) by executing the PKI migration strategy: shorten key lifetimes immediately, deploy dual-stack CA infrastructure, track Merkle Tree Certificates for web PKI, and test certificate chain processing through all middleboxes before production.",
        output: 'PKI modernization plan',
      },
      {
        title: 'HSM and KMS Modernization',
        do: 'Inventory all HSMs by model, firmware version, and PQC capability (immediate); upgrade HSM firmware to PQC-capable versions as available; plan HSM hardware replacement aligned to refresh cycle where firmware upgrade is insufficient; configure cloud KMS for PQC key types as available; and deploy software-based PQC key-wrapping overlay as a bridge for HSMs not yet upgradeable.',
        output: 'HSM/KMS upgrade schedule',
      },
      {
        title: 'Network Infrastructure Assessment',
        do: 'Test the ways PQC impacts network infrastructure before production deployment, covering handshake size impact and protocol-specific concerns (TLS 1.3, DTLS/UDP, IKEv2/IPsec, QUIC, constrained IoT, satellite/LPWAN, mobile networks), applying the per-protocol mitigations.',
        output: 'Network compatibility report',
      },
      {
        title: 'Performance Testing Methodology',
        do: 'For each system targeted for PQC migration, execute baseline measurement, lab validation, canary deployment, SLO evaluation, and capacity planning.',
        output: 'Performance baseline and projections',
      },
      {
        title: 'Capacity Planning for PQC at Scale',
        do: 'Plan for the expected resource impact of PQC across CPU, memory, network bandwidth, and storage, taking the prescribed planning action for each.',
        output: 'Performance baseline and projections (capacity plan for production rollout)',
      },
    ],
  },
  p7: {
    name: 'Vendor & Supply Chain Governance',
    summary:
      "Ensure third-party products and services support the organization's PQC migration timeline. Vendor dependencies are the single largest external constraint on migration speed; vendors update on their own timelines unless contractually compelled otherwise.",
    gate: 'continuous phase — framework defines no one-time gate',
    activities: [
      {
        title: 'Classify Vendor Portfolio by PQC Impact',
        do: 'Classify each vendor into one of three categories by PQC impact and take the corresponding action.',
        output: 'Vendor PQC readiness register (vendor classification matrix)',
      },
      {
        title: 'Execute Vendor Engagement',
        do: 'For each strategic vendor, obtain a PQC feature matrix, GA version and dates, interoperability guidance, performance data, fallback behavior, and CBOM data; drive engagement using the core Vendor PQC Readiness Questionnaire.',
        output: 'Vendor questionnaire responses',
      },
      {
        title: 'Insert PQC Requirements into Procurement',
        do: 'For all new purchases and contract renewals, add a PQC warranty/crypto-agility clause (adapted by legal counsel) and add PQC requirements to RFPs; adapt existing government model language rather than drafting from scratch.',
        output: 'Updated procurement requirements',
      },
      {
        title: 'Manage Vendor-as-Blocker Scenarios',
        do: 'When a critical vendor cannot provide PQC support within the migration timeline, deploy bridging patterns, run champion-challenger evaluation, escalate contractually, and accept-and-document residual risk if no alternative exists.',
        output: 'Bridging pattern deployments',
      },
      {
        title: 'Establish Ongoing Vendor Governance',
        do: 'Run the ongoing vendor governance cadence (tracking roadmaps, verifying GA commitments, updating scorecards, reporting to SteerCo, re-evaluating classifications) and report the vendor KPI board to SteerCo.',
        output: 'Vendor governance cadence',
      },
      {
        title: 'Coordinate Counterparties You Cannot Contractually Compel',
        do: 'Coordinate partners, customers, API consumers, and interbank/B2B counterparties (who offer no contractual leverage but on whom Wave 3 "External, Controlled" deployment depends) using a six-element negotiation pattern.',
        output: 'Counterparty coordination (negotiation pattern, feeds the risk register)',
      },
      {
        title: 'Cloud Shared Responsibility and the SaaS Class',
        do: 'Apply the cloud shared-responsibility split (who migrates what) with boundary verification, and treat SaaS as a distinct control-posture class where vendor governance is the only lever.',
        output: 'Vendor PQC readiness register (provider attestations + SaaS classification)',
      },
    ],
  },
  'verify-close': {
    name: 'Migration Verification & Program Closure',
    summary:
      'Defines how to prove the migration happened (verification) and how the program ends (closure into BAU). Both are routinely neglected: systems get reported migrated on change tickets rather than observed behavior, and programs drift into an unfunded twilight instead of closing deliberately.',
    gate: 'Define closure criteria in advance: typically maturity Level 4 or higher across all seven domains; verification complete for Tier 1 and Tier 2 systems; and every remaining item carried as an explicit risk acceptance with an owner and a re-evaluation date.',
    activities: [
      {
        title: 'Verification records',
        do: 'Evidence standard applied; 100% Tier 1 coverage, documented sampling for lower tiers; records filed in the evidence dossier',
        output: '',
      },
      {
        title: 'Decommissioning log',
        do: 'Certificates revoked on schedule; keys destroyed with certificates; trust stores cleaned; CBOM entries updated',
        output: '',
      },
      {
        title: 'Closure decision record',
        do: 'Closure criteria met or explicitly risk-accepted; decision minuted by the governance level that chartered the program',
        output: '',
      },
      {
        title: 'BAU handover register',
        do: 'Named permanent owner, funded budget, and operating cadence for every continuing capability',
        output: '',
      },
    ],
  },
  foundations: {
    name: 'Program Foundations (cross-cutting)',
    summary:
      'Program Foundations are capabilities that span every phase and operate continuously across the program lifecycle. Five foundational capabilities: a maturity model for benchmarking, metrics and KPIs for tracking/reporting, crypto-agility as architectural end-state, regulatory and standards alignment, and the skills and team structures to execute. Each should be established early (Phase 0/Phase 1) and maintained throughout.',
    gate: null,
    activities: [],
  },
}
