// SPDX-License-Identifier: GPL-3.0-only
// Generated by scripts/sync-sandbox-scenarios.ts — do not edit by hand.
// Source: pqctoday-sandbox/ui/src/data/scenarios.ts
// Regenerate with: npm run sync:sandbox

export type SandboxTrackId =
  | 'protocol-simulation'
  | 'infrastructure'
  | 'supply-chain'
  | 'quantum'
  | 'secrets-kms'
  | 'web'
  | 'applications'
export type SandboxDifficulty = 'beginner' | 'intermediate' | 'advanced'

export interface SandboxScenario {
  id: string
  title: string
  emoji: string
  useCase: string
  algorithms: string[]
  difficulty: SandboxDifficulty
  trackId: SandboxTrackId
  tool: { name: string; url: string }
}

export interface SandboxTrack {
  id: SandboxTrackId
  label: string
  subtitle: string
  difficulty: string
}

export const SANDBOX_SCENARIOS: SandboxScenario[] = [
  {
    id: 'tls',
    title: 'OpenSSL TLS 1.3 + Composite Cert',
    emoji: '🔐',
    useCase:
      'Execute OpenSSL TLS 1.3 handshakes with configurable certificate formats. In pure-ML-DSA mode the server cert is an ML-DSA-65 cert (key from openssl genpkey) and ML-DSA authenticates the connection. In composite mode a LAMPS draft-19 composite CERTIFICATE (ML-DSA-65 + ECDSA-P256, OID 1.3.6.1.5.5.7.6.45) is constructed by composite_mkcert from softhsmv3 PKCS#11 keys — but the live TLS handshake authenticates with a fresh ephemeral ECDSA-P256 key (the composite SignatureScheme is not yet in OpenSSL mainline, so ML-DSA does not sign CertificateVerify). Both modes pair with the X25519MLKEM768 hybrid KEX for a quantum-safe key exchange.',
    algorithms: ['ML-KEM-768', 'TLS 1.3', 'LAMPS Composite cert', 'softhsmv3 PKCS#11 keys'],
    difficulty: 'advanced',
    trackId: 'protocol-simulation',
    tool: { name: 'OpenSSL', url: 'https://github.com/openssl/openssl' },
  },
  {
    id: 'ssh',
    title: 'SSH PQC Authentication + KEX',
    emoji: '💻',
    useCase:
      'Full post-quantum SSH session: host and client auth keys (ML-DSA-65) held in softhsmv3 via PKCS#11 v3.2, combined with draft-ietf-sshm-mlkem-hybrid-kex hybrid ML-KEM key exchange (mlkem768x25519). Every auth signature traverses C_Sign on the HSM token; the ephemeral ML-KEM KEX runs in-process inside OpenSSH.',
    algorithms: ['ML-DSA-65', 'ML-KEM hybrid KEX', 'OpenSSH 10.3', 'PKCS#11 v3.2'],
    difficulty: 'intermediate',
    trackId: 'protocol-simulation',
    tool: {
      name: 'OpenSSH (PQCToday patch)',
      url: 'https://datatracker.ietf.org/doc/draft-sfluhrer-ssh-mldsa/',
    },
  },
  {
    id: 'vpn',
    title: 'Quantum-Resistant VPN',
    emoji: '🛡️',
    useCase:
      'Secure site-to-site IPsec routing hidden behind SoftHSMv3 IKEv2 Key Exchanges, contrasting classical Diffie-Hellman vulnerability against post-quantum encapsulation.',
    algorithms: ['ML-KEM', 'IKEv2'],
    difficulty: 'intermediate',
    trackId: 'protocol-simulation',
    tool: { name: 'strongSwan', url: 'https://www.strongswan.org' },
  },
  {
    id: 'tpm-playground',
    title: 'TPM 2.0 PQC Playground',
    emoji: '🛠️',
    useCase:
      'Execute raw TPM 2.0 Post-Quantum operations (ML-KEM & ML-DSA) entirely in the browser utilizing a WebAssembly port of libtpms coupled with real-time compliance validation.',
    algorithms: ['WASM TPM', 'TCG V1.85'],
    difficulty: 'advanced',
    trackId: 'protocol-simulation',
    tool: { name: 'libtpms WASM', url: 'https://github.com/stefanberger/libtpms' },
  },
  {
    id: 'pki',
    title: 'Enterprise PKI Chains',
    emoji: '🏛️',
    useCase:
      "Build a hierarchical PQC Certificate Authority with OpenSSL 3.6 — a mixed-algorithm chain: Root CA (SLH-DSA-SHA2-128s) → Intermediate CA (ML-DSA-65) → Leaf (ML-DSA-44) — verified end-to-end and compared against an all-RSA-2048 classical chain. The ML-DSA-65 tier is also exercised as an HSM-resident CA: the key is generated inside softhsmv3 and the issued leaf's certificate signature is a real HSM C_Sign, so the live PKCS#11 panel shows the actual C_GenerateKeyPair / C_Sign (ML-DSA-65) captured by pkcs11-spy.",
    algorithms: ['SLH-DSA-128s', 'ML-DSA-65', 'ML-DSA-44', 'X.509'],
    difficulty: 'beginner',
    trackId: 'infrastructure',
    tool: { name: 'OpenSSL', url: 'https://www.openssl.org' },
  },
  {
    id: 'cert-validation',
    title: 'Certificate Chain Validation',
    emoji: '✅',
    useCase:
      'Verify ML-DSA-65 certificate chains end-to-end — from Root CA through Intermediate to Leaf — validating that PQC signatures are correctly chained and parseable by OpenSSL.',
    algorithms: ['ML-DSA-65', 'X.509 Chain'],
    difficulty: 'beginner',
    trackId: 'infrastructure',
    tool: { name: 'OpenSSL', url: 'https://github.com/openssl/openssl' },
  },
  {
    id: 'hybrid-certs',
    title: 'Hybrid Certificate Formats',
    emoji: '📜',
    useCase:
      'Generate and compare all 7 PQC X.509 certificate formats — Pure ML-DSA, Pure SLH-DSA, Composite, Alt-Sig/Catalyst, Related Certificates, Chameleon, and the new ML-KEM-768 KEM certificate (RFC 9935) — measuring DER sizes, keygen times, backward compatibility, and encapsulation round-trips.',
    algorithms: ['7 Formats', 'X.509', 'RFC 9935'],
    difficulty: 'advanced',
    trackId: 'infrastructure',
    tool: {
      name: 'OpenSSL 3.6.2 (file-based keys; no HSM)',
      url: 'https://github.com/openssl/openssl',
    },
  },
  {
    id: 'mtc',
    title: 'Merkle Tree Certificates',
    emoji: '🌳',
    useCase:
      'Mitigate PQC certificate bloat: compare a real X.509 ML-DSA-87 three-cert chain (root → intermediate → leaf) against a Merkle Tree Certificate (assertion + inclusion proof) issued by a real bwesterb/mtc v0.1.2 CA with an ML-DSA-87 signing key. Certificate management and SIZE only — no TLS stack negotiates MTC yet.',
    algorithms: ['ML-DSA-87', 'MTC', 'Cert size'],
    difficulty: 'advanced',
    trackId: 'infrastructure',
    tool: { name: 'bwesterb/mtc + OpenSSL', url: 'https://github.com/bwesterb/mtc' },
  },
  {
    id: 'cloud-kms',
    title: 'Cloud KMS Key Wrapping',
    emoji: '🔑',
    useCase:
      'Demonstrate ML-KEM-768 key encapsulation with OpenSSL 3.6 — the key-wrapping pattern cloud KMS services (AWS, Azure, GCP) use to protect data encryption keys with a quantum-safe KEM — compared against classical RSA-OAEP wrapping.',
    algorithms: ['ML-KEM-768', 'Encap/Decap'],
    difficulty: 'beginner',
    trackId: 'infrastructure',
    tool: { name: 'OpenSSL', url: 'https://www.openssl.org' },
  },
  {
    id: 'secrets-vault',
    title: 'Zero-Trust Secrets Transit',
    emoji: '🔐',
    useCase:
      "Encrypt secrets through OpenBao's transit engine while the client↔OpenBao TLS channel negotiates X25519MLKEM768. PQC protects the secret IN TRANSIT only — the transit KEK itself is AES-256-GCM (no asymmetric PQC inside the engine).",
    algorithms: ['ML-KEM-768', 'OpenBao'],
    difficulty: 'intermediate',
    trackId: 'infrastructure',
    tool: { name: 'OpenBao', url: 'https://openbao.org/' },
  },
  {
    id: 'smime',
    title: 'Secure Email (S/MIME)',
    emoji: '📧',
    useCase:
      'Compare legacy RSA-2048 S/MIME encryption sequences against open-source ML-DSA & ML-KEM cryptographic integration protecting long-lived email archives.',
    algorithms: ['ML-DSA-65', 'ML-KEM-768'],
    difficulty: 'intermediate',
    trackId: 'infrastructure',
    tool: { name: 'OpenSSL 3.6.2 smime', url: 'https://github.com/openssl/openssl' },
  },
  {
    id: 'wireguard',
    title: 'Modern Transport Tunnels',
    emoji: '🚇',
    useCase:
      'Protect WireGuard (wireguard-go) tunnel establishment with Rosenpass — a production PQC-VPN daemon that runs a real ML-KEM-768 exchange and rotates the WireGuard PreSharedKey every ~2 minutes, defeating "Harvest Now, Decrypt Later".',
    algorithms: ['ML-KEM-768', 'Wireguard'],
    difficulty: 'intermediate',
    trackId: 'infrastructure',
    tool: { name: 'Rosenpass + wireguard-go', url: 'https://rosenpass.eu' },
  },
  {
    id: 'cbom-compliance',
    title: 'CBOM Compliance Audit — PQC Readiness Scoring',
    emoji: '✅',
    useCase:
      'Scan the full sandbox container with cdxgen (--type os --include-crypto) to generate a real CycloneDX 1.6 CBOM covering every installed crypto library and tool. Evaluate it against CNSA 2.0 and NIST IR 8547 policies using OPA / Rego. Compare a pre-migration classical state (high at-risk count) against a post-migration PQC state to quantify compliance progress. Reuses the CBOM produced by scenario 16 if run within 30 minutes.',
    algorithms: ['CBOM CycloneDX 1.6', 'CNSA 2.0', 'NIST IR 8547'],
    difficulty: 'advanced',
    trackId: 'supply-chain',
    tool: { name: 'cdxgen + OPA', url: 'https://github.com/CycloneDX/cdxgen' },
  },
  {
    id: 'tpm-pqc-migration',
    title: 'TPM 2.0 → PQC Migration',
    emoji: '🔐',
    useCase:
      'Walk the TCG TPM 2.0 V1.85 key hierarchy and see the concrete cost of migrating each key role (EK / SRK / AIK / IDevID) to post-quantum algorithms. Every key is produced twice — once by the real pqctoday-tpm libtpms engine (TPM2_CreatePrimary wire protocol) and once by pqctoday-hsm (softhsmv3 via PKCS#11 v3.2) — then cross-verified so users see both trust roots agree on ML-DSA-65 (1952 B pk, 3309 B sig) and ML-KEM-768 (1184 B pk, 32 B shared secret).',
    algorithms: ['TPM 2.0 V1.85', 'ML-DSA-65', 'ML-KEM-768', 'softhsmv3'],
    difficulty: 'advanced',
    trackId: 'supply-chain',
    tool: { name: 'pqctoday-tpm + pqctoday-hsm', url: 'https://github.com/pqctoday/pqctoday-tpm' },
  },
  {
    id: 'supply-chain-signing',
    title: 'Supply Chain Signing — Quantum-Safe Container Provenance',
    emoji: '📦',
    useCase:
      'Demonstrate post-quantum software signing with the forked Sigstore cosign (v3.0.6 + ML-DSA-65) — sign a blob/manifest with an HSM-backed ML-DSA-65 key, verify it, and attach an SBOM attestation. Rekor transparency-log upload is OFF (Rekor has no ML-DSA entry type yet), disclosed honestly. Protects supply-chain integrity against quantum signature forgery per EO 14028 and SLSA Level 3.',
    algorithms: ['ML-DSA-65', 'Sigstore / cosign', 'SLSA L3'],
    difficulty: 'advanced',
    trackId: 'supply-chain',
    tool: {
      name: 'Sigstore cosign (PQCToday ML-DSA fork)',
      url: 'https://github.com/sigstore/cosign',
    },
  },
  {
    id: 'sequoia',
    title: 'PGP Code Signing (Sequoia)',
    emoji: '🦅',
    useCase:
      'Produce a real RFC 9580 v6 OpenPGP signature with an ML-DSA-65 + Ed25519 composite key (public-key-algorithm 30, draft-ietf-openpgp-pqc) generated and held inside SoftHSMv3 — signing software artifacts via the opgpkcs11 bridge, with the private key never leaving the HSM.',
    algorithms: ['ML-DSA-65', 'OpenPGP v6', 'HSM-backed'],
    difficulty: 'intermediate',
    trackId: 'supply-chain',
    tool: {
      name: 'Sequoia sq + opgpkcs11 (openpgp-pkcs11-sequoia)',
      url: 'https://sequoia-pgp.org',
    },
  },
  {
    id: 'crypto-discovery',
    title: 'Crypto Discovery & CBOM',
    emoji: '🔍',
    useCase:
      'Scan the sandbox infrastructure with cdxgen (CycloneDX CBOM generator), testssl.sh, and ssh-audit to produce a complete Cryptographic Bill of Materials — covering installed libraries, runtime-negotiated TLS, and SSH algorithms. Step zero of any PQC migration.',
    algorithms: ['CBOM', 'cdxgen', 'testssl.sh'],
    difficulty: 'advanced',
    trackId: 'quantum',
    tool: { name: 'cdxgen + testssl.sh + ssh-audit', url: 'https://github.com/CycloneDX/cdxgen' },
  },
  {
    id: 'pqctoday-kmip',
    title: 'PQCToday KMIP 3.0 KMS',
    emoji: '🏢',
    useCase:
      'Drive a real crypto-agile KMIP key lifecycle with pqctoday-kmip (Rust, MIT) backed by softhsmrustv3 — CreateKeyPair → Activate → Sign for ML-DSA-65, and CreateKeyPair → Activate → Encapsulate → Decapsulate for ML-KEM-768. The server speaks KMIP ProtocolVersion 3.0; note that KMIP 3.0 is still an OASIS Committee Specification Draft (the latest ratified standard is 2.1) and the PQC algorithm tags come from KMIP Working Draft 19.',
    algorithms: ['ML-DSA/ML-KEM', 'KMIP 3.0 (OASIS draft / PQC WD19)'],
    difficulty: 'advanced',
    trackId: 'secrets-kms',
    tool: {
      name: 'pqctoday-kmip (Rust KMIP 3.0)',
      url: 'https://github.com/pqctoday/pqctoday-kmip',
    },
  },
  {
    id: 'sops',
    title: 'GitOps Secrets (SOPS)',
    emoji: '🗝️',
    useCase:
      'Encrypt GitOps secrets with SOPS + age using the X-Wing hybrid KEM (X25519 + ML-KEM-768) via the age-plugin-pqctoday recipient, HSM-backed by softhsmv3 — protecting infrastructure-as-code secrets from harvest-now-decrypt-later attacks.',
    algorithms: ['X-Wing', 'ML-KEM-768', 'SOPS'],
    difficulty: 'intermediate',
    trackId: 'secrets-kms',
    tool: { name: 'SOPS + age + age-plugin-pqctoday', url: 'https://github.com/getsops/sops' },
  },
  {
    id: 'browser-tls',
    title: 'Browser ML-KEM Handshake',
    emoji: '🌐',
    useCase:
      'Drive headless Chromium to connect to the nginx TLS endpoint and compare a classical X25519 handshake vs a hybrid X25519MLKEM768 handshake. tcpdump captures the live ClientHello/ServerHello exchange in the terminal. Auth uses ECDSA P-256 in both runs — ML-DSA server certs are not yet supported by browsers.',
    algorithms: ['X25519MLKEM768', 'Chromium'],
    difficulty: 'intermediate',
    trackId: 'web',
    tool: { name: 'Playwright + Chromium', url: 'https://playwright.dev' },
  },
  {
    id: 'migration-impact',
    title: 'Migration Impact Analysis',
    emoji: '📊',
    useCase:
      'Measure the real-world performance impact of migrating from classical to PQC TLS — handshake latency, certificate sizes, and bandwidth expansion — with an ephemeral OpenSSL s_server: classical (RSA-2048 + X25519) vs PQC (ML-DSA-65 + X25519MLKEM768).',
    algorithms: ['Benchmark', 'Classical → PQC'],
    difficulty: 'intermediate',
    trackId: 'web',
    tool: { name: 'OpenSSL', url: 'https://www.openssl.org' },
  },
  {
    id: 'haproxy',
    title: 'Enterprise Edge Load-Balancing',
    emoji: '⚖️',
    useCase:
      'Deploy HAProxy configured with hybrid ML-KEM/ECDHE bindings to measure Post-Quantum TLS handshake performance under heavy concurrent edge load.',
    algorithms: ['ML-KEM-768', 'HAProxy 3.0'],
    difficulty: 'advanced',
    trackId: 'web',
    tool: { name: 'HAProxy', url: 'https://haproxy.org' },
  },
  {
    id: 'ab-handshake-bench',
    title: 'A/B TLS Handshake Benchmark',
    emoji: '⚡',
    useCase:
      'Measure concurrent TLS 1.3 handshake throughput with Apache Bench against ephemeral nginx (session resumption OFF, so requests/sec ≈ full handshakes/sec): classical RSA-2048 + X25519 vs post-quantum ML-DSA-65 cert + X25519MLKEM768 hybrid KEX. The negotiated group is proven from nginx $ssl_curve telemetry.',
    algorithms: ['ML-DSA-65', 'X25519MLKEM768', 'Benchmark'],
    difficulty: 'advanced',
    trackId: 'web',
    tool: {
      name: 'Apache Bench (ab) + nginx + OpenSSL',
      url: 'https://httpd.apache.org/docs/2.4/programs/ab.html',
    },
  },
  {
    id: 'pqcflow',
    title: 'PQC Network Traffic Analysis',
    emoji: '📡',
    useCase:
      'Capture live TLS traffic on the loopback and run pqc-flow (CipherIQ) to identify which flows are quantum-safe (X25519MLKEM768) vs classical-at-risk (X25519, RSA) — the zero-disruption first step of any PQC network migration. This sandbox run exercises TLS only; pqc-flow also classifies SSH/QUIC, but that traffic is not generated here.',
    algorithms: ['Passive Discovery', 'PCAP'],
    difficulty: 'intermediate',
    trackId: 'web',
    tool: { name: 'pqc-flow', url: 'https://github.com/CipherIQ/pqc-flow' },
  },
  {
    id: 'api-security-jwt',
    title: 'Post-Quantum JWT Identity Constraints',
    emoji: '🛂',
    useCase:
      'Sign JSON Web Tokens with ML-DSA-65 using OpenSSL raw signatures and measure the impact on HTTP request-header limits: the ~4.5 KB token clears nginx (8 KB) but is rejected by a 4 KB cloud-WAF header cap.',
    algorithms: ['ML-DSA-65', 'Header bloat'],
    difficulty: 'advanced',
    trackId: 'applications',
    tool: { name: 'OpenSSL (raw JOSE signing)', url: 'https://www.openssl.org' },
  },
  {
    id: 'stepca',
    title: 'Automated CA (Step-CA)',
    emoji: '🪜',
    useCase:
      'Deploy Smallstep step-ca with PQC-enabled certificate issuance, contrasting classical RSA ACME workflows against post-quantum ML-DSA-65 automated certificate management.',
    algorithms: ['ML-DSA-65', 'ACME'],
    difficulty: 'intermediate',
    trackId: 'applications',
    tool: {
      name: 'step-ca (PQCToday SoftCAS fork)',
      url: 'https://github.com/smallstep/certificates',
    },
  },
  {
    id: 'database-postgres',
    title: 'PostgreSQL TLS Hardening',
    emoji: '🐘',
    useCase:
      'Migrate PostgreSQL client-server TLS from a classical RSA-2048 cert + prime256v1 ECDHE to an ML-DSA-65 server cert over the X25519MLKEM768 hybrid group, protecting database traffic from harvest-now-decrypt-later attacks.',
    algorithms: ['ML-KEM-768', 'ML-DSA-65 cert', 'PostgreSQL'],
    difficulty: 'intermediate',
    trackId: 'applications',
    tool: { name: 'PostgreSQL', url: 'https://www.postgresql.org' },
  },
  {
    id: 'firmware-hss',
    title: 'Firmware Verification (HSS)',
    emoji: '💾',
    useCase:
      'Secure IoT endpoint firmware updates with NIST SP 800-208 Stateful Hash-Based Signatures (HSS/LMS), generated and verified inside SoftHSMv3 via PKCS#11 CKM_HSS — full keygen → sign → verify, where each signature consumes a one-time LMS leaf (the budget decrements).',
    algorithms: ['HSS / LMS', 'Stateful Signature'],
    difficulty: 'advanced',
    trackId: 'applications',
    tool: {
      name: 'SoftHSMv3 (PKCS#11 CKM_HSS) + OpenSSL',
      url: 'https://github.com/pqctoday/softhsmv3',
    },
  },
  {
    id: 'osslsigncode',
    title: 'Code Signing (osslsigncode)',
    emoji: '🔏',
    useCase:
      'Sign Windows PE binaries using osslsigncode with classical RSA vs post-quantum ML-DSA-65, demonstrating the supply-chain implications of harvest-now-decrypt-later on software distribution.',
    algorithms: ['ML-DSA-65', 'PE/Authenticode'],
    difficulty: 'intermediate',
    trackId: 'applications',
    tool: { name: 'osslsigncode', url: 'https://github.com/mtrojnar/osslsigncode' },
  },
  {
    id: 'iot-mqtt',
    title: 'Lightweight MQTT Telemetry',
    emoji: '📡',
    useCase:
      'Run a real Mosquitto 2.1.2 TLS broker (built against OpenSSL 3.6) and compare a classical ECDSA-P256 / secp256r1 arm against a PQC ML-DSA-65 cert / X25519MLKEM768 KEM arm — driving a live TLS 1.3 handshake plus end-to-end pub/sub over TLS in each. WHY IT MATTERS: MQTT telemetry from sensors, meters, and medical/industrial devices is a prime harvest-now-decrypt-later (HNDL) target — long-lived deployments mean traffic captured today can be decrypted once a CRQC exists, and firmware that ships classical-only crypto may outlive the quantum transition. The PQC arm moves the key exchange to the NIST ML-KEM hybrid group (quantum-safe) while the cost (larger ML-DSA-65 cert, ~1KB KEM ciphertext, broker memory) is exactly what constrained-device migration planning must budget for.',
    algorithms: ['ML-KEM-768', 'Battery (estimate)'],
    difficulty: 'intermediate',
    trackId: 'applications',
    tool: { name: 'Eclipse Mosquitto', url: 'https://mosquitto.org/' },
  },
]

export const SANDBOX_TRACKS: SandboxTrack[] = [
  {
    id: 'protocol-simulation',
    label: 'Protocol Simulation',
    subtitle:
      'Interactive hardware telemetry for OpenSSL TLS 1.3, OpenSSH, IKEv2 VPN, and WASM TPM 2.0 PQC',
    difficulty: 'Intermediate',
  },
  {
    id: 'infrastructure',
    label: 'Cryptographic Infrastructure',
    subtitle:
      'PKI chain of trust, certificate validation, hybrid migration path, cloud KMS, and foundational key stacks',
    difficulty: 'Beginner → Intermediate',
  },
  {
    id: 'supply-chain',
    label: 'Supply Chain & Compliance',
    subtitle:
      'CNSA 2.0 CBOM audit with cdxgen + OPA, TPM 2.0 PQC migration, container provenance, and PGP code signing',
    difficulty: 'Advanced',
  },
  {
    id: 'quantum',
    label: 'Crypto Discovery',
    subtitle:
      'Scan running systems with cdxgen + testssl.sh to produce a CycloneDX CBOM and surface at-risk algorithms',
    difficulty: 'Advanced',
  },
  {
    id: 'secrets-kms',
    label: 'Secrets & Key Management',
    subtitle:
      'KMIP 3.0 PQC key lifecycle with pqctoday-kmip + SoftHSMv3, and GitOps secret encryption with SOPS + age',
    difficulty: 'Intermediate',
  },
  {
    id: 'web',
    label: 'Web & Network Security',
    subtitle:
      'Browser TLS negotiation, migration impact quantification, HAProxy edge-termination, A/B handshake benchmarking, and live PQC traffic analysis',
    difficulty: 'Intermediate',
  },
  {
    id: 'applications',
    label: 'Application Security',
    subtitle:
      'Microservice JWT auth, internal CA issuance, database TLS, firmware signing, and IoT MQTT',
    difficulty: 'Intermediate → Advanced',
  },
]
