// SPDX-License-Identifier: GPL-3.0-only
import { describe, it, expect } from 'vitest'
import { SANDBOX_SCENARIOS, SANDBOX_TRACKS, type SandboxTrackId } from './sandboxScenarios'
import { getSandboxNiceMapping } from './sandboxNiceMapping'
import { WORKSHOP_TOOLS, SANDBOX_TOOL_PREFIX } from '../components/Playground/workshopRegistry'

/**
 * Invariants that guard the sandbox data layer against the drift class that the
 * 2026-06-17 audit found: scenarios pointing at tracks/NICE/icon tables that
 * don't cover them. The data is generated by scripts/sync-sandbox-scenarios.ts;
 * these tests fail fast if a regeneration adds a track/scenario that a consumer
 * map hasn't been extended to cover.
 */
describe('sandbox scenario data invariants', () => {
  const trackIds = new Set<SandboxTrackId>(SANDBOX_TRACKS.map((t) => t.id))

  it('has a non-empty scenario + track set', () => {
    expect(SANDBOX_SCENARIOS.length).toBeGreaterThan(0)
    expect(SANDBOX_TRACKS.length).toBeGreaterThan(0)
  })

  it('every scenario id is unique', () => {
    const ids = SANDBOX_SCENARIOS.map((s) => s.id)
    expect(new Set(ids).size).toBe(ids.length)
  })

  it('every scenario references a declared track', () => {
    for (const s of SANDBOX_SCENARIOS) {
      expect(trackIds.has(s.trackId), `scenario '${s.id}' → unknown track '${s.trackId}'`).toBe(
        true
      )
    }
  })

  it('every declared track contains at least one scenario (no dead tracks)', () => {
    for (const track of SANDBOX_TRACKS) {
      const count = SANDBOX_SCENARIOS.filter((s) => s.trackId === track.id).length
      expect(count, `track '${track.id}' has no scenarios`).toBeGreaterThan(0)
    }
  })

  it('every scenario has a non-placeholder tool name + https url', () => {
    for (const s of SANDBOX_SCENARIOS) {
      expect(s.tool.name.trim().length, `scenario '${s.id}' tool.name empty`).toBeGreaterThan(0)
      expect(s.tool.url, `scenario '${s.id}' tool.url not https`).toMatch(/^https:\/\//)
      expect(s.algorithms.length, `scenario '${s.id}' has no algorithms`).toBeGreaterThan(0)
    }
  })

  it('every scenario resolves to a NICE mapping with competency areas + work roles', () => {
    for (const s of SANDBOX_SCENARIOS) {
      const ref = getSandboxNiceMapping(s.id)
      expect(ref, `scenario '${s.id}' has no NICE mapping`).toBeDefined()
      expect(
        ref!.competencyAreas.length,
        `scenario '${s.id}' NICE: no competency areas`
      ).toBeGreaterThan(0)
      expect(ref!.workRoles.length, `scenario '${s.id}' NICE: no work roles`).toBeGreaterThan(0)
      expect(ref!.tier).toBeTruthy()
    }
  })

  it('every scenario is wired into the workshop registry with an icon and launch tool', () => {
    const sandboxTools = WORKSHOP_TOOLS.filter((t) => t.category === 'Sandbox')
    expect(sandboxTools.length).toBe(SANDBOX_SCENARIOS.length)
    for (const s of SANDBOX_SCENARIOS) {
      const tool = sandboxTools.find((t) => t.id === `${SANDBOX_TOOL_PREFIX}${s.id}`)
      expect(tool, `scenario '${s.id}' has no sbx- workshop tool`).toBeDefined()
      expect(tool!.icon, `scenario '${s.id}' workshop tool has no icon`).toBeTruthy()
      expect(
        tool!.recommendedPersonas.length,
        `scenario '${s.id}' has no personas`
      ).toBeGreaterThan(0)
    }
  })

  it('the sandbox surfaces under every persona (no persona is fully excluded)', () => {
    const sandboxTools = WORKSHOP_TOOLS.filter((t) => t.category === 'Sandbox')
    const personas = [
      'executive',
      'developer',
      'architect',
      'researcher',
      'ops',
      'curious',
    ] as const
    for (const persona of personas) {
      const visible = sandboxTools.filter((t) => t.recommendedPersonas.includes(persona))
      expect(visible.length, `persona '${persona}' sees no sandbox scenarios`).toBeGreaterThan(0)
    }
  })
})
