// SPDX-License-Identifier: GPL-3.0-only
import {
  hasSubstantiveEnrichment,
  type EnrichmentLookup,
  type LibraryEnrichment,
} from './enrichmentParse'
import { libraryData } from './libraryData'
import { TIMELINE_LABEL_ALIASES } from './timelineLabelAliases.generated'
import timelineEnrichmentsJson from './generated/timelineEnrichments.generated.json'

export type { LibraryEnrichment, EnrichmentLookup }
export { hasSubstantiveEnrichment }

/**
 * Maps library downloadUrl → referenceId for cross-linking timeline events to library records.
 * Used by UI components to show "Also in Library →" badges when a timeline SourceUrl
 * matches a library document.
 */
export const timelineToLibraryRef: Record<string, string> = Object.fromEntries(
  libraryData.filter((item) => item.downloadUrl).map((item) => [item.downloadUrl, item.referenceId])
)

// The merged lookup over ALL timeline enrichment generations — the live
// directory and all three archive tiers — precomputed at build time by
// scripts/generate-timeline-enrichments.ts (27 Sep 2026). Reading the 40 raw
// markdown files here (34.2 MB) made this module an 86 MB app chunk; the merged
// result is 338 entries, 1.1 MB. The merge-all semantics are unchanged: the
// archive tiers must stay in (excluding them once lost 6 live, non-deprecated
// rows — Brazil:ITI, G7:G7 CEG, Germany:BSI, Hong Kong:HKMA, Malaysia:NACSA,
// Singapore:CSA/GovTech/IMDA). timelineEnrichments.generated.test.ts proves the
// file equals mergeEnrichmentFiles over the raw files, key for key.
export const timelineEnrichments: EnrichmentLookup = timelineEnrichmentsJson as EnrichmentLookup

/**
 * Build the enrichment lookup key for a timeline document row.
 * Matches the key format generated by the enrichment script:
 * "{countryName}:{org} — {title}"
 */
export function getTimelineEnrichmentKey(countryName: string, org: string, title: string): string {
  return `${countryName}:${org} — ${title}`
}

/**
 * The enrichment for a timeline row: by its current label first, then by any
 * label the same event_id carried in an earlier CSV generation. Enrichment
 * sections are keyed by label, so a title edit used to orphan a row's
 * enrichment (timeline remediation r2 W-B).
 */
export function getTimelineEnrichment(
  eventId: string | undefined,
  countryName: string,
  org: string,
  title: string
): LibraryEnrichment | undefined {
  const direct = timelineEnrichments[getTimelineEnrichmentKey(countryName, org, title)]
  if (direct || !eventId) return direct
  // eslint-disable-next-line security/detect-object-injection
  for (const label of TIMELINE_LABEL_ALIASES[eventId] ?? []) {
    // eslint-disable-next-line security/detect-object-injection
    const hit = timelineEnrichments[label]
    if (hit) return hit
  }
  return undefined
}
