// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-timeline-facts.mjs from timeline_06232026_r3.csv — DO NOT EDIT BY HAND.
// Edit the timeline CSV and re-run `npm run gen:timeline-facts` (runs in prebuild).
// Single source of truth: the timeline reference CSV.

/** Each country's canonical PQC migration deadline — the row tagged
 *  `is_sim_deadline=true` in the timeline CSV. Untagged countries fall back to
 *  the Q-Day anchor in moscaClock. */
export const TIMELINE_COUNTRY_DEADLINE_YEAR: Record<string, number> = {
  AU: 2030, // Legacy Asymmetric Crypto Disallowed — Full PQC Transition
  CA: 2031, // High Priority Systems Complete
  DE: 2030, // Critical Applications PQC — Hybrid No Longer Required
  EU: 2030, // High-Risk Systems Secured
  FR: 2027, // PQC Qualification Requirement
  IN: 2033, // Full Nationwide PQC Adoption
  JP: 2035, // Government PQC Transition Deadline
  KR: 2035, // Full PQC Roadmap Complete
  UK: 2035, // Full PQC Compliance
  US: 2030, // Key-Establishment Migration Deadline (June 2026 EO)
}

/** Per-country scenario milestone years, from rows tagged `sim_milestone` in the
 *  timeline CSV (e.g. 'hndl-critical', 'tnfl-critical', 'governance'). Powers the
 *  scenario-configurable simulation; untagged milestones (general-asset, governance)
 *  are derived in scenarioConfig. */
export const TIMELINE_COUNTRY_MILESTONES: Record<string, Partial<Record<string, number>>> = {
  US: { 'hndl-critical': 2030, 'tnfl-critical': 2031 },
}
