// SPDX-License-Identifier: GPL-3.0-only
// GENERATED by scripts/gen-timeline-facts.mjs from every timeline_*.csv generation — DO NOT EDIT BY HAND.

/** event_id → every "{Country}:{OrgName} — {Title}" label the row has carried. */
export const TIMELINE_LABEL_ALIASES: Record<string, readonly string[]> = {
  'acpr-banque-de-france-post-quantum-cryptography-transition-r': [
    'France:ACPR/Banque de France — Post-Quantum Cryptography Transition Roadmap Declaration',
  ],
  'african-union-auc-malabo-convention-enters-into-force': [
    'African Union:AUC — Malabo Convention Enters Into Force',
  ],
  'australia-apra-system-risk-outlook-flags-quantum-computing-risk': [
    'Australia:APRA — System Risk Outlook Flags Quantum Computing Risk',
  ],
  'australia-asd-acsc-annual-cyber-threat-report-2024-25-pqc-as-a-national-priority': [
    'Australia:ASD — ACSC Annual Cyber Threat Report 2024–25 — PQC as a National Priority',
    "Australia:ASD — ACSC Annual Cyber Threat Report 2024–25 — Prepare for PQC as one of 4 'Big Moves'",
  ],
  'australia-asd-asd-full-migration-phase': ['Australia:ASD — ASD Full Migration Phase'],
  'australia-asd-commonwealth-cyber-security-posture-in-2025': [
    'Australia:ASD — Commonwealth Cyber Security Posture in 2025',
  ],
  'australia-asd-critical-systems-migration-start': [
    'Australia:ASD — Critical Systems Migration Start',
  ],
  'australia-asd-initial-pqc-planning-guide': ['Australia:ASD — Initial PQC Planning Guide'],
  'australia-asd-ism-december-2024-update': ['Australia:ASD — ISM December 2024 Update'],
  'australia-asd-ism-june-2025-cryptography-guidelines-update': [
    'Australia:ASD — ISM June 2025 Cryptography Guidelines Update',
  ],
  'australia-asd-legacy-asymmetric-crypto-disallowed-full-pqc-transition': [
    'Australia:ASD — Legacy Asymmetric Crypto Disallowed — Full PQC Transition',
    'Australia:ASD — Quantum-Vulnerable Asymmetric Algorithms (DH, ECDH, ECDSA, RSA) Not Approved Beyond 2030',
  ],
  'australia-asd-migration-planning-phase': ['Australia:ASD — Migration Planning Phase'],
  'australia-asd-pqc-planning-guide-updated': ['Australia:ASD — PQC Planning Guide Updated'],
  'australia-asd-traditional-crypto-prohibited': ['Australia:ASD — Traditional Crypto Prohibited'],
  'australia-disr-national-quantum-strategy': ['Australia:DISR — National Quantum Strategy'],
  'bahrain-ncsc-national-quantum-safe-deployment': [
    'Bahrain:NCSC — National Quantum-Safe Deployment',
  ],
  'bank-of-israel-banking-system-preparedness-for-quantum-compu': [
    'Israel:Bank of Israel — Banking System Preparedness for Quantum Computing Cyber Risks',
  ],
  'bis-bis-paper-158-quantum-roadmap': ['BIS:BIS — Paper 158 Quantum Roadmap'],
  'brazil-bacen-lift-papers-post-quantum-cryptography-feasibility-study-for-pix': [
    'Brazil:BACEN — LIFT Papers Post-Quantum Cryptography Feasibility Study for Pix',
  ],
  'brazil-iti-icp-brasil-mandates-ml-dsa-and-ml-kem-certificate-standards': [
    'Brazil:ITI — ICP-Brasil Adds ML-DSA and ML-KEM to Its Cryptographic Standards (DOC-ICP-01.01 v6.0)',
    'Brazil:ITI — ICP-Brasil Mandates ML-DSA and ML-KEM Certificate Standards',
  ],
  'bsi-vs-it-umstellungsfristen-fuer-post-quanten-kryptografie': [
    'Germany:BSI — BSI: VS-IT Umstellungsfristen fuer Post-Quanten-Kryptografie vereinbart',
  ],
  'canada-btq-technologies-bitcoin-quantum-testnet-launch': [
    'Canada:BTQ Technologies — Bitcoin Quantum Testnet Launch',
  ],
  'canada-cccs-cccs-pqc-migration-roadmap-published': [
    'Canada:CCCS — CCCS PQC Migration Roadmap Published',
  ],
  'canada-cccs-departmental-planning-phase': ['Canada:CCCS — Departmental Planning Phase'],
  'canada-cccs-departmental-pqc-migration-plans-due': [
    'Canada:CCCS — Departmental PQC Migration Plans Due',
  ],
  'canada-cccs-full-gc-migration-complete': ['Canada:CCCS — Full GC Migration Complete'],
  'canada-cccs-high-priority-migration-phase': ['Canada:CCCS — High Priority Migration Phase'],
  'canada-cccs-high-priority-systems-complete': ['Canada:CCCS — High Priority Systems Complete'],
  'canada-cccs-itsp-40-111-v4-pqc-algorithms-approved': [
    'Canada:CCCS — ITSP.40.111 v4 Adds NIST PQC Algorithms',
    'Canada:CCCS — ITSP.40.111 v4 PQC Algorithms Approved',
  ],
  'canada-cccs-remaining-systems-migration': ['Canada:CCCS — Remaining Systems Migration'],
  'canada-ised-pqc-best-practices-published': ['Canada:ISED — PQC Best Practices Published'],
  'canada-osfi-guideline-b-13-technology-and-cyber-risk-managem': [
    'Canada:OSFI — Guideline B-13 — Technology and Cyber Risk Management',
  ],
  'canada-tbs-spin-notice-published': ['Canada:TBS — SPIN Notice Published'],
  'central-bank-of-jordan-quantum-resistant-encryption-roadmap': [
    'Jordan:Central Bank of Jordan — Quantum-Resistant Encryption Roadmap for the Financial Sector',
  ],
  'chile-chile-govt-national-quantum-strategy-launched': [
    'Chile:Chile Govt — National Quantum Strategy Launched',
  ],
  'china-cacr-cacr-pqc-competition-results': ['China:CACR — CACR PQC Competition Results'],
  'china-china-telecom-hybrid-quantum-safe-system-launched': [
    'China:China Telecom — Hybrid Quantum-Safe System Launched',
  ],
  'china-iccs-ngcc-algorithm-evaluation': ['China:ICCS — NGCC Algorithm Evaluation'],
  'china-iccs-ngcc-financial-sector-pqc-migration-phase': [
    'China:ICCS — NGCC Financial-Sector PQC Migration Phase',
  ],
  'china-iccs-ngcc-program-launched': ['China:ICCS — NGCC Program Launched'],
  'czech-republic-czqci-czqci-euroqci-backbone-launched': [
    'Czech Republic:CZQCI — CZQCI EuroQCI Backbone Launched',
    'Czech Republic:CZQCI — CZQCI EuroQCI Test Quantum Backbone Project',
  ],
  'czech-republic-nukib-cryptographic-recommendations': [
    'Czech Republic:NUKIB — Cryptographic Recommendations',
  ],
  'czech-republic-nukib-encryption-migration-complete': [
    'Czech Republic:NUKIB — Encryption Migration Complete',
  ],
  'czech-republic-nukib-key-establishment-migration': [
    'Czech Republic:NUKIB — Key Establishment Migration',
  ],
  'czech-republic-nukib-national-cyber-and-information-security': [
    'Czech Republic:NUKIB — National Cyber and Information Security Agency - EU Member States Warn of the Quantum Threat and Call for the Transition to Post-Quantum Cryptography',
  ],
  'czech-republic-nukib-national-cyber-and-information-security-2': [
    'Czech Republic:NUKIB — National Cyber and Information Security Agency - Letter of Support to the Position Paper on Quantum Key Distribution',
  ],
  'de-bsi-germany-quantum-secure-id-card-demonstrator': [
    'Germany:BSI — Germany Quantum-Secure ID Card Demonstrator',
  ],
  'denmark-transition-to-quantum-safe-cryptography-guidance': [
    'Denmark:SAMSIK — Transition to Quantum-Safe Cryptography',
  ],
  'dhs-post-quantum-cryptography': ['United States:DHS — DHS Post-Quantum Cryptography'],
  'egypt-mcit-law-151-2020-executive-regulations-issued': [
    'Egypt:MCIT — Law 151/2020 Executive Regulations Issued',
  ],
  'estonia-cybernetica-estonia-pqc-transition-led-by-cybernetica': [
    'Estonia:Cybernetica — Estonia PQC Transition Led by Cybernetica',
  ],
  'european-union-ec-critical-infrastructure-migration': [
    'European Union:EC — Critical Infrastructure Migration',
    'European Union:EC — High-Risk Use Cases Transitioned to PQC',
  ],
  'european-union-ec-cryptographic-inventory-mandate': [
    'European Union:EC — Cryptographic Inventory Mandate',
  ],
  'european-union-ec-eu-cyber-resilience-act-in-force': [
    'European Union:EC — EU Cyber Resilience Act In Force',
  ],
  'european-union-ec-eu-pqc-recommendation-published': [
    'European Union:EC — EU PQC Recommendation Published',
  ],
  'european-union-ec-eudi-wallet-available-all-member-states': [
    'European Union:European Commission — EUDI Wallet Available in All Member States',
  ],
  'european-union-ec-full-eu-pqc-transition': ['European Union:EC — Full EU PQC Transition'],
  'european-union-ec-high-priority-system-migration-begins': [
    'European Union:EC — High-Priority System Migration Begins',
  ],
  'european-union-ec-high-risk-systems-secured': ['European Union:EC — High-Risk Systems Secured'],
  'european-union-ec-member-state-strategy-initiation': [
    'European Union:EC — Member State Strategy Initiation',
  ],
  'european-union-eccg-agreed-cryptographic-algorithms-v2': [
    'European Union:ECCG — Agreed Cryptographic Algorithms v2',
    'European Union:ECCG — Agreed Cryptographic Mechanisms v2',
  ],
  'european-union-enisa-enisa-pqc-anticipating-threats': [
    'European Union:ENISA — ENISA PQC Anticipating Threats',
  ],
  'european-union-enisa-pqc-integration-study': ['European Union:ENISA — PQC Integration Study'],
  'european-union-eu-horizon-qarc-project-execution': [
    'European Union:EU Horizon — QARC Project Execution',
  ],
  'european-union-europol-qsff-call-to-action': ['European Union:Europol — QSFF Call to Action'],
  'european-union-nis-cg-coordinated-roadmap-v1-1': [
    'European Union:NIS CG — Coordinated Roadmap v1.1',
  ],
  'european-union-nis-cg-eu-pqc-survey-launched': [
    'European Union:NIS CG — EU PQC Survey Launched',
  ],
  'faa-request-for-information-post-quantum-cryptography-suppor': [
    'United States:FAA — FAA Request for Information: Post Quantum Cryptography Support (RFI 697DCK-26-RFI-PQC)',
  ],
  'finland-traficom-quantum-safe-encryption-transition-guidance': [
    'Finland:Traficom — Quantum-Safe Encryption Transition Guidance Published',
  ],
  'france-amf-sets-2026-priorities-names-quantum-computing-in-cyber-inspections': [
    'France:AMF — AMF Sets 2026 Priorities, Names Quantum Computing in Cyber Inspections',
  ],
  'france-anssi-bsi-nlncsa-se-joint-qkd-position-paper': [
    'France:ANSSI/BSI/NLNCSA/SE — Joint QKD Position Paper',
  ],
  'france-anssi-cea-leti-cesti-pqc-accreditation': [
    'France:ANSSI — CEA-Leti CESTI PQC Accreditation',
  ],
  'france-anssi-cryptographic-accreditation-doctrine-updated': [
    'France:ANSSI — Cryptographic Accreditation Doctrine Updated',
  ],
  'france-anssi-first-pqc-security-visas-issued': [
    'France:ANSSI — First PQC Security Visas Issued',
  ],
  'france-anssi-initial-pqc-position-paper': ['France:ANSSI — Initial PQC Position Paper'],
  'france-anssi-ipsec-dr-referential-update-planned': [
    'France:ANSSI — IPsec DR Referential Update (Planned)',
  ],
  'france-anssi-pg-083-cryptographic-guide-update-planned': [
    'France:ANSSI — PG-083 Cryptographic Guide Update (Planned)',
  ],
  'france-anssi-phase-1-pre-quantum-security': ['France:ANSSI — Phase 1 - Pre-Quantum Security'],
  'france-anssi-phase-2-hybridization-required': [
    'France:ANSSI — Phase 2 - Hybridization Required',
  ],
  'france-anssi-phase-3-standalone-pqc-optional': [
    'France:ANSSI — Phase 3 - Standalone PQC Optional',
  ],
  'france-anssi-pqc-faq-published': ['France:ANSSI — PQC FAQ Published'],
  'france-anssi-pqc-market-studies-published': ['France:ANSSI — PQC Market Studies Published'],
  'france-anssi-pqc-position-paper-follow-up': ['France:ANSSI — PQC Position Paper Follow-up'],
  'france-anssi-pqc-qualification-requirement': ['France:ANSSI — PQC Qualification Requirement'],
  'france-idemia-first-pqc-hardware-accelerator-announced': [
    'France:IDEMIA — First PQC Hardware Accelerator Announced',
  ],
  'g7-cybersecurity-working-group-preparing-for-the-post-quantum-era-call-to-action': [
    'G7:G7 Cybersecurity Working Group — Preparing for the Post-Quantum Era: A Call to Action',
  ],
  'g7-g7-ceg-g7-financial-sector-critical-systems-pqc-transition': [
    'G7:G7 CEG — G7 Financial Sector Critical Systems PQC Transition',
  ],
  'g7-g7-ceg-g7-financial-sector-pqc-roadmap': ['G7:G7 CEG — G7 Financial Sector PQC Roadmap'],
  'g7-g7-ceg-g7-statement-on-quantum-computing': ['G7:G7 CEG — G7 Statement on Quantum Computing'],
  'germany-adva-bsi-approved-400g-pqc-encryptor': [
    'Germany:Adva — BSI-Approved 400G PQC Encryptor',
  ],
  'germany-bsi-bsi-tr-02102-1-2026-edition': ['Germany:BSI — BSI TR-02102-1 2026 Edition'],
  'germany-bsi-bundesdruckerei-quantum-secure-id-card-demonstrator': [
    'Germany:BSI/Bundesdruckerei — Quantum-Secure ID Card Demonstrator',
  ],
  'germany-bsi-critical-applications-pqc-hybrid-no-longer-required': [
    'Germany:BSI — Critical Applications PQC — Hybrid No Longer Required',
    'Germany:BSI — Very High Protection Requirements — Transition to Quantum-Safe Mechanisms by End of 2030 Using Hybrid Form',
  ],
  'germany-bsi-dlr-quantity-initiative-launched': [
    'Germany:BSI/DLR — DLR × BSI Cooperation on QUANTITY Cryptanalysis Project',
    'Germany:BSI/DLR — QUANTITY Initiative Launched',
  ],
  'germany-bsi-eu-joint-statement-on-pqc': ['Germany:BSI — EU Joint Statement on PQC'],
  'germany-bsi-full-pqc-transition-standalone-algorithms-required': [
    'Germany:BSI — Full PQC Transition — Standalone Algorithms Required',
    'Germany:BSI — Transition to Quantum-Safe Signatures by 2035',
  ],
  'germany-bsi-hybrid-ipsec-and-ssh-required': [
    'Germany:BSI — BSI Sets 2031 End for Sole Use of Classical Key Agreement in IKEv2/IPsec',
    'Germany:BSI — Hybrid IPsec and SSH Required',
  ],
  'germany-bsi-hybrid-tls-required-for-classified-communications': [
    'Germany:BSI — BSI Signals Future Hybrid PQC Key Exchange for TLS',
  ],
  'germany-bsi-tr-02102-1-pqc-update': ['Germany:BSI — TR-02102-1 PQC Update'],
  'germany-infineon-first-cc-eal6-pqc-security-controller': [
    'Germany:Infineon — First CC EAL6 PQC Security Controller',
  ],
  'global-3gpp-sa3-3gpp-tr-33-938-pqc-transition-study': [
    'Global:3GPP SA3 — 3GPP TR 33.938 Cryptographic Inventory (5G System)',
    'Global:3GPP SA3 — 3GPP TR 33.938 PQC Transition Study',
  ],
  'global-ca-browser-forum-ballot-smc013-ml-dsa-for-s-mime-adopted': [
    'Global:CA/Browser Forum — Ballot SMC013 ML-DSA for S/MIME Adopted',
  ],
  'global-ethereum-foundation-post-quantum-security-top-priority': [
    'Global:Ethereum Foundation — Post-Quantum Security Top Priority',
  ],
  'global-ethereum-foundation-vitalik-buterin-publishes-pq-defense-roadmap': [
    'Global:Ethereum Foundation — Vitalik Buterin Publishes PQ Defense Roadmap',
  ],
  'global-fs-isac-fs-isac-pqc-migration-timeline-position-paper-published': [
    'Global:FS-ISAC — FS-ISAC PQC Migration Timeline Position Paper Published',
  ],
  'global-ibm-ibm-heron-r2-processor-available': ['Global:IBM — IBM Heron R2 Processor Available'],
  'global-ibm-ibm-kookaburra-processor-released': [
    'Global:IBM — IBM Kookaburra Processor Released',
  ],
  'global-ibm-ibm-next-gen-processor-development': [
    'Global:IBM — IBM Next-Gen Processor Development',
  ],
  'global-ibm-ibm-quantum-advantage-target': ['Global:IBM — IBM Quantum Advantage Target'],
  'global-ibm-quantum-safe-explorer-launched': ['Global:IBM — Quantum Safe Explorer Launched'],
  'global-microsoft-core-infrastructure-transition': [
    'Global:Microsoft — Core Infrastructure Transition',
  ],
  'global-microsoft-early-quantum-safe-adoption': [
    'Global:Microsoft — Early Quantum-Safe Adoption',
  ],
  'global-microsoft-majorana-1-quantum-chip': ['Global:Microsoft — Majorana 1 Quantum Chip'],
  'global-microsoft-microsoft-full-pqc-transition': [
    'Global:Microsoft — Microsoft Full PQC Transition',
  ],
  'global-microsoft-microsoft-qsp-roadmap-published': [
    'Global:Microsoft — Microsoft QSP Roadmap Published',
  ],
  'global-microsoft-quantum-safe-program-launch': [
    'Global:Microsoft — Quantum Safe Program Launch',
  ],
  'global-oasis-pkcs-11-v3-2-pqc-mechanisms-draft-published': [
    'Global:OASIS — PKCS#11 v3.2 PQC Mechanisms Draft Published',
  ],
  'global-openssl-openssl-3-5-0-native-pqc-release': [
    'Global:OpenSSL — OpenSSL 3.5.0 Native PQC Release',
  ],
  'global-pqshield-100th-research-paper-milestone': [
    'Global:PQShield — 100th Research Paper Milestone',
  ],
  'global-pqshield-carahsoft-government-partnership': [
    'Global:PQShield — Carahsoft Government Partnership',
  ],
  'global-pqshield-post-quantum-vpn-research-initiated': [
    'Global:PQShield — Post-Quantum VPN Research Initiated',
  ],
  'global-pqshield-ultrapq-suite-launched': ['Global:PQShield — UltraPQ-Suite Launched'],
  'global-quantinuum-helios-quantum-computer-commercial-launch': [
    'Global:Quantinuum — Helios Quantum Computer Commercial Launch',
  ],
  'global-tcg-tpm-2-0-pqc-library-specification-draft': [
    'Global:TCG — TPM 2.0 PQC Library Specification Draft',
  ],
  'global-tcg-tpm-2-0-v1-85-pqc-library-specification-draft': [
    'Global:TCG — TPM 2.0 Library Specification Version 185 Released',
    'Global:TCG — TPM 2.0 v1.85 PQC Library Specification Draft',
  ],
  'going-beyond-encryption-malaysia-rolls-out-quantum-cryptogra': [
    'Malaysia:NACSA — Going beyond encryption, Malaysia rolls out quantum cryptography sandbox to safeguard digital borders | Malay Mail',
    'Malaysia:NACSA — Malaysia Launches National Post-Quantum Cryptography Migration Plan and Quantum Cryptography Sandbox',
  ],
  'gsma-gsma-pq-03-v2-0-guidelines': ['GSMA:GSMA — PQ.03 v2.0 Guidelines'],
  'hong-kong-hkma-financial-sector-pqc-migration-complete': [
    'Hong Kong:HKMA — Financial Sector PQC Migration Complete',
    'Hong Kong:HKMA — HKMA target for full sectoral PQC readiness',
  ],
  'hong-kong-hkma-financial-sector-pqc-planning': [
    'Hong Kong:HKMA — Financial Sector PQC Planning',
  ],
  'hong-kong-hkma-fintech-2030-strategy-pqc-resilience-pillar': [
    'Hong Kong:HKMA — Fintech 2030 Strategy: PQC Resilience Pillar',
  ],
  'hong-kong-hkma-fintech-promotion-blueprint-published': [
    'Hong Kong:HKMA — Fintech Promotion Blueprint Published',
  ],
  'hong-kong-hkma-fintech-promotion-blueprint-quantum-preparedness-index': [
    'Hong Kong:HKMA — Fintech Promotion Blueprint: Quantum Preparedness Index',
  ],
  'hong-kong-hkma-hkma-fintech-adoption-report-pqc-commitment': [
    'Hong Kong:HKMA — HKMA Fintech Adoption Report: PQC Commitment',
  ],
  'hong-kong-hkma-pqc-readiness-assessment-required': [
    'Hong Kong:HKMA — PQC Readiness Assessment Required',
    'Hong Kong:HKMA — Quantum Preparedness Whitepaper and First Quantum Preparedness Index Launched',
  ],
  'hong-kong-legco-critical-infrastructure-cybersecurity-ordinance': [
    'Hong Kong:LegCo — Critical Infrastructure Cybersecurity Ordinance',
  ],
  'india-cert-in-bom-guidelines-expanded': [
    'India:CERT-In — BOM Guidelines Expanded',
    'India:CERT-In — BOM Guidelines Version 2.0 Cover QBOM & CBOM',
  ],
  'india-dst-nqm-cii-pqc-foundations-deadline': ['India:DST/NQM — CII PQC Foundations Deadline'],
  'india-dst-nqm-full-nationwide-pqc-adoption': ['India:DST/NQM — Full Nationwide PQC Adoption'],
  'india-dst-nqm-india-national-pqc-migration': ['India:DST/NQM — India National PQC Migration'],
  'india-dst-nqm-national-quantum-safe-roadmap-published': [
    'India:DST/NQM — National Quantum-Safe Roadmap Published',
  ],
  'india-tec-tec-technical-report-published': ['India:TEC — TEC Technical Report Published'],
  'indonesia-bssn-indonesia-bssn-pqc-migration-initiated': [
    'Indonesia:BSSN — Indonesia BSSN PQC Migration Initiated',
  ],
  'indonesia-bssn-national-pqc-migration-roadmap-task-force': [
    'Indonesia:BSSN — National PQC Migration Roadmap Task Force — Inaugural Meeting',
  ],
  'international-bis-paper-158-quantum-roadmap': ['International:BIS — Paper 158 Quantum Roadmap'],
  'international-etsi-etsi-ts-104-105-hybrid-pqc-standard-published': [
    'International:ETSI — ETSI TS 104 015 Hybrid PQC Standard Published',
  ],
  'international-etsi-iqc-etsi-iqc-qsc-conference-2026': [
    'International:ETSI/IQC — ETSI/IQC QSC Conference 2026',
  ],
  'international-gri-quantum-threat-timeline-report-2025': [
    'International:GRI — Quantum Threat Timeline Report 2025',
  ],
  'international-gsma-mobile-network-operator-pqc-transition-window': [
    'International:GSMA — Mobile Network Operator PQC Transition Window',
  ],
  'international-gsma-pq-03-v2-0-guidelines': ['International:GSMA — PQ.03 v2.0 Guidelines'],
  'international-ietf-draft-ietf-lamps-kyber-certificates': [
    'International:IETF — RFC 9935 ML-KEM Algorithm Identifiers for X.509 Certificates',
    'International:IETF — draft-ietf-lamps-kyber-certificates',
  ],
  'international-ietf-draft-ietf-tls-ecdhe-mlkem-hybrid-kex': [
    'International:IETF — draft-ietf-tls-ecdhe-mlkem Hybrid KEX',
  ],
  'international-ietf-rfc-9370-multiple-key-exchanges-in-ikev2': [
    'International:IETF — RFC 9370 Multiple Key Exchanges in IKEv2',
  ],
  'international-ietf-rfc-9794-pqc-hybrid-terminology': [
    'International:IETF — RFC 9794 PQC Hybrid Terminology',
  ],
  'international-ietf-rfc-9881-ml-dsa-in-x-509': ['International:IETF — RFC 9881 ML-DSA in X.509'],
  'international-ietf-rfc-9941-ssh-pq-hybrid-key-exchange': [
    'International:IETF — RFC 9941 SSH PQ-Hybrid Key Exchange',
  ],
  'international-iso-iec-iso-iec-sc27-pqc-standardization': [
    'International:ISO/IEC — ISO/IEC SC27 PQC Standardization',
  ],
  'international-itu-t-itu-t-x-1811-quantum-safe-security-guidelines-for-5g-publish': [
    'International:ITU-T — ITU-T X.1811 Quantum-Safe Security Guidelines for 5G Published',
  ],
  'international-pki-consortium-pki-consortium-pqc-conference-2025-conclusions': [
    'International:PKI Consortium — PKI Consortium PQC Conference 2025 Conclusions',
  ],
  'international-pqcc-pqcc-pqc-migration-roadmap-published': [
    'International:PQCC — PQCC PQC Migration Roadmap Published',
  ],
  'international-samsung-thales-ml-kem-embedded-secure-element-breakthrough': [
    'International:Samsung/Thales — ML-KEM Embedded Secure Element Breakthrough',
  ],
  'israel-boi-banking-pqc-directive': ['Israel:BOI — Banking PQC Directive'],
  'israel-incd-boi-inventory-planning-phase': ['Israel:INCD/BOI — Inventory & Planning Phase'],
  'israel-incd-government-threat-assessment': ['Israel:INCD — Government Threat Assessment'],
  'israel-incd-national-cybersecurity-strategy-2025-2028': [
    'Israel:INCD — National Cybersecurity Strategy 2025-2028',
  ],
  'israel-incd-pqc-readiness-guide-published': ['Israel:INCD — PQC Readiness Guide Published'],
  'italy-acn-pqc-guidance-published': ['Italy:ACN — PQC Guidance Published'],
  'japan-cryptrec-cryptrec-adds-ml-kem-to-ciphers-list': [
    'Japan:CRYPTREC — CRYPTREC Adds ML-KEM to Ciphers List',
  ],
  'japan-cryptrec-pqc-guideline-gl-2004-2022': ['Japan:CRYPTREC — PQC Guideline GL-2004-2022'],
  'japan-cryptrec-pqc-guideline-gl-2004-2022-2': ['Japan:CRYPTREC — PQC Guideline GL-2004-2022'],
  'japan-meti-nisc-cybersecurity-industry-policy-package': [
    'Japan:METI/NISC — Cybersecurity Industry Policy Package',
  ],
  'japan-nco-government-pqc-transition-deadline': [
    'Japan:NCO — Government PQC Transition Deadline',
  ],
  'japan-nec-nict-qkd-high-speed-data-integration-demo': [
    'Japan:NEC/NICT — QKD High-Speed Data Integration Demo',
  ],
  'japan-nedo-k-program-pqc-research': ['Japan:NEDO — K Program PQC Research'],
  'japan-nisc-critical-systems-migration': ['Japan:NISC — Critical Systems Migration'],
  'japan-nisc-pqc-migration-planning': [
    'Japan:CRYPTREC — PQC Migration Planning',
    'Japan:NISC — PQC Migration Planning',
  ],
  'jordan-cbj-jordan-financial-sector-pqc-roadmap': [
    'Jordan:CBJ — Jordan Financial Sector PQC Roadmap',
  ],
  'kenya-odpc-odpc-guidance-on-data-protection-by-design': [
    'Kenya:ODPC — Data Protection (General) Regulations, 2021 — Data Protection by Design',
    'Kenya:ODPC — ODPC Guidance on Data Protection by Design',
  ],
  'malaysia-nacsa-malaysia-national-pqc-migration': [
    'Malaysia:NACSA — Malaysia National PQC Migration',
  ],
  'malaysia-nacsa-national-pqc-migration-plan-published': [
    'Malaysia:NACSA — MyKriptografi Action Plan 2026–2030',
    'Malaysia:NACSA — National PQC Migration Plan Published',
  ],
  'my-pki-consortium-pki-consortium-pqc-conference-2025-conclusions': [
    'Malaysia:PKI Consortium — PKI Consortium PQC Conference 2025 Conclusions',
  ],
  'nato-nato-quantum-technologies-strategy': ['NATO:NATO — Quantum Technologies Strategy'],
  'nccoe-migration-to-post-quantum-cryptography': [
    'United States:NIST NCCoE — NCCoE Migration to Post-Quantum Cryptography',
  ],
  'ncsc-post-quantum-cryptography-pqc-migration-workshop-report': [
    'United Kingdom:NCSC — NCSC: Post-Quantum Cryptography (PQC) migration workshop report',
  ],
  'netherlands-aivd-pqc-migration-handbook-2nd-edition': [
    'Netherlands:AIVD — PQC Migration Handbook (2nd Edition)',
  ],
  'new-zealand-gcsb-ncsc-nzism-v3-8-updated': ['New Zealand:GCSB/NCSC — NZISM v3.8 Updated'],
  'new-zealand-gcsb-ncsc-nzism-v3-9-published': ['New Zealand:GCSB/NCSC — NZISM v3.9 Published'],
  'new-zealand-gcsb-ncsc-planning-phase': [
    'New Zealand:GCSB/NCSC — NZISM v3.9 Release',
    'New Zealand:GCSB/NCSC — Planning Phase',
  ],
  'new-zealand-gcsb-ncsc-transition-phase': [
    'New Zealand:GCSB/NCSC — NZISM v3.9 Release',
    'New Zealand:GCSB/NCSC — Transition Phase',
  ],
  'nigeria-ndpc-ndpa-general-application-directive-2025': [
    'Nigeria:NDPC — NDPA General Application Directive 2025',
  ],
  'nigeria-ndpc-nigeria-data-protection-act-2023-enacted': [
    'Nigeria:NDPC — Nigeria Data Protection Act 2023 Enacted',
  ],
  'norway-nsm-quantum-migration-guidance': [
    'Norway:NSM — Quantum Migration (Kvantemigrasjon) Guidance',
  ],
  'nsa-post-quantum-cybersecurity-resources': [
    'United States:NSA — NSA Post-Quantum Cybersecurity Resources',
  ],
  'poland-psnc-pionier-q-quantum-network-launched': [
    'Poland:PSNC — PIONIER-Q Quantum Network Launched',
  ],
  'rbi-india-q-safe-expert-committee-on-quantum-technology-risk': [
    'India:RBI — Q-SAFE Expert Committee on Quantum Technology Risk',
  ],
  'russia-tc26-post-quantum-cryptographic-mechanisms-working-gr': [
    'Russia:TC26 — Post-Quantum Cryptographic Mechanisms Working Group (WG 2.5)',
  ],
  'saudi-arabia-aramco-pasqal-first-quantum-computer-in-ksa': [
    'Saudi Arabia:Aramco/Pasqal — First Quantum Computer in KSA',
  ],
  'saudi-arabia-c4ir-quantum-economy-landscape-report': [
    'Saudi Arabia:C4IR — Quantum Economy Landscape Report',
  ],
  'saudi-arabia-nca-ecc-2-2024-cybersecurity-controls': [
    'Saudi Arabia:NCA — ECC-2:2024 Cybersecurity Controls',
  ],
  'saudi-arabia-nca-saudi-national-cryptographic-standards': [
    'Saudi Arabia:NCA — Saudi National Cryptographic Standards',
  ],
  'saudi-arabia-stc-stc-quantum-safe-framework-launched': [
    'Saudi Arabia:STC — STC Quantum-Safe Framework Launched',
  ],
  'singapore-csa-govtech-imda-quantum-safe-handbook-and-quantum-readiness-index-rel': [
    'Singapore:CSA/GovTech/IMDA — Draft Quantum-Safe Handbook Released for Public Consultation',
    'Singapore:CSA/GovTech/IMDA — Quantum-Safe Handbook and Quantum Readiness Index Released',
  ],
  'singapore-csa-mas-financial-sector-planning': ['Singapore:CSA/MAS — Financial Sector Planning'],
  'singapore-imda-nqsn-launched': ['Singapore:IMDA — NQSN+ Launched'],
  'singapore-mas-bdf-cross-border-pqc-experiment': [
    'Singapore:MAS/BdF — Cross-Border PQC Experiment',
  ],
  'singapore-mas-financial-sector-pqc-migration-plans-due': [
    'Singapore:MAS — Financial Sector PQC Migration Plans Due',
    'Singapore:MAS — MAS advisory on addressing cybersecurity risks associated with quantum',
  ],
  'singapore-mas-financial-sector-qkd-sandbox-completed': [
    'Singapore:MAS — Financial Sector QKD Sandbox Completed',
  ],
  'singapore-quantinuum-nqo-helios-quantum-computer-singapore-deployment': [
    'Singapore:Quantinuum/NQO — Helios Quantum Computer Singapore Deployment',
  ],
  'south-africa-ir-popia-enforcement-begins': ['South Africa:IR — POPIA Enforcement Begins'],
  'south-africa-sa-quti-sa-quti-quantum-communications-program': [
    'South Africa:SA QuTI — SA QuTI Quantum Communications Program',
  ],
  'south-korea-msit-full-pqc-roadmap-complete': ['South Korea:MSIT — Full PQC Roadmap Complete'],
  'south-korea-msit-k-pqc-master-plan-to-2035': ['South Korea:MSIT — K-PQC Master Plan to 2035'],
  'south-korea-msit-pilot-transition-phase': ['South Korea:MSIT — Pilot Transition Phase'],
  'south-korea-nis-kisa-kpqc-competition-results': [
    'South Korea:NIS/KISA — KpqC Competition Results',
  ],
  'spain-ccn-ccn-tec-009-post-quantum-transition': [
    'Spain:CCN — CCN-TEC 009 Post-Quantum Transition',
  ],
  'spain-ccn-four-phase-pqc-approach': [
    'Spain:CCN — Five-Phase PQC Transition Approach',
    'Spain:CCN — Four-Phase PQC Approach',
  ],
  'spain-ccn-pqc-transition-period': ['Spain:CCN — PQC Transition Period'],
  'spain-spain-govt-spain-quantum-technologies-strategy-eur-808m': [
    'Spain:Spain Govt — Spain Quantum Technologies Strategy (EUR 800M)',
    'Spain:Spain Govt — Spain Quantum Technologies Strategy (EUR 808M)',
  ],
  'spain-telefonica-telefonica-quantum-centre-of-excellence-opened': [
    'Spain:Telefonica — Telefonica Quantum Centre of Excellence Opened',
  ],
  'sweden-ncsc-national-recommendations-for-quantum-safe-crypto': [
    'Sweden:NCSC Sweden — National Recommendations for the Transition to Quantum-Safe Cryptography',
  ],
  'switzerland-ncsc-quantum-computers-and-post-quantum-cryptogr': [
    'Switzerland:NCSC Switzerland — Quantum Computers and Post-Quantum Cryptography — Technology Brief',
  ],
  'taiwan-moda-five-year-pqc-plan': ['Taiwan:MODA — Five-Year PQC Plan'],
  'taiwan-moda-interim-quantum-safe-milestone': ['Taiwan:MODA — Interim Quantum-Safe Milestone'],
  'thailand-ncsa-quantum-ready-2030-roadmap': ['Thailand:NCSA — Quantum-Ready 2030 Roadmap'],
  'uk-ico-quantum-computing-tech-horizons-report': [
    'United Kingdom:ICO — Quantum Computing (Tech Horizons Report)',
  ],
  'united-arab-emirates-adgm-tii-quantum-secure-communications-testbed': [
    'United Arab Emirates:ADGM/TII — Quantum-Secure Communications Testbed',
  ],
  'united-arab-emirates-desc-dubai-pqc-guideline-launched': [
    'United Arab Emirates:DESC — Dubai PQC Guideline Launched',
  ],
  'united-arab-emirates-tii-nist-additional-signatures-round-2-contributions': [
    'United Arab Emirates:TII — NIST Additional Digital Signature Schemes Round 2 candidates',
    'United Arab Emirates:TII — NIST Additional Signatures Round 2 Contributions',
  ],
  'united-arab-emirates-uae-csc-national-encryption-policy-approved': [
    'United Arab Emirates:UAE CSC — National Encryption Policy Approved',
  ],
  'united-arab-emirates-uae-csc-national-pqc-migration-program': [
    'United Arab Emirates:UAE CSC — National PQC Migration Program',
  ],
  'united-arab-emirates-uae-csc-uae-crypto-discovery-tool-and-pqc-index': [
    'United Arab Emirates:UAE CSC — UAE Crypto Discovery Tool and PQC Index',
  ],
  'united-kingdom-cmorg-financial-sector-pqc-guidance': [
    'United Kingdom:CMORG — Financial Sector PQC Guidance',
  ],
  'united-kingdom-dsit-cni-perspectives-report': ['United Kingdom:DSIT — CNI Perspectives Report'],
  'united-kingdom-ncsc-discovery-planning-phase': [
    'United Kingdom:NCSC — Discovery & Planning Phase',
  ],
  'united-kingdom-ncsc-full-pqc-compliance': [
    'United Kingdom:NCSC — Complete migration to PQC',
    'United Kingdom:NCSC — Full PQC Compliance',
  ],
  'united-kingdom-ncsc-ncsc-full-migration-phase': [
    'United Kingdom:NCSC — NCSC Full Migration Phase',
  ],
  'united-kingdom-ncsc-ncsc-pqc-migration-roadmap-published': [
    'United Kingdom:NCSC — NCSC PQC Migration Roadmap Published',
  ],
  'united-kingdom-ncsc-pqc-white-paper-updated': ['United Kingdom:NCSC — PQC White Paper Updated'],
  'united-kingdom-ncsc-pqc-whitepaper-published': [
    'United Kingdom:NCSC — PQC Whitepaper Published',
  ],
  'united-kingdom-ncsc-priority-migration-phase': [
    'United Kingdom:NCSC — Priority Migration Phase',
  ],
  'united-states-algorand-foundation-first-post-quantum-mainnet-transaction': [
    'United States:Algorand Foundation — First Post-Quantum Mainnet Transaction',
  ],
  'united-states-bitcoin-core-bip-360-pay-to-merkle-root-proposal': [
    'United States:Bitcoin Core — BIP-360 Pay-to-Merkle-Root Proposal',
  ],
  'united-states-ciena-1-6t-quantum-safe-optical-encryption': [
    'United States:Ciena — 1.6T Quantum-Safe Optical Encryption',
  ],
  'united-states-cisa-acdi-deployment-phase': ['United States:CISA — ACDI Deployment Phase'],
  'united-states-cisa-automated-pqc-discovery-strategy': [
    'United States:CISA — Automated PQC Discovery Strategy',
  ],
  'united-states-cisa-cisa-cbom-guidance-far-contractor-vdp-rule-due-eo-14412': [
    'United States:CISA — CISA CBOM Guidance & FAR Contractor VDP Rule Due (EO 14412)',
  ],
  'united-states-cisa-cisa-pqc-product-category-list-eo-14306-deadline': [
    'United States:CISA — CISA PQC Product Category List — EO 14306 Deadline',
  ],
  'united-states-cisa-cisa-pqc-product-category-list-publication': [
    'United States:CISA — CISA PQC Product Category List Publication',
  ],
  'united-states-cisa-federal-pqc-procurement-guidance': [
    'United States:CISA — Federal PQC Procurement Guidance',
  ],
  'united-states-cisa-pqc-considerations-for-ot': [
    'United States:CISA — PQC Considerations for OT',
  ],
  'united-states-congress-national-quantum-initiative-reauthorization-act': [
    'United States:Congress — National Quantum Initiative Reauthorization Act',
  ],
  'united-states-congress-quantum-computing-cybersecurity-preparedness-act': [
    'United States:Congress — Quantum Computing Cybersecurity Preparedness Act',
  ],
  'united-states-dod-dod-pqc-migration-memorandum': [
    'United States:DoD — DoD PQC Migration Memorandum',
  ],
  'united-states-dod-dod-pqc-migration-memorandum-2': [
    'United States:DoD — DoD PQC Migration Memorandum',
  ],
  'united-states-ethereum-foundation-strawmap-pqc-roadmap-published': [
    'United States:Ethereum Foundation — Strawmap PQC Roadmap Published',
  ],
  'united-states-far-council-far-council-proposed-rule-contractor-pqc-fips-complian': [
    'United States:FAR Council — FAR Council Proposed Rule — Contractor PQC/FIPS Compliance (EO 14412)',
  ],
  'united-states-federal-agencies-agency-pqc-migration-plans-due-to-omb-oncd-m-26-1': [
    'United States:Federal Agencies — Agency PQC Migration Plans Due to OMB/ONCD (M-26-15)',
  ],
  'united-states-federal-agencies-digital-signature-migration-deadline-eo-june-22-2': [
    'United States:Federal Agencies — Digital-Signature Migration Deadline (EO June 22 2026)',
  ],
  'united-states-federal-agencies-key-establishment-migration-deadline-eo-june-22-2': [
    'United States:Federal Agencies — Key-Establishment Migration Deadline (EO June 22 2026)',
  ],
  'united-states-google-google-cloud-ml-kem-default-and-chrome-mtc-program': [
    'United States:Google — Google Cloud ML-KEM Default and Chrome MTC Program',
  ],
  'united-states-google-google-pqc-migration-2029-timeline': [
    'United States:Google — Google PQC Migration 2029 Timeline',
  ],
  'united-states-gsa-gsa-pqc-buyer-guide-v1-0': ['United States:GSA — GSA PQC Buyer Guide v1.0'],
  'united-states-microsoft-nist-pqc-algorithms-in-windows-platform': [
    'United States:Microsoft — NIST PQC Algorithms in Windows Platform',
  ],
  'united-states-nist-112-bit-security-algorithms-fully-disallowed': [
    'United States:NIST — 112-bit Security Algorithms Fully Disallowed',
  ],
  'united-states-nist-112-bit-security-deprecated': [
    'United States:NIST — 112-bit Security Deprecated',
  ],
  'united-states-nist-additional-signatures-round-3-advances': [
    'United States:NIST — Additional Signatures Round 3 Advances',
  ],
  'united-states-nist-fips-203-204-205-published': [
    'United States:NIST — FIPS 203 Published',
    'United States:NIST — FIPS 203, 204, 205 Published',
  ],
  'united-states-nist-fips-206-fn-dsa-draft-submitted': [
    'United States:NIST — FIPS 206 (FN-DSA) Draft Submitted',
  ],
  'united-states-nist-hawk-withdrawn-from-additional-signatures-round-3': [
    'United States:NIST — HAWK Withdrawn from the Additional Signatures Process',
  ],
  'united-states-nist-hqc-selected-as-fifth-algorithm': [
    'United States:NIST — HQC Selected as Fifth Algorithm',
  ],
  'united-states-nist-hqc-standard-finalized-expected': [
    'United States:NIST — HQC Standard Finalized (Expected)',
  ],
  'united-states-nist-ir-8547-public-comments-published': [
    'United States:NIST — IR 8547 Public Comments Published',
  ],
  'united-states-nist-nccoe-cswp-48-pqc-migration-mappings-draft': [
    'United States:NIST NCCoE — CSWP 48 PQC Migration Mappings Draft',
  ],
  'united-states-nist-nccoe-pqc-interoperability-testing': [
    'United States:NIST NCCoE — PQC Interoperability Testing',
  ],
  'united-states-nist-nist-ir-8545-round-4-status-report': [
    'United States:NIST — NIST IR 8545 Round 4 Status Report',
  ],
  'united-states-nist-nist-ir-8547-ipd2-published': [
    'United States:NIST — NIST IR 8547 IPD2 Published',
  ],
  'united-states-nist-nist-ir-8547-transition-guidance-draft': [
    'United States:NIST — NIST IR 8547 Transition Guidance (Draft)',
  ],
  'united-states-nist-nist-pqc-migration-pilot-complete-eo-june-22-2026': [
    'United States:NIST — NIST PQC Migration Pilot Complete (EO June 22 2026)',
    'United States:NIST — NIST PQC Migration Pilot to Be Completed by December 31, 2027 (EO June 22 2026)',
  ],
  'united-states-nist-nist-sp-800-208-published-lms-xmss': [
    'United States:NIST — NIST SP 800-208 Published (LMS/XMSS)',
  ],
  'united-states-nist-nist-sp-800-227-kem-recommendations': [
    'United States:NIST — NIST SP 800-227 KEM Recommendations',
  ],
  'united-states-nist-nsa-cryptographic-inventory': [
    'United States:NIST/NSA — Cryptographic Inventory',
  ],
  'united-states-nist-sixth-pqc-standardization-conference': [
    'United States:NIST — Sixth PQC Standardization Conference',
  ],
  'united-states-nsa-cnsa-1-0-compliance-deadline-for-nss': [
    'United States:NSA — CNSA 1.0 Compliance Deadline for NSS',
    'United States:NSA — No CNSA 2.0 Transition Enforced Before December 31, 2025 for NIAP/CSfC-Validated NSS',
  ],
  'united-states-nsa-cnsa-2-0-algorithms-revised': [
    'United States:NSA — CNSA 2.0 Algorithms Revised',
  ],
  'united-states-nsa-cnsa-2-0-exclusive-network-signing': [
    'United States:NSA — CNSA 2.0 Exclusive - Network/Signing',
  ],
  'united-states-nsa-cnsa-2-0-exclusive-os-web-cloud': [
    'United States:NSA — CNSA 2.0 Exclusive - OS/Web/Cloud',
  ],
  'united-states-nsa-cnsa-2-0-published': ['United States:NSA — CNSA 2.0 Published'],
  'united-states-nsa-full-cnsa-2-0-transition-complete': [
    'United States:NSA — Full CNSA 2.0 Transition Complete',
  ],
  'united-states-nsa-large-pki-systems-migration': [
    'United States:NSA — Large PKI Systems Migration',
  ],
  'united-states-nsa-nss-acquisitions-cnsa-2-0-required': [
    'United States:NSA — NSS Acquisitions CNSA 2.0 Required',
  ],
  'united-states-nsa-nss-quantum-resistant-majority': [
    'United States:NSA — NSS Quantum Resistant Majority',
  ],
  'united-states-nsa-operating-systems-transition': [
    'United States:NSA — Operating Systems Transition',
  ],
  'united-states-nsa-software-firmware-signing-transition': [
    'United States:NSA — Software/Firmware Signing Transition',
  ],
  'united-states-nsa-traditional-networking-transition': [
    'United States:NSA — Traditional Networking Transition',
  ],
  'united-states-nsa-web-cloud-services-transition': [
    'United States:NSA — Web/Cloud Services Transition',
  ],
  'united-states-omb-m-23-02-cryptographic-inventory': [
    'United States:OMB — M-23-02 Cryptographic Inventory',
  ],
  'united-states-omb-omb-memorandum-m-26-15-published': [
    'United States:OMB — OMB Memorandum M-26-15 Published',
  ],
  'united-states-openssl-openssl-3-6-1-pqc-release': [
    'United States:OpenSSL — OpenSSL 3.6.1 PQC Release',
  ],
  'united-states-sandboxaq-aqtive-guard-fedramp-ready': [
    'United States:SandboxAQ — AQtive Guard FedRAMP Ready',
  ],
  'united-states-sandboxaq-aqtive-guard-pentagon-5-year-agreement': [
    'United States:SandboxAQ — AQtive Guard Pentagon 5-Year Agreement',
  ],
  'united-states-sandboxaq-mitre-lf-rwpqc-2025-conference': [
    'United States:SandboxAQ/MITRE/LF — RWPQC 2025 Conference',
  ],
  'united-states-sealsq-us-post-quantum-root-of-trust-service-launch': [
    'United States:SEALSQ — US Post-Quantum Root of Trust Service Launch',
  ],
  'united-states-white-house-executive-order-14144': [
    'United States:White House — Executive Order 14144',
  ],
  'united-states-white-house-executive-order-14306-issued': [
    'United States:White House — Executive Order 14306 Issued',
  ],
  'united-states-white-house-executive-order-14413-issued-quantum-innovation-qc-add': [
    'United States:White House — Executive Order 14413 Issued — Quantum Innovation / QC-ADDS',
  ],
  'united-states-white-house-nsm-10-published': ['United States:White House — NSM-10 Published'],
  'united-states-white-house-nspm-12-published': ['United States:White House — NSPM-12 Published'],
  'united-states-white-house-pqc-report-to-congress': [
    'United States:White House — PQC Report to Congress',
  ],
  'united-states-white-house-securing-the-nation-against-advanced-cryptographic-att': [
    'United States:White House — Securing the Nation Against Advanced Cryptographic Attacks (Executive Order, June 22 2026)',
  ],
  'uruguay-agesic-national-cybersecurity-strategy-2024-2030-commits-to-quantum-resistant-pki': [
    'Uruguay:AGESIC — National Cybersecurity Strategy 2024-2030 Commits to Quantum-Resistant PKI',
  ],
}
