// SPDX-License-Identifier: GPL-3.0-only
import {
  mergeEnrichmentFiles,
  hasSubstantiveEnrichment,
  type EnrichmentLookup,
  type LibraryEnrichment,
} from './libraryEnrichmentData'
import { libraryData } from './libraryData'

export type { LibraryEnrichment, EnrichmentLookup }
export { hasSubstantiveEnrichment }

/**
 * Maps library downloadUrl → referenceId for cross-linking timeline events to library records.
 * Used by UI components to show "Also in Library →" badges when a timeline SourceUrl
 * matches a library document.
 */
export const timelineToLibraryRef: Record<string, string> = Object.fromEntries(
  libraryData.filter((item) => item.downloadUrl).map((item) => [item.downloadUrl, item.referenceId])
)

// Reads all three archive tiers this dataset has accumulated, not just the live
// directory — same fix as src/data/maturityGovernanceData.ts (2026-08-07). This is a
// merge-all source (mergeEnrichmentFiles reads every dated file's own filename date,
// oldest to newest), so a file sitting in an archive dir was invisible to the glob
// even though its content was never superseded. Confirmed real loss: 6 live,
// non-deprecated timeline rows (Brazil:ITI, G7:G7 CEG, Germany:BSI, Hong Kong:HKMA,
// Malaysia:NACSA, Singapore:CSA/GovTech/IMDA) had no enrichment without this.
function loadTimelineEnrichments(): EnrichmentLookup {
  const modules = {
    ...import.meta.glob('./doc-enrichments/timeline_doc_enrichments_*.md', {
      query: '?raw',
      import: 'default',
      eager: true,
    }),
    ...import.meta.glob('./archive/timeline_doc_enrichments_*.md', {
      query: '?raw',
      import: 'default',
      eager: true,
    }),
    ...import.meta.glob('./doc-enrichments/archive/timeline_doc_enrichments_*.md', {
      query: '?raw',
      import: 'default',
      eager: true,
    }),
    ...import.meta.glob('./doc-enrichments/archive_v1/timeline_doc_enrichments_*.md', {
      query: '?raw',
      import: 'default',
      eager: true,
    }),
  } as Record<string, string>
  return mergeEnrichmentFiles(modules)
}

export const timelineEnrichments: EnrichmentLookup = loadTimelineEnrichments()

/**
 * Build the enrichment lookup key for a timeline document row.
 * Matches the key format generated by the enrichment script:
 * "{countryName}:{org} — {title}"
 */
export function getTimelineEnrichmentKey(countryName: string, org: string, title: string): string {
  return `${countryName}:${org} — ${title}`
}
