// SPDX-License-Identifier: GPL-3.0-only
/**
 * Export the current VPN simulator configuration as a downloadable bundle.
 * Produces a .zip containing strongswan.conf, ipsec.conf / swanctl.conf,
 * ipsec.secrets (for PSK mode), peer certs (for dual auth), and a README.
 */
import JSZip from 'jszip'
import { saveAs } from 'file-saver'
import type { IKEv2Mode } from '@/components/PKILearning/modules/VPNSSHModule/data/ikev2Constants'
import { EDUCATION_NOTICE, withEducationNoticeComment } from '@/data/educationNotice'

export interface VpnConfigExport {
  mode: IKEv2Mode
  authMode: 'psk' | 'dual'
  mtu: number
  allowFragmentation: boolean
  clientAlg: string
  clientSize: string
  clientClassAlg: string
  serverAlg: string
  serverSize: string
  serverClassAlg: string
  clientPsk: string
  serverPsk: string
  strongswanConfInit: string
  strongswanConfResp: string
  ipsecConfInit: string
  ipsecConfResp: string
  initiatorCertPem?: string | null
  responderCertPem?: string | null
  initiatorCkaId?: string | null
  responderCkaId?: string | null
}

const README = (cfg: VpnConfigExport) => `# PQC VPN Configuration Bundle

> **Notice — ${EDUCATION_NOTICE}**
>
> This bundle is a teaching artefact. The PSKs in \`ipsec.secrets\` were
> generated by a simulator in a browser tab and are not secrets; the peer
> certificates are self-signed by a simulated, unaudited token. Do not install
> this configuration on a host that carries real traffic, and do not reuse any
> key or PSK it contains.

Exported from the pqctoday-hub PKCS#11 VPN simulator.

## Selected configuration

- IKE mode: \`${cfg.mode}\`
- Auth mode: \`${cfg.authMode}\`
- Initiator signature: ${cfg.clientAlg === 'RSA' ? cfg.clientClassAlg : `ML-DSA-${cfg.clientSize}`}
- Responder signature: ${cfg.serverAlg === 'RSA' ? cfg.serverClassAlg : `ML-DSA-${cfg.serverSize}`}
- MTU: ${cfg.mtu}
- Fragmentation: ${cfg.allowFragmentation ? 'enabled' : 'disabled'}

## Files

- \`initiator/strongswan.conf\` — charon daemon options (initiator role)
- \`initiator/ipsec.conf\` — connection definition (initiator role)
- \`responder/strongswan.conf\` — charon daemon options (responder role)
- \`responder/ipsec.conf\` — connection definition (responder role)
${
  cfg.authMode === 'psk'
    ? '- `initiator/ipsec.secrets` + `responder/ipsec.secrets` — PSK material'
    : '- `initiator/certs/*.pem`, `responder/certs/*.pem` — generated self-signed certificates'
}

## Before you follow the next section

${EDUCATION_NOTICE}

The steps below exist so you can see how these files would be wired up, on a
throw-away lab host you are willing to lose. They are **not** a deployment
procedure: nothing in this bundle — configuration, PSK, certificate or key — is
fit to protect real data, and the "Simulator caveats" section below scopes what
the simulator does, not whether the result is safe to run. It is not.

## How to run against a real strongSwan daemon (lab hosts only)

1. Install strongSwan 6.x with the PKCS#11 plugin loaded.
2. Copy the \`initiator/\` or \`responder/\` subdirectory to the target host,
   e.g. \`/etc/strongswan/\` (path may vary by distribution).
3. If using dual auth, import the PEM certs into \`/etc/ipsec.d/certs/\` and
   ensure the matching private key exists on your PKCS#11 token at the same
   CKA_ID listed below.
4. Start/reload charon.

## Expected PKCS#11 handles (CKA_ID, hex)

- Initiator key: \`${cfg.initiatorCkaId ?? '(not provisioned yet)'}\`
- Responder key: \`${cfg.responderCkaId ?? '(not provisioned yet)'}\`

> Note: the simulator builds self-signed certs with a \`SubjectKeyIdentifier\`
> extension equal to the CKA_ID so strongSwan's pkcs11 plugin can locate
> the private key via \`C_FindObjects({CKA_ID=ski})\`.

## Simulator caveats

- The WASM simulator runs the full IKEv2 handshake for real: ML-KEM in the
  primary KE slot, ECP-256 as Additional KE 1 over a real IKE_INTERMEDIATE
  round (RFC 9242/9370), RFC 7383 fragmentation, and CHILD_SA negotiation
  (stub-kernel SPIs; no ESP data plane). strongSwan 6.0+ supports all of
  this natively — RFC 9370 multiple key exchanges, the \`mlkem512/768/1024\`
  proposal keywords, and \`ke1_\`–\`ke7_\` additional-KE prefixes — no patches
  required. The ML-KEM IKEv2 Key Exchange Method IDs (35/36/37) are
  IANA-assigned.
- ML-DSA certificate OIDs follow RFC 9881 (ML-DSA in X.509) — verify your
  peer strongSwan understands these OIDs before deploying. ML-DSA as an
  IKEv2 AUTH method (draft-sfluhrer-ipsecme-ikev2-mldsa) has no IANA
  assignment yet.

Generated ${new Date().toISOString()}.
`

export async function exportVpnConfigBundle(cfg: VpnConfigExport): Promise<void> {
  const zip = new JSZip()

  zip.file('README.md', README(cfg))

  // Every file in the bundle carries the notice, not just the README: these are
  // the files someone copies to a host, and the README is the one they leave
  // behind (education-notice remediation 2026-09-26).
  const noticed = (body: string) => withEducationNoticeComment(body, '#')

  zip.file('initiator/strongswan.conf', noticed(cfg.strongswanConfInit))
  zip.file('initiator/ipsec.conf', noticed(cfg.ipsecConfInit))

  zip.file('responder/strongswan.conf', noticed(cfg.strongswanConfResp))
  zip.file('responder/ipsec.conf', noticed(cfg.ipsecConfResp))

  if (cfg.authMode === 'psk') {
    zip.file(
      'initiator/ipsec.secrets',
      noticed(
        `# PSK for outbound connection — simulator-generated, NOT a secret.\n: PSK "${cfg.clientPsk}"\n`
      )
    )
    zip.file(
      'responder/ipsec.secrets',
      noticed(
        `# PSK for inbound connection — simulator-generated, NOT a secret.\n: PSK "${cfg.serverPsk}"\n`
      )
    )
  }

  if (cfg.authMode === 'dual') {
    // Each side needs BOTH certs: its own (leftcert=) and the peer's
    // (rightcert= / trust anchor for the self-signed peer cert) — mirrors
    // the worker provisioning flow in VpnSimulationPanel.
    if (cfg.initiatorCertPem) {
      zip.file('initiator/certs/initiator.crt', cfg.initiatorCertPem)
      zip.file('responder/certs/initiator.crt', cfg.initiatorCertPem)
    }
    if (cfg.responderCertPem) {
      zip.file('responder/certs/responder.crt', cfg.responderCertPem)
      zip.file('initiator/certs/responder.crt', cfg.responderCertPem)
    }
  }

  const blob = await zip.generateAsync({ type: 'blob' })
  const stamp = new Date().toISOString().replace(/[:.]/g, '-')
  saveAs(blob, `pqc-vpn-config-${cfg.mode}-${cfg.authMode}-${stamp}.zip`)
}
